/* Famous People, second helping: 15 more in each subsection, taking every
   one of them to 25. */
module.exports = {
"Famous People": [

/* ---------------- SPACE ---------------- */
{g:"Space",e:"🧐",q:"Which Indian mission went to Mars on its very first try?",o:[["🔴","Mangalyaan"],["🌙","Chandrayaan-2"],["☀️","Aditya-L1"],["🛰️","Gaganyaan"]],h:"Mangal is the Hindi name for the red planet."},
{g:"Space",e:"🤔",q:"What is the name of India's mission to study the Sun?",o:[["☀️","Aditya-L1"],["🌙","Chandrayaan-3"],["🔴","Mangalyaan"],["👨‍🚀","Gaganyaan"]],h:"Aditya is another name for the Sun."},
{g:"Space",e:"💭",q:"What is the name of India's planned mission to send people into space?",o:[["👨‍🚀","Gaganyaan"],["🌙","Chandrayaan"],["🔴","Mangalyaan"],["☀️","Aditya"]],h:"Gagan means the sky."},
{g:"Space",e:"🎓",q:"Which woman scientist was called the Rocket Woman of India for her work on Mangalyaan?",o:[["👩‍🔬","Ritu Karidhal"],["👩‍🚀","Kalpana Chawla"],["👩","Sunita Williams"],["👩‍✈️","Tessy Thomas"]],h:"She was the deputy operations director of the Mars mission."},
{g:"Space",e:"📝",q:"Who was the Chairman of ISRO when Chandrayaan-3 landed on the Moon?",o:[["🛰️","S Somanath"],["🚀","K Sivan"],["⚛️","Homi Bhabha"],["🔭","Vikram Sarabhai"]],h:"He led ISRO from 2022."},
{g:"Space",e:"🔎",q:"What was the name of the lander that touched down in Chandrayaan-3?",o:[["🛬","Vikram"],["🤖","Pragyan"],["🚀","Aryabhata"],["🛰️","Bhaskara"]],h:"Named after the father of India's space programme."},
{g:"Space",e:"🧐",q:"What was India's very first satellite called?",o:[["🛰️","Aryabhata"],["🌙","Chandrayaan"],["🔴","Mangalyaan"],["📡","INSAT"]],h:"Named after an ancient Indian mathematician."},
{g:"Space",e:"🤔",q:"Which woman is known as the Missile Woman of India?",o:[["🚀","Tessy Thomas"],["👩‍🚀","Kalpana Chawla"],["👩‍🔬","Ritu Karidhal"],["👩","Sunita Williams"]],h:"She led the Agni missile project."},
{g:"Space",e:"💭",q:"Which astronaut did Rakesh Sharma answer when asked how India looked from space?",o:[["🎩","Indira Gandhi"],["🌹","Jawaharlal Nehru"],["🧓","Mahatma Gandhi"],["🛡️","Sardar Patel"]],h:"The Prime Minister at the time, a woman."},
{g:"Space",e:"🎓",q:"Which American space agency sent people to the Moon?",o:[["🚀","NASA"],["🛰️","ISRO"],["🌌","ESA"],["🔭","JAXA"]],h:"Four letters, and it is in the United States."},
{g:"Space",e:"📝",q:"Which Indian-origin astronaut sadly died when her shuttle broke up in 2003?",o:[["👩‍🚀","Kalpana Chawla"],["👩","Sunita Williams"],["👨‍🚀","Rakesh Sharma"],["👩‍🔬","Ritu Karidhal"]],h:"The shuttle was called Columbia."},
{g:"Space",e:"🔎",q:"Where is India's main rocket launch centre?",o:[["🏝️","Sriharikota"],["🏙️","Bengaluru"],["🏔️","Dehradun"],["🌊","Kochi"]],h:"An island off the coast of Andhra Pradesh."},
{g:"Space",e:"🧐",q:"Which telescope in space takes the most famous pictures of stars?",o:[["🔭","Hubble"],["🛰️","Aryabhata"],["🌙","Chandrayaan"],["📡","INSAT"]],h:"Named after an American astronomer."},
{g:"Space",e:"🤔",q:"Which country was the first to land near the Moon's south pole?",o:[["🇮🇳","India"],["🇺🇸","United States"],["🇷🇺","Russia"],["🇨🇳","China"]],h:"It happened in August 2023, and the whole country celebrated."},
{g:"Space",e:"💭",q:"What do we call the suit an astronaut wears in space?",o:[["👨‍🚀","A spacesuit"],["🥼","A lab coat"],["🦺","A life jacket"],["🧥","A raincoat"]],h:"It gives them air and keeps them safe."},

/* ---------------- CRICKET ---------------- */
{g:"Cricket",e:"🎓",q:"Which Indian woman captained the team to the T20 World Cup final?",o:[["🧤","Harmanpreet Kaur"],["🏏","Mithali Raj"],["🎯","Jhulan Goswami"],["⭐","Smriti Mandhana"]],h:"She hit a famous 171 not out against Australia."},
{g:"Cricket",e:"📝",q:"Which Indian woman opener is famous for her elegant left-handed batting?",o:[["⭐","Smriti Mandhana"],["🏏","Mithali Raj"],["🎯","Jhulan Goswami"],["🧤","Harmanpreet Kaur"]],h:"She bats left-handed and is from Sangli."},
{g:"Cricket",e:"🔎",q:"Which captain led India to the very first T20 World Cup win in 2007?",o:[["🧤","MS Dhoni"],["🏏","Rahul Dravid"],["🧢","Sourav Ganguly"],["👑","Virat Kohli"]],h:"He was the young new captain that year."},
{g:"Cricket",e:"🧐",q:"Which Indian spinner is famous for bowling with a big turning ball?",o:[["🌀","Anil Kumble"],["🏏","Kapil Dev"],["🧤","MS Dhoni"],["🧢","Zaheer Khan"]],h:"He once took all ten wickets in one innings."},
{g:"Cricket",e:"🤔",q:"How many players are there in a cricket team on the field?",o:[["1️⃣1️⃣","Eleven"],["9️⃣","Nine"],["🔟","Ten"],["1️⃣2️⃣","Twelve"]],h:"One more than ten."},
{g:"Cricket",e:"💭",q:"What do we call it when a batsman scores one hundred runs?",o:[["💯","A century"],["5️⃣0️⃣","A fifty"],["6️⃣","A six"],["4️⃣","A boundary"]],h:"The same word as one hundred years."},
{g:"Cricket",e:"🎓",q:"Which Indian batsman was famous for hitting the very first ball for four?",o:[["💥","Virender Sehwag"],["🧱","Rahul Dravid"],["🏏","Sunil Gavaskar"],["🧤","MS Dhoni"]],h:"They called him the Nawab of Najafgarh."},
{g:"Cricket",e:"📝",q:"Which Indian captain was known as Dada and made the team fearless abroad?",o:[["🧢","Sourav Ganguly"],["🧤","MS Dhoni"],["🏏","Sachin Tendulkar"],["👑","Virat Kohli"]],h:"Dada means elder brother in Bengali."},
{g:"Cricket",e:"🔎",q:"What do we call the person who decides if a batsman is out?",o:[["☝️","The umpire"],["🧢","The captain"],["🧤","The wicketkeeper"],["📣","The commentator"]],h:"They raise one finger to give a decision."},
{g:"Cricket",e:"🧐",q:"How many stumps and bails make one wicket?",o:[["🪵","Three stumps and two bails"],["🪵","Two stumps and three bails"],["🪵","Four stumps and one bail"],["🪵","Three stumps and three bails"]],h:"There is one more stump than there are bails."},
{g:"Cricket",e:"🤔",q:"Which Indian bowler took the most wickets for India in Test cricket?",o:[["🌀","Anil Kumble"],["🏏","Kapil Dev"],["⚡","Zaheer Khan"],["🎯","Harbhajan Singh"]],h:"A leg-spinner who wore glasses."},
{g:"Cricket",e:"💭",q:"What is the trophy called that India and Australia play for in Test cricket?",o:[["🏆","Border-Gavaskar Trophy"],["🥇","Ashes"],["🏅","World Cup"],["🎖️","Champions Trophy"]],h:"Named after one great captain from each country."},
{g:"Cricket",e:"🎓",q:"Which Indian all-rounder both batted well and bowled fast in the 1983 win?",o:[["🏆","Kapil Dev"],["🏏","Sunil Gavaskar"],["🧤","Syed Kirmani"],["🧢","Mohinder Amarnath"]],h:"He was also the captain that year."},
{g:"Cricket",e:"📝",q:"What do we call six runs hit without the ball touching the ground?",o:[["6️⃣","A six"],["4️⃣","A four"],["💯","A century"],["1️⃣","A single"]],h:"The ball sails right over the boundary rope."},
{g:"Cricket",e:"🔎",q:"Which Indian city has the famous cricket ground called Eden Gardens?",o:[["🌉","Kolkata"],["🏙️","Mumbai"],["🕌","Delhi"],["🌴","Chennai"]],h:"The city of the Howrah Bridge."},

/* ---------------- SPORTS ---------------- */
{g:"Sports",e:"🧐",q:"Which sport does Neeraj Chopra play?",o:[["🎯","Javelin throw"],["🏸","Badminton"],["🥊","Boxing"],["🏹","Archery"]],h:"He throws a long light spear as far as he can."},
{g:"Sports",e:"🤔",q:"Which is India's national game as many people call it?",o:[["🏑","Hockey"],["🏏","Cricket"],["⚽","Football"],["🏸","Badminton"]],h:"India won eight Olympic golds in it."},
{g:"Sports",e:"💭",q:"Which Indian badminton player won the All England championship in 1980?",o:[["🏸","Prakash Padukone"],["🎾","Sania Mirza"],["🏑","Dhyan Chand"],["♟️","Viswanathan Anand"]],h:"His daughter is a famous film actor."},
{g:"Sports",e:"🎓",q:"Which Indian wrestler won two Olympic medals?",o:[["🤼","Sushil Kumar"],["🥊","Vijender Singh"],["🎯","Abhinav Bindra"],["🏸","Saina Nehwal"]],h:"He wrestles on a mat, not in a ring."},
{g:"Sports",e:"📝",q:"How many rings are there on the Olympic flag?",o:[["5️⃣","Five"],["4️⃣","Four"],["6️⃣","Six"],["3️⃣","Three"]],h:"One for each of the inhabited continents."},
{g:"Sports",e:"🔎",q:"Which Indian sprinter from Assam won a world under-20 gold?",o:[["🏃","Hima Das"],["🏅","PT Usha"],["🥊","Mary Kom"],["🏸","Saina Nehwal"]],h:"People call her the Dhing Express."},
{g:"Sports",e:"🧐",q:"Which Indian badminton player won an Olympic bronze in 2012?",o:[["🏸","Saina Nehwal"],["🎾","Sania Mirza"],["🥊","Mary Kom"],["🏃","PT Usha"]],h:"She was the first Indian woman to win an Olympic badminton medal."},
{g:"Sports",e:"🤔",q:"In which sport would you find a googly and a yorker?",o:[["🏏","Cricket"],["🏑","Hockey"],["🏸","Badminton"],["⚽","Football"]],h:"Both are ways of bowling a ball."},
{g:"Sports",e:"💭",q:"Which Indian footballer captained the national team for many years?",o:[["⚽","Sunil Chhetri"],["🏑","Dhyan Chand"],["🏏","Virat Kohli"],["🏸","Lakshya Sen"]],h:"He has scored more international goals than almost anyone alive."},
{g:"Sports",e:"🎓",q:"How often are the Summer Olympic Games held?",o:[["4️⃣","Every four years"],["1️⃣","Every year"],["2️⃣","Every two years"],["🔟","Every ten years"]],h:"The same gap as a leap year cycle."},
{g:"Sports",e:"📝",q:"Which Indian para-athlete won gold in javelin at the Paralympics?",o:[["🥇","Sumit Antil"],["🎯","Neeraj Chopra"],["🏸","Saina Nehwal"],["🥊","Mary Kom"]],h:"He throws javelin from a standing start with a prosthetic leg."},
{g:"Sports",e:"🔎",q:"Which Indian shuttler won gold at the World Championships in 2019?",o:[["🏸","PV Sindhu"],["🎾","Sania Mirza"],["🏃","Hima Das"],["🥊","Mary Kom"]],h:"She already had an Olympic silver by then."},
{g:"Sports",e:"🧐",q:"In chess, which piece can jump over the others?",o:[["🐴","The knight"],["♛","The queen"],["♜","The rook"],["♝","The bishop"]],h:"It moves in the shape of the letter L."},
{g:"Sports",e:"🤔",q:"Which game is played on a board of 64 black and white squares?",o:[["♟️","Chess"],["🎲","Ludo"],["🀄","Carrom"],["🎯","Darts"]],h:"Eight rows of eight."},
{g:"Sports",e:"💭",q:"Which Indian city hosted the Commonwealth Games in 2010?",o:[["🕌","New Delhi"],["🏙️","Mumbai"],["🌉","Kolkata"],["🌴","Chennai"]],h:"Our capital city."},

/* ---------------- FREEDOM ---------------- */
{g:"Freedom",e:"🎓",q:"On which date did India become free?",o:[["🇮🇳","15 August 1947"],["📜","26 January 1950"],["🗓️","2 October 1869"],["📅","15 August 1950"]],h:"We fly the flag and eat sweets on this day."},
{g:"Freedom",e:"📝",q:"On which date did our Constitution come into force?",o:[["📜","26 January 1950"],["🇮🇳","15 August 1947"],["🗓️","2 October 1947"],["📅","26 January 1947"]],h:"We call that day Republic Day."},
{g:"Freedom",e:"🔎",q:"Whose birthday do we celebrate as Gandhi Jayanti?",o:[["🧓","Mahatma Gandhi"],["🌹","Jawaharlal Nehru"],["🛡️","Sardar Patel"],["📘","Dr Ambedkar"]],h:"The second of October."},
{g:"Freedom",e:"🧐",q:"What was Mahatma Gandhi's full name?",o:[["🧓","Mohandas Karamchand Gandhi"],["👤","Mohan Kumar Gandhi"],["👤","Mahesh Chandra Gandhi"],["👤","Madan Krishna Gandhi"]],h:"His first name was Mohandas."},
{g:"Freedom",e:"🤔",q:"Which famous march did Gandhi lead to make salt from the sea?",o:[["🧂","The Dandi March"],["🚶","The Long March"],["🌊","The Sea March"],["🏔️","The Hill March"]],h:"Named after the seaside village where it ended."},
{g:"Freedom",e:"💭",q:"Which army did Subhas Chandra Bose lead?",o:[["🎖️","The Indian National Army"],["⚔️","The Royal Army"],["🛡️","The Maratha Army"],["🏹","The Sikh Army"]],h:"Often called the INA, or Azad Hind Fauj."},
{g:"Freedom",e:"❓",q:"Who was the first President of India?",o:[["📘","Dr Rajendra Prasad"],["🌹","Jawaharlal Nehru"],["🎓","S Radhakrishnan"],["🚀","APJ Abdul Kalam"]],h:"He led the meetings that wrote the Constitution."},
{g:"Freedom",e:"📝",q:"Whose birthday do we celebrate as Teachers' Day?",o:[["🎓","Dr S Radhakrishnan"],["🌹","Jawaharlal Nehru"],["🧓","Mahatma Gandhi"],["📘","Dr Ambedkar"]],h:"He was a teacher before he became President."},
{g:"Freedom",e:"🔎",q:"Which slogan did Gandhi give in 1942 asking the British to leave?",o:[["📢","Quit India"],["⚔️","Do or Die only"],["🇮🇳","Jai Hind"],["🕊️","Vande Mataram"]],h:"Two words, telling them to go."},
{g:"Freedom",e:"🧐",q:"Who wrote the song Vande Mataram?",o:[["📜","Bankim Chandra Chatterjee"],["✍️","Rabindranath Tagore"],["🖋️","Sarojini Naidu"],["📖","Munshi Premchand"]],h:"It comes from his novel Anandamath."},
{g:"Freedom",e:"🤔",q:"Which freedom fighter was called Punjab Kesari, the Lion of Punjab?",o:[["🦁","Lala Lajpat Rai"],["📢","Bal Gangadhar Tilak"],["⚔️","Bhagat Singh"],["🛡️","Sardar Patel"]],h:"He was one of the trio Lal, Bal and Pal."},
{g:"Freedom",e:"💭",q:"What did Gandhi call the path of non-violence?",o:[["🕊️","Ahimsa"],["⚔️","Kranti"],["📢","Swadeshi"],["🛡️","Satyagraha only"]],h:"A means not, and himsa means harm."},
{g:"Freedom",e:"🎓",q:"Which young woman fought the British alongside Rani Lakshmibai?",o:[["🗡️","Jhalkaribai"],["👑","Razia Sultan"],["🏹","Ahilyabai Holkar"],["⚔️","Chand Bibi"]],h:"She looked so like the queen that she took her place in battle."},
{g:"Freedom",e:"📝",q:"Which garden saw a terrible massacre in Amritsar in 1919?",o:[["🌳","Jallianwala Bagh"],["🏛️","Shalimar Bagh"],["🌺","Mughal Gardens"],["🌿","Lodhi Gardens"]],h:"There is a memorial there with bullet marks on the walls."},
{g:"Freedom",e:"🔎",q:"What is the Hindi phrase Gandhi used for self-rule?",o:[["🇮🇳","Swaraj"],["🕊️","Ahimsa"],["🧵","Khadi"],["📢","Satyagraha"]],h:"Swa means one's own, and raj means rule."},

/* ---------------- SCIENCE ---------------- */
{g:"Science",e:"🧐",q:"Which Indian-American scientist won a Nobel Prize for work on genes?",o:[["🧬","Har Gobind Khorana"],["🔬","CV Raman"],["⚛️","Homi Bhabha"],["🌱","JC Bose"]],h:"He helped work out the genetic code."},
{g:"Science",e:"🤔",q:"Which Indian astrophysicist won a Nobel Prize for work on stars?",o:[["⭐","Subrahmanyan Chandrasekhar"],["🔬","CV Raman"],["🧬","Har Gobind Khorana"],["⚛️","Homi Bhabha"]],h:"A limit for dying stars carries his name."},
{g:"Science",e:"💭",q:"Which Indian scientist led the Green Revolution that grew more food?",o:[["🌾","MS Swaminathan"],["🥛","Verghese Kurien"],["🔬","CV Raman"],["🌱","JC Bose"]],h:"He bred wheat that gave far bigger harvests."},
{g:"Science",e:"🎓",q:"Who led India's White Revolution and made it rich in milk?",o:[["🥛","Verghese Kurien"],["🌾","MS Swaminathan"],["⚛️","Homi Bhabha"],["🛰️","Vikram Sarabhai"]],h:"He founded Amul in Gujarat."},
{g:"Science",e:"📝",q:"Which Indian doctor is Doctors' Day named after?",o:[["🩺","Dr B C Roy"],["💉","Dr Salim Ali"],["🔬","Dr CV Raman"],["🧬","Dr Khorana"]],h:"He was also Chief Minister of West Bengal."},
{g:"Science",e:"🔎",q:"Which Indian scientist was famous for studying birds?",o:[["🐦","Salim Ali"],["🌱","JC Bose"],["🔬","CV Raman"],["🌾","MS Swaminathan"]],h:"People call him the Birdman of India."},
{g:"Science",e:"🧐",q:"Who discovered that the Earth goes round the Sun, not the other way?",o:[["☀️","Copernicus"],["🍎","Newton"],["⚛️","Einstein"],["💡","Edison"]],h:"He put the Sun at the centre, long ago in Poland."},
{g:"Science",e:"🤔",q:"Which scientist discovered penicillin by accident?",o:[["🧫","Alexander Fleming"],["💉","Louis Pasteur"],["🔬","Robert Koch"],["🧬","Gregor Mendel"]],h:"A mould grew on a dish he had left out."},
{g:"Science",e:"💭",q:"Which woman scientist won two Nobel Prizes for her work on radioactivity?",o:[["⚛️","Marie Curie"],["🧬","Rosalind Franklin"],["🔬","Ada Lovelace"],["🌱","Jane Goodall"]],h:"She discovered radium and polonium."},
{g:"Science",e:"🎓",q:"Which scientist explained how animals change slowly over a very long time?",o:[["🐢","Charles Darwin"],["🍎","Isaac Newton"],["⚛️","Albert Einstein"],["🔭","Galileo"]],h:"He sailed on a ship called the Beagle."},
{g:"Science",e:"📝",q:"Who is often called the father of the computer for designing the first one?",o:[["🖩","Charles Babbage"],["💡","Thomas Edison"],["📞","Graham Bell"],["⚛️","Einstein"]],h:"He designed an Analytical Engine made of gears."},
{g:"Science",e:"🔎",q:"Which Indian mathematician wrote the ancient book Aryabhatiya?",o:[["📐","Aryabhata"],["🔢","Ramanujan"],["🧮","Bhaskara"],["➗","Brahmagupta"]],h:"The book carries his own name."},
{g:"Science",e:"🧐",q:"Which scientist invented the radio?",o:[["📻","Guglielmo Marconi"],["💡","Thomas Edison"],["📞","Graham Bell"],["🍎","Isaac Newton"]],h:"An Italian, and he sent signals without any wires."},
{g:"Science",e:"🤔",q:"Which two brothers built and flew the first aeroplane?",o:[["✈️","The Wright brothers"],["🚂","The Stephenson brothers"],["🚗","The Ford brothers"],["🚲","The Michaux brothers"]],h:"Orville and Wilbur, in America."},
{g:"Science",e:"💭",q:"On whose birthday do we celebrate National Science Day in India?",o:[["🔬","CV Raman's discovery"],["⚛️","Homi Bhabha"],["🌱","JC Bose"],["🚀","APJ Abdul Kalam"]],h:"It marks the day he announced his effect, on 28 February."},

/* ---------------- ARTS ---------------- */
{g:"Arts",e:"🎓",q:"Which Indian sitar player's daughter is also a famous musician?",o:[["🎸","Ravi Shankar"],["🪈","Bismillah Khan"],["🥁","Zakir Hussain"],["🎻","Amjad Ali Khan"]],h:"Anoushka carries on his music."},
{g:"Arts",e:"📝",q:"Which classical dance comes from Tamil Nadu?",o:[["💃","Bharatanatyam"],["🎭","Kathakali"],["🪘","Kathak"],["🕺","Manipuri"]],h:"The oldest of them all, danced in temples."},
{g:"Arts",e:"🔎",q:"Which classical dance from North India is famous for fast spins?",o:[["🪘","Kathak"],["💃","Bharatanatyam"],["🎭","Kathakali"],["🕺","Odissi"]],h:"The name comes from katha, a story."},
{g:"Arts",e:"🧐",q:"Which Indian painter is famous for beautiful paintings of gods and queens?",o:[["🖌️","Raja Ravi Varma"],["🎨","MF Husain"],["🖼️","Amrita Sher-Gil"],["✏️","Jamini Roy"]],h:"He was from Kerala, and a prince."},
{g:"Arts",e:"🤔",q:"Which instrument does a tabla player use?",o:[["🥁","A pair of drums"],["🎸","Strings"],["🪈","A pipe"],["🎹","Keys"]],h:"Two of them, played with the palms and fingers."},
{g:"Arts",e:"💭",q:"Which instrument has many strings and is played by plucking, made famous by Ravi Shankar?",o:[["🎸","The sitar"],["🥁","The tabla"],["🪈","The flute"],["🎻","The sarod"]],h:"It has a long neck and a round gourd body."},
{g:"Arts",e:"🎓",q:"Which Indian flute player is world famous?",o:[["🪈","Hariprasad Chaurasia"],["🎸","Ravi Shankar"],["🥁","Zakir Hussain"],["🎻","Amjad Ali Khan"]],h:"He plays the bansuri, Krishna's instrument."},
{g:"Arts",e:"📝",q:"Which Indian singer sang for films alongside her sister Lata?",o:[["🎤","Asha Bhosle"],["🎶","Shreya Ghoshal"],["🎵","Geeta Dutt"],["🎼","Alka Yagnik"]],h:"Two sisters, both legends of playback singing."},
{g:"Arts",e:"🔎",q:"Which Indian music director won two Oscars for Slumdog Millionaire?",o:[["🎬","AR Rahman"],["🎸","Ravi Shankar"],["🥁","Zakir Hussain"],["🎤","Asha Bhosle"]],h:"From Chennai, and he wrote Jai Ho."},
{g:"Arts",e:"🧐",q:"Which dance form comes from Odisha?",o:[["🕺","Odissi"],["💃","Bharatanatyam"],["🎭","Kathakali"],["🪘","Kathak"]],h:"The name sounds like the state it comes from."},
{g:"Arts",e:"🤔",q:"Which Indian writer wrote stories about the town of Malgudi?",o:[["📜","RK Narayan"],["📖","Munshi Premchand"],["✍️","Rabindranath Tagore"],["🖋️","Ruskin Bond"]],h:"Malgudi Days was made into a television show."},
{g:"Arts",e:"💭",q:"Which writer living in Mussoorie is loved for children's stories about the hills?",o:[["🖋️","Ruskin Bond"],["📜","RK Narayan"],["📖","Munshi Premchand"],["✍️","Rabindranath Tagore"]],h:"He wrote The Blue Umbrella."},
{g:"Arts",e:"🎓",q:"Which Indian woman painter is famous for paintings of village women?",o:[["🖼️","Amrita Sher-Gil"],["🎨","MF Husain"],["🖌️","Raja Ravi Varma"],["✏️","Jamini Roy"]],h:"She died very young, but her paintings are treasures."},
{g:"Arts",e:"📝",q:"Which Indian art form uses coloured powder on the floor at festivals?",o:[["🌸","Rangoli"],["🎨","Madhubani"],["🖼️","Warli"],["🪔","Kolam only"]],h:"Made fresh at the doorstep every morning."},
{g:"Arts",e:"🔎",q:"Which folk painting style comes from Bihar and uses bright natural colours?",o:[["🎨","Madhubani"],["🖼️","Warli"],["🌸","Rangoli"],["✏️","Pattachitra"]],h:"Named after a town in Bihar."}
]
};
