module.exports = {
"Our India": [
{e:"🇮🇳",q:"Which colour in our flag is also called saffron?",o:[["🟧","Orange"],["🟩","Green"],["⬜","White"],["🔵","Blue"]],h:"Kesari! The top stripe."},
{e:"📜",q:"Who designed our national flag?",o:[["✍️","Pingali Venkayya"],["🧓","Gandhi ji"],["🌹","Nehru ji"],["🚀","Dr Kalam"]],h:"A freedom fighter from Andhra Pradesh."},
{e:"🔍",q:"What is written below the lions on our national emblem?",o:[["📜","Satyameva Jayate"],["🎵","Jana Gana Mana"],["🇮🇳","Vande Mataram"],["🌸","Namaste"]],h:"It means: truth alone wins."},
{e:"🧐",q:"What does Satyameva Jayate mean?",o:[["✅","Truth alone wins"],["💪","Strength alone wins"],["💰","Money alone wins"],["🏃","Speed alone wins"]],h:"Satya means truth."},
{e:"🎓",q:"How many lions can we see on our national emblem?",o:[["3️⃣","Three"],["4️⃣","Four"],["2️⃣","Two"],["1️⃣","One"]],h:"There are four, but one always hides behind!"},
{e:"📖",q:"Which is our national vegetable?",o:[["🎃","Pumpkin"],["🥔","Potato"],["🧅","Onion"],["🥕","Carrot"]],h:"Big, round and orange. Kaddu!"},
{e:"💭",q:"On which day do we celebrate National Sports Day?",o:[["8️⃣","29 August"],["1️⃣5️⃣","15 August"],["2️⃣6️⃣","26 January"],["2️⃣","2 October"]],h:"Just before Independence Day month ends."},
{e:"🇮🇳",q:"Which slogan did Lal Bahadur Shastri give to India?",o:[["🌾","Jai Jawan Jai Kisan"],["🎵","Jana Gana Mana"],["🙏","Namaste India"],["🪔","Happy Diwali"]],h:"It praises the soldier and the farmer."},
{e:"📜",q:"Who gave the slogan 'Give me blood, I will give you freedom'?",o:[["🎖️","Subhash Chandra Bose"],["🧓","Gandhi ji"],["🌹","Nehru ji"],["✍️","Tagore"]],h:"Netaji! He led the Azad Hind Fauj."},
{e:"🔍",q:"What do we call Subhash Chandra Bose lovingly?",o:[["🎖️","Netaji"],["👴","Bapu"],["🧒","Chacha"],["🗿","Sardar"]],h:"It means 'respected leader'."},
{e:"🧐",q:"Which colour cap did Gandhi ji make famous?",o:[["⬜","A white cap"],["🔴","A red cap"],["⚫","A black cap"],["🟢","A green cap"]],h:"We still call it the Gandhi topi."},
{e:"🎓",q:"On Republic Day, who takes the salute at the parade?",o:[["🏛️","The President"],["👩‍🏫","A teacher"],["🩺","A doctor"],["👮","A policeman"]],h:"The highest person in our country."},
{e:"📖",q:"Which book tells us all the rules of our country?",o:[["📕","The Constitution"],["🏹","The Ramayana"],["📗","A dictionary"],["📘","A storybook"]],h:"Samvidhan! Republic Day celebrates the day it started."},
{e:"💭",q:"Who wrote our Constitution?",o:[["📕","Dr B.R. Ambedkar"],["🧓","Gandhi ji"],["✍️","Tagore"],["🚀","Dr Kalam"]],h:"We call him the Father of the Constitution."},
{e:"🇮🇳",q:"How many colours does the Ashoka Chakra have?",o:[["1️⃣","One"],["2️⃣","Two"],["3️⃣","Three"],["7️⃣","Seven"]],h:"It is all one colour: navy blue."},
{e:"📜",q:"Which festival do we celebrate for our soldiers on 26 July?",o:[["🎖️","Kargil Vijay Diwas"],["🪔","Diwali"],["🎨","Holi"],["🪁","Makar Sankranti"]],h:"It remembers the brave Kargil soldiers."},
{e:"🔍",q:"Which is India's highest award for bravery in war?",o:[["🏅","Param Vir Chakra"],["🥇","A gold medal"],["🏆","A trophy"],["🎗️","A ribbon"]],h:"Param means the highest, Vir means brave."},
{e:"🧐",q:"What do we call the soldiers who guard our country?",o:[["🎖️","The Army"],["👨‍🍳","Cooks"],["👩‍🏫","Teachers"],["🚗","Drivers"]],h:"They protect our borders day and night."},
{e:"🎓",q:"Which Indian city is called the City of Nawabs?",o:[["🕌","Lucknow"],["🏖️","Goa"],["❄️","Shimla"],["🌴","Kochi"]],h:"Famous for its polite manners and kebabs."},
{e:"📖",q:"Which is our national microbe... no, which is our national reptile?",o:[["🐍","King Cobra"],["🐊","Crocodile"],["🐢","Tortoise"],["🦎","Lizard"]],h:"The longest venomous snake in the world."},
{e:"💭",q:"In which month do most Indian schools have summer holidays?",o:[["☀️","May"],["❄️","January"],["🎄","December"],["🌧️","August"]],h:"The hottest month of all."},
{e:"🇮🇳",q:"What do we call the boundary line between two countries?",o:[["🛂","The border"],["🌉","A bridge"],["🛣️","A road"],["🏞️","A river"]],h:"Soldiers stand guard there."},
{e:"📜",q:"Which Indian scientist's birthday is National Science Day?",o:[["🔬","C.V. Raman"],["🧓","Gandhi ji"],["🌹","Nehru ji"],["🏏","Sachin"]],h:"He won the Nobel Prize for the Raman Effect."},
{e:"🔍",q:"What colour clothes did Gandhi ji always wear?",o:[["⬜","Plain white khadi"],["🟥","Red silk"],["⬛","Black wool"],["🟨","Yellow satin"]],h:"Simple cloth he spun himself."},
{e:"🧐",q:"What did Gandhi ji use to spin cloth at home?",o:[["🧵","A charkha"],["🚗","A car"],["📻","A radio"],["🪈","A flute"]],h:"A spinning wheel. It is on the old flag design!"}
],

"Animals & Birds": [
{e:"🐾",q:"Odd one out: which animal does NOT live in water?",o:[["🐐","Goat"],["🐟","Fish"],["🐙","Octopus"],["🦀","Crab"]],h:"Three of them would drown on land."},
{e:"🔍",q:"Which animal sleeps standing up?",o:[["🐎","Horse"],["🐈","Cat"],["🐕","Dog"],["🐇","Rabbit"]],h:"It can lock its legs and doze on its feet!"},
{e:"🧐",q:"Which bird builds the most beautiful hanging nest?",o:[["🪺","Weaver bird"],["🐦‍⬛","Crow"],["🦆","Duck"],["🐓","Cock"]],h:"Baya! It weaves grass like a basket."},
{e:"🎓",q:"Which animal can change the colour of its skin?",o:[["🦎","Chameleon"],["🐄","Cow"],["🐕","Dog"],["🐇","Rabbit"]],h:"It hides by matching the leaves."},
{e:"📖",q:"Which is the largest bird's egg?",o:[["🪶","An ostrich egg"],["🐔","A hen's egg"],["🐦","A sparrow's egg"],["🦜","A parrot's egg"]],h:"The biggest bird lays the biggest egg."},
{e:"🐾",q:"Which animal carries its baby on its back in the water?",o:[["🐊","Crocodile"],["🐄","Cow"],["🐐","Goat"],["🐕","Dog"]],h:"A surprisingly gentle mother, with many teeth!"},
{e:"🔍",q:"Which insect has a hard shell with pretty spots?",o:[["🐞","Ladybug"],["🐜","Ant"],["🦟","Mosquito"],["🕷️","Spider"]],h:"Red with black dots."},
{e:"🧐",q:"Which tiny insect bites us and spreads illness?",o:[["🦟","Mosquito"],["🦋","Butterfly"],["🐝","Bee"],["🐞","Ladybug"]],h:"It buzzes near your ear at night."},
{e:"🎓",q:"How do we stop mosquitoes breeding at home?",o:[["🪣","Never let water stand still"],["🍬","Feed them sugar"],["🪟","Open all windows"],["💡","Keep lights on"]],h:"They lay eggs in still water."},
{e:"📖",q:"Which animal is known for never forgetting?",o:[["🐘","The elephant"],["🐟","The fish"],["🐜","The ant"],["🐛","The worm"]],h:"People say it has a very long memory."},
{e:"🐾",q:"Which bird is India's smallest and hovers near flowers?",o:[["🐦","Sunbird"],["🦅","Eagle"],["🦚","Peacock"],["🦢","Swan"]],h:"Tiny and shiny, it sips nectar."},
{e:"🔍",q:"Which animal do we get silk from?",o:[["🐛","The silkworm"],["🐄","The cow"],["🐑","The sheep"],["🐔","The hen"]],h:"It spins a cocoon of fine thread."},
{e:"🧐",q:"Which animal has a pouch AND lives only in India's forests? Careful!",o:[["❌","None of these"],["🦘","Kangaroo"],["🐨","Koala"],["🦥","Sloth"]],h:"All three of those live far away, not in India."},
{e:"🎓",q:"Which bird do farmers like because it eats harmful insects?",o:[["🐦","Sparrow"],["🦅","Eagle"],["🦢","Swan"],["🐧","Penguin"]],h:"Small, brown, and hops around the fields."},
{e:"📖",q:"What do we call animals that eat only plants?",o:[["🌿","Herbivores"],["🥩","Carnivores"],["🍽️","Omnivores"],["🐟","Fish"]],h:"Herb means plant."},
{e:"🐾",q:"What do we call animals that eat other animals?",o:[["🥩","Carnivores"],["🌿","Herbivores"],["🍽️","Omnivores"],["🐦","Birds"]],h:"Lions and tigers are these."},
{e:"🔍",q:"Odd one out by FOOD: which one eats only plants?",o:[["🐄","Cow"],["🦁","Lion"],["🐅","Tiger"],["🐊","Crocodile"]],h:"Three of them hunt. One only grazes."},
{e:"🧐",q:"Which animal helps blind people find their way?",o:[["🦮","A guide dog"],["🐈","A cat"],["🐀","A rat"],["🐟","A fish"]],h:"Specially trained, and very patient."},
{e:"🎓",q:"Which animal is the tallest in the world?",o:[["🦒","Giraffe"],["🐘","Elephant"],["🐎","Horse"],["🐪","Camel"]],h:"That very long neck wins it."},
{e:"📖",q:"Where does a rabbit live?",o:[["🕳️","In a burrow"],["🪹","In a nest"],["🐴","In a stable"],["🌊","In water"]],h:"A tunnel it digs under the ground."},
{e:"🐾",q:"What do we call a group of lions?",o:[["👑","A pride"],["🐟","A school"],["🐝","A swarm"],["🐑","A flock"]],h:"It sounds like being proud!"},
{e:"🔍",q:"What do we call a group of fish swimming together?",o:[["🏫","A school"],["👑","A pride"],["🐝","A swarm"],["🐑","A flock"]],h:"The same word as where you study!"},
{e:"🧐",q:"Which animal is awake all night and sleeps all day?",o:[["🦇","Bat"],["🐔","Hen"],["🐄","Cow"],["🦚","Peacock"]],h:"It hangs upside down to sleep."},
{e:"🎓",q:"Why should we never disturb a bird's nest?",o:[["🥚","The mother may leave her eggs"],["🎨","It looks untidy"],["🔊","It is noisy"],["🤷","No reason"]],h:"A frightened mother bird may not come back."},
{e:"📖",q:"Which Indian animal reserve project saves our national animal?",o:[["🐅","Project Tiger"],["🐘","Project Bus"],["🐄","Project Milk"],["🦜","Project Parrot"]],h:"It protects the striped one."}
]
};
