module.exports = {
"Space": [
{e:"🌌",q:"Which Indian rocket is nicknamed the workhorse of ISRO?",o:[["🚀","PSLV"],["🚂","Train"],["✈️","Jet"],["⛵","Boat"]],h:"It has launched hundreds of satellites."},
{e:"🔍",q:"In which year did Chandrayaan-3 land on the Moon?",o:[["2️⃣3️⃣","2023"],["1️⃣9️⃣","1999"],["2️⃣0️⃣","2005"],["1️⃣9️⃣","1969"]],h:"Quite recently. All of India watched it live."},
{e:"🧐",q:"Near which part of the Moon did Chandrayaan-3 land?",o:[["⬇️","The south pole"],["🏙️","A city"],["🌊","A sea"],["🌴","A forest"]],h:"India was the first country ever to land there."},
{e:"🎓",q:"What is the name of the little rover Chandrayaan-3 carried?",o:[["🤖","Pragyan"],["🚗","Maruti"],["🚂","Rail"],["🛵","Scooter"]],h:"Pragyan means wisdom."},
{e:"📖",q:"Who is called the father of India's space programme?",o:[["🚀","Vikram Sarabhai"],["🧓","Gandhi ji"],["✍️","Tagore"],["🏏","Sachin"]],h:"ISRO's lander was named after him."},
{e:"🌌",q:"What do we call the huge burning ball at the centre of our solar system?",o:[["☀️","The Sun"],["🌙","The Moon"],["🌍","The Earth"],["🪐","Saturn"]],h:"Everything goes around it."},
{e:"🔍",q:"Why does the Moon shine at night?",o:[["☀️","It reflects the Sun's light"],["🔥","It is burning"],["💡","It has bulbs"],["⚡","It makes lightning"]],h:"It has no light of its own at all."},
{e:"🧐",q:"Why do stars look so tiny to us?",o:[["📏","They are very, very far away"],["🤏","They are really small"],["☁️","Clouds shrink them"],["👁️","Our eyes are weak"]],h:"Many are far bigger than our Sun."},
{e:"🎓",q:"Which planet comes right after Earth, away from the Sun?",o:[["🔴","Mars"],["🟡","Venus"],["🟤","Mercury"],["🪐","Saturn"]],h:"The red one, our next-door neighbour."},
{e:"📖",q:"Which planet is nearest to Earth?",o:[["🟡","Venus"],["🪐","Saturn"],["🪐","Jupiter"],["🟦","Neptune"]],h:"The bright evening star."},
{e:"🌌",q:"What do astronauts float in when they leave Earth?",o:[["🎈","Zero gravity"],["🌊","Water"],["🏖️","Sand"],["🧊","Ice"]],h:"Nothing pulls them down out there."},
{e:"🔍",q:"What do we call the suit-shaped vehicle astronauts live in, going round Earth?",o:[["🛰️","A space station"],["🏠","A house"],["🚌","A bus"],["⛵","A boat"]],h:"A laboratory floating in orbit."},
{e:"🧐",q:"How long does light from the Sun take to reach Earth?",o:[["⏱️","About 8 minutes"],["⚡","One second"],["📆","One day"],["🗓️","One year"]],h:"Fast, but not instant. It is very far!"},
{e:"🎓",q:"Which is the hottest planet in our solar system?",o:[["🟡","Venus"],["🟤","Mercury"],["🌍","Earth"],["🔴","Mars"]],h:"Not the closest one. Thick clouds trap the heat."},
{e:"📖",q:"Which planet spins on its side, almost lying down?",o:[["🟦","Uranus"],["🌍","Earth"],["🔴","Mars"],["🟡","Venus"]],h:"It rolls along like a ball instead of spinning like a top."},
{e:"🌌",q:"What do we call a rock from space that lands on Earth?",o:[["🪨","A meteorite"],["🌈","A rainbow"],["☁️","A cloud"],["🪁","A kite"]],h:"If it survives the fall and hits the ground."},
{e:"🔍",q:"What protects Earth from most space rocks?",o:[["🌬️","Our blanket of air"],["🌊","The sea"],["🏔️","The mountains"],["🌳","The trees"]],h:"They burn up as they rush through it."},
{e:"🧐",q:"Which Indian mission first found signs of water on the Moon?",o:[["🌙","Chandrayaan-1"],["🔴","Mangalyaan"],["🧑‍🚀","Gaganyaan"],["🚂","Railyaan"]],h:"The very first Indian Moon mission."},
{e:"🎓",q:"How many Indians have travelled to space so far as of today?",o:[["🤏","Very few"],["💯","Hundreds"],["🔢","Thousands"],["0️⃣","None at all"]],h:"You can nearly count them on one hand."},
{e:"📖",q:"What do we call the huge group of stars our Sun belongs to?",o:[["🌌","A galaxy"],["🏫","A school"],["🌳","A forest"],["🏙️","A city"]],h:"Ours is called Akash Ganga, the Milky Way."},
{e:"🌌",q:"Can we hear any sound in outer space?",o:[["🤫","No, it is completely silent"],["🔊","Yes, very loudly"],["🎵","Yes, like music"],["📣","Only shouting"]],h:"Sound needs air to travel. There is none out there."},
{e:"🔍",q:"What do we wear on Earth that astronauts also need, to see in bright sunlight?",o:[["🕶️","A dark visor"],["🧤","Gloves"],["👟","Shoes"],["🧢","A cap"]],h:"The Sun is blinding with no air to soften it."},
{e:"🧐",q:"Which direction do all the planets travel around the Sun?",o:[["🔄","All in the same direction"],["↔️","Each a different way"],["⬆️","Straight up"],["🛑","They do not move"]],h:"Like runners all going round the same track."},
{e:"🎓",q:"Why can we not live on the Moon right now?",o:[["🚫","No air, no water, too hot and too cold"],["👻","It is haunted"],["🏙️","It is too crowded"],["💰","It costs too much"]],h:"Astronauts must carry everything with them."},
{e:"📖",q:"What is the name of India's satellite navigation system?",o:[["🧭","NavIC"],["🗺️","Map"],["📍","Pin"],["🧲","Magnet"]],h:"It helps Indian phones and ships find their way."}
],

"Transport & Safety": [
{e:"🚦",q:"What should we do if we see a fire in a building?",o:[["🚪","Go out calmly and call 101"],["🛗","Take the lift"],["🙈","Hide under a bed"],["📦","Collect our things first"]],h:"Never use the lift during a fire."},
{e:"🔍",q:"Why should we never use a lift during a fire?",o:[["⚡","It can stop and trap you"],["🐌","It is slow"],["💰","It costs money"],["📣","It is noisy"]],h:"The power may cut off. Use the stairs."},
{e:"🧐",q:"Which way should we crawl if a room is full of smoke?",o:[["⬇️","Low, near the floor"],["⬆️","High, with arms up"],["🏃","Running upright"],["🤸","Jumping"]],h:"Smoke rises, so clean air stays low down."},
{e:"🎓",q:"What is the safest seat for a child in a car?",o:[["💺","The back seat, belted in"],["🎡","The front seat"],["🪟","On a lap by the window"],["🦵","On the driver's lap"]],h:"Never in front, because of the airbag."},
{e:"📖",q:"What should we do before opening a car door on a busy road?",o:[["👀","Look behind for bikes and cars"],["🏃","Push it open fast"],["🙈","Close our eyes"],["📣","Shout"]],h:"A cyclist could be passing right beside you."},
{e:"🚦",q:"Which lane should slow vehicles use on a highway?",o:[["⬅️","The left lane"],["➡️","The right lane"],["↔️","The middle only"],["🤷","Any lane"]],h:"In India we keep left; faster traffic overtakes on the right."},
{e:"🔍",q:"What does a zebra crossing signal to a driver?",o:[["🚶","Walkers may cross here"],["💨","Drive faster"],["🅿️","Park here"],["📣","Honk here"]],h:"Drivers must slow down and stop."},
{e:"🧐",q:"What should we do when an ambulance sounds its siren behind us?",o:[["↔️","Move aside and let it pass"],["🛑","Stop right in front"],["💨","Race it"],["🙈","Ignore it"]],h:"Someone's life may depend on those seconds."},
{e:"🎓",q:"Why is honking too much a bad thing?",o:[["🔊","It is noise pollution and startles people"],["💰","It is expensive"],["🎨","It is ugly"],["🐌","It is slow"]],h:"Hospitals and schools have silent zones."},
{e:"📖",q:"What should we wear while cycling for safety?",o:[["🪖","A helmet"],["👑","A crown"],["🧣","A scarf over the eyes"],["🎧","Loud headphones"]],h:"And never wear headphones on the road."},
{e:"🚦",q:"Why should we not wear earphones while crossing a road?",o:[["👂","We cannot hear horns or engines"],["💰","They cost money"],["🔋","The battery dies"],["🎵","Music is bad"]],h:"Your ears warn you before your eyes do."},
{e:"🔍",q:"What is a speed breaker for?",o:[["🐌","To make vehicles slow down"],["💨","To make them faster"],["🅿️","For parking"],["🎨","For decoration"]],h:"Usually near schools and hospitals."},
{e:"🧐",q:"Which vehicle has the right to go first at a crossing?",o:[["🚑","An ambulance or fire engine"],["🚗","The biggest car"],["🛵","The fastest bike"],["🚌","The bus"]],h:"Emergency vehicles always go first."},
{e:"🎓",q:"What do we call the person walking on the road?",o:[["🚶","A pedestrian"],["🚗","A driver"],["👨‍✈️","A pilot"],["⚓","A sailor"]],h:"You are one every day."},
{e:"📖",q:"What should we check before getting off a bus?",o:[["🛑","That the bus has fully stopped"],["🎵","The music"],["🪟","The window"],["⌚","The time"]],h:"Never jump off a moving bus."},
{e:"🚦",q:"Which is safer to cross by: a foot overbridge or running across?",o:[["🌉","The foot overbridge"],["🏃","Running across"],["🚗","Between cars"],["🤸","Jumping the divider"]],h:"It takes longer but you stay safe."},
{e:"🔍",q:"What do we call the vehicle that carries many school children?",o:[["🚌","A school bus"],["🚑","An ambulance"],["🚒","A fire engine"],["🚚","A truck"]],h:"Bright yellow, with a helper inside."},
{e:"🧐",q:"What should we do if we miss our school bus?",o:[["🏫","Go back and tell a grown-up"],["🏃","Run after it"],["🚗","Ask a stranger for a lift"],["🚶","Walk alone far away"]],h:"Never accept a lift from someone you do not know."},
{e:"🎓",q:"Which vehicle runs on tracks in a city, above the road?",o:[["🚇","The metro"],["⛵","A boat"],["✈️","A plane"],["🐂","A bullock cart"]],h:"It glides over pillars above the traffic."},
{e:"📖",q:"Which fuel do most cars in India run on?",o:[["⛽","Petrol or diesel"],["💧","Water"],["🥛","Milk"],["🧃","Juice"]],h:"We fill it at a petrol pump."},
{e:"🚦",q:"Which vehicle is best for the environment?",o:[["🚲","A bicycle"],["🚚","A big truck"],["✈️","An aeroplane"],["🚗","A petrol car"]],h:"It makes no smoke at all, only healthy legs."},
{e:"🔍",q:"What do electric vehicles use instead of petrol?",o:[["🔋","A battery"],["💧","Water"],["🏖️","Sand"],["🌬️","Wind"]],h:"You plug them in to charge, like a phone."},
{e:"🧐",q:"Why is it safer to travel by train than by road?",o:[["🛤️","Trains have their own track with no crossing traffic"],["💨","They are faster"],["💰","They are cheaper"],["🎵","They are noisy"]],h:"Nothing else uses the railway line."},
{e:"🎓",q:"What is the yellow line on a railway platform for?",o:[["⚠️","Do not step past it"],["🎨","Decoration"],["🅿️","Parking"],["🏃","Running races"]],h:"Trains rush past very close to the edge."},
{e:"📖",q:"Which number is written on every Indian vehicle to identify it?",o:[["🔢","The number plate"],["📞","A phone number"],["🏠","A house number"],["🎂","A birthday"]],h:"White and black letters on front and back."}
]
};
