module.exports = {
"Body & Good Habits": [
{e:"🧒",q:"How many bones does a grown-up human have?",o:[["2️⃣0️⃣","206"],["🔟","10"],["5️⃣0️⃣","50"],["1️⃣0️⃣0️⃣","1000"]],h:"A bit more than two hundred."},
{e:"🔍",q:"Which is the smallest bone in our body?",o:[["👂","A bone inside the ear"],["🦵","A leg bone"],["✋","A finger bone"],["🦴","A back bone"]],h:"Tinier than a grain of rice!"},
{e:"🧐",q:"Which is the strongest muscle in our body for its size?",o:[["👅","The tongue"],["🦵","The leg"],["💪","The arm"],["👂","The ear"]],h:"It never gets tired of talking!"},
{e:"🎓",q:"What do we call the first set of teeth children get?",o:[["🦷","Milk teeth"],["💎","Gold teeth"],["🪨","Stone teeth"],["🔩","Iron teeth"]],h:"They fall out and new ones grow."},
{e:"📖",q:"What should we do if a milk tooth becomes loose?",o:[["👨‍👩‍👧","Tell a grown-up, do not force it"],["🔨","Pull it hard"],["🙈","Hide it"],["🍬","Eat more toffee"]],h:"It will come out on its own soon."},
{e:"🧒",q:"Which food is very bad for our teeth at bedtime?",o:[["🍫","Sweets and chocolates"],["🥛","Milk"],["🥕","Carrots"],["💧","Water"]],h:"Sugar sits on the teeth all night."},
{e:"🔍",q:"How long should we wash our hands with soap?",o:[["⏱️","About 20 seconds"],["⚡","One second"],["🕐","One hour"],["0️⃣","No time at all"]],h:"As long as singing Happy Birthday twice."},
{e:"🧐",q:"When should we especially wash our hands?",o:[["🍽️","Before eating and after the toilet"],["😴","Only before sleeping"],["📺","Only before TV"],["🎂","Only on birthdays"]],h:"Those are the two most important times."},
{e:"🎓",q:"Why should we not bite our nails?",o:[["🦠","Germs under them go into our mouth"],["🎨","It looks colourful"],["🔊","It is noisy"],["💰","It costs money"]],h:"Dirt hides in that little gap."},
{e:"📖",q:"What should we do if we get sweaty after playing?",o:[["🚿","Wash and change clothes"],["😴","Sleep in them"],["🍽️","Eat at once"],["🙈","Hide"]],h:"Sweat plus dust equals itchy skin."},
{e:"🧒",q:"Which part of the body helps us balance while walking?",o:[["👂","The inner ear"],["💇","The hair"],["💅","The nails"],["👅","The tongue"]],h:"Something deep inside the ear keeps us steady."},
{e:"🔍",q:"What happens to our heart when we run fast?",o:[["💓","It beats faster"],["🛑","It stops"],["🐌","It slows down"],["😴","It sleeps"]],h:"Put your hand on your chest after running."},
{e:"🧐",q:"Why do we breathe faster after exercise?",o:[["🫁","Our body needs more oxygen"],["🎵","To make music"],["🥵","To feel hot"],["🤷","No reason"]],h:"Working muscles use up air quickly."},
{e:"🎓",q:"Which drink is best right after playing in the sun?",o:[["💧","Water"],["🥤","Fizzy cold drink"],["☕","Hot coffee"],["🍦","Ice cream"]],h:"You lost water as sweat. Put it back."},
{e:"📖",q:"What should we put on before going out in strong sun?",o:[["🧢","A cap, and carry water"],["🧥","A thick woollen coat"],["🩱","A swimsuit"],["🧣","A muffler"]],h:"Shade your head and stay hydrated."},
{e:"🧒",q:"How many hours of sleep does a Class 1 child need?",o:[["😴","About 10 hours"],["⏱️","2 hours"],["🕐","1 hour"],["0️⃣","None"]],h:"Little children need much more sleep than grown-ups."},
{e:"🔍",q:"Why should we not look at screens just before bed?",o:[["😴","It makes it harder to fall asleep"],["🎨","It changes colours"],["💰","It costs money"],["🔊","It is loud"]],h:"Bright light tells the brain it is still daytime."},
{e:"🧐",q:"How should we sit while writing or reading?",o:[["🪑","Straight, with the book at a distance"],["🛏️","Lying flat on the tummy"],["🙃","Upside down"],["🏃","While running"]],h:"Slouching hurts your back and your eyes."},
{e:"🎓",q:"What should we do every 20 minutes of screen time?",o:[["👀","Look far away for a little while"],["🍬","Eat a sweet"],["🏃","Run outside"],["😴","Sleep"]],h:"It rests your eye muscles."},
{e:"📖",q:"Which of these is a good habit at the dining table?",o:[["🤐","Eating with our mouth closed"],["📣","Talking with a full mouth"],["🤾","Throwing food"],["🏃","Running around"]],h:"Quiet chewing is polite chewing."},
{e:"🧒",q:"What should we say before leaving the table?",o:[["🙏","May I get up, please"],["🤐","Nothing"],["📣","I am done, bye"],["🏃","Just run off"]],h:"Ask politely, and carry your plate."},
{e:"🔍",q:"What should we do with our shoes when we enter the house?",o:[["👟","Take them off and keep them in place"],["🛏️","Wear them to bed"],["🍽️","Put them on the table"],["🤾","Throw them"]],h:"Outside dirt stays outside."},
{e:"🧐",q:"Why should we open the windows in the morning?",o:[["🌬️","Fresh air and sunlight come in"],["🔊","To hear noise"],["🦟","To let insects in"],["🌧️","To let rain in"]],h:"Sunlight kills germs in the room."},
{e:"🎓",q:"What should we do with a hanky or tissue after sneezing?",o:[["🗑️","Bin the tissue, wash the hanky"],["🎒","Put it back in the bag"],["🤝","Give it to a friend"],["🍽️","Use it at the table"]],h:"It is full of germs now."},
{e:"📖",q:"What should we do if someone is coughing near us?",o:[["↔️","Move a little away politely"],["😆","Laugh"],["👉","Point at them"],["🤝","Hug them"]],h:"Be kind, but keep a safe distance."}
],

"Sports & Fun": [
{e:"🎽",q:"How many players are there on one side in a volleyball team?",o:[["6️⃣","Six"],["1️⃣1️⃣","Eleven"],["7️⃣","Seven"],["5️⃣","Five"]],h:"Three at the front, three at the back."},
{e:"🔍",q:"How many players are there in a basketball team on court?",o:[["5️⃣","Five"],["7️⃣","Seven"],["1️⃣1️⃣","Eleven"],["9️⃣","Nine"]],h:"Same as the fingers on one hand."},
{e:"🧐",q:"Which country did the game of cricket come from?",o:[["🇬🇧","England"],["🇮🇳","India"],["🗾","Japan"],["🇧🇷","Brazil"]],h:"It came to India long ago with the British."},
{e:"🎓",q:"Which game is thought to have started in India as chaturanga?",o:[["♟️","Chess"],["⚽","Football"],["🏊","Swimming"],["⛸️","Skating"]],h:"An ancient Indian game of four army divisions."},
{e:"📖",q:"Which Indian sport is the national game of Bangladesh too?",o:[["🤸","Kabaddi"],["🏏","Cricket"],["♟️","Chess"],["🎾","Tennis"]],h:"The chanting, breath-holding game."},
{e:"🎽",q:"In cricket, what do we call it when a batter scores 100 runs?",o:[["💯","A century"],["🦆","A duck"],["4️⃣","A four"],["6️⃣","A six"]],h:"Hundred years is also called this!"},
{e:"🔍",q:"In cricket, what do we call a batter out for zero runs?",o:[["🦆","A duck"],["💯","A century"],["👑","A king"],["🏆","A winner"]],h:"Named after a bird's egg shape: zero."},
{e:"🧐",q:"How many balls are there in one over in cricket?",o:[["6️⃣","Six"],["4️⃣","Four"],["8️⃣","Eight"],["🔟","Ten"]],h:"Then the bowler changes ends."},
{e:"🎓",q:"Which Indian woman won an Olympic medal in wrestling?",o:[["🤼","Sakshi Malik"],["🏸","P.V. Sindhu"],["🥊","Mary Kom"],["🏏","Mithali Raj"]],h:"She won bronze at Rio in 2016."},
{e:"📖",q:"Which sport does Mithali Raj play?",o:[["🏏","Cricket"],["🏸","Badminton"],["🥊","Boxing"],["♟️","Chess"]],h:"She captained the Indian women's team."},
{e:"🎽",q:"In which sport did India win many Olympic golds long ago?",o:[["🏑","Hockey"],["⚽","Football"],["🏊","Swimming"],["🎾","Tennis"]],h:"Eight gold medals, in Dhyan Chand's time."},
{e:"🔍",q:"What do we call the person who trains a sports team?",o:[["📋","A coach"],["👨‍⚖️","An umpire"],["📣","A fan"],["🎫","A conductor"]],h:"They plan the practice and give advice."},
{e:"🧐",q:"What do we call the people who come to watch a match?",o:[["👥","Spectators"],["📋","Coaches"],["👨‍⚖️","Umpires"],["🧢","Captains"]],h:"They fill the stands and cheer."},
{e:"🎓",q:"What should we do if we get hurt while playing?",o:[["🧑","Stop and tell a grown-up"],["🤐","Keep playing quietly"],["🙈","Hide it"],["😭","Blame a friend"]],h:"A small hurt can become a big one."},
{e:"📖",q:"What is the most important thing about playing a game?",o:[["🤝","Playing fairly and having fun"],["🏆","Winning at any cost"],["😠","Beating your friend"],["💰","Getting money"]],h:"Sportsmanship matters more than the score."},
{e:"🎽",q:"Which game do we play with a bat, a ball and a wall?",o:[["🎾","Squash"],["♟️","Chess"],["🎲","Ludo"],["🎯","Carrom"]],h:"You hit the ball against the wall."},
{e:"🔍",q:"In which game do we ride and hit a ball with a long stick?",o:[["🐎","Polo"],["🏊","Swimming"],["♟️","Chess"],["🎯","Carrom"]],h:"Played on horseback. It started in Manipur!"},
{e:"🧐",q:"Which state is the birthplace of modern polo?",o:[["🐎","Manipur"],["🏖️","Goa"],["🐪","Rajasthan"],["🥥","Kerala"]],h:"In the north-east of India."},
{e:"🎓",q:"Which martial art comes from Kerala?",o:[["🤺","Kalaripayattu"],["🥊","Boxing"],["♟️","Chess"],["🏏","Cricket"]],h:"One of the oldest fighting arts in the world."},
{e:"📖",q:"What do we call a game that ends with nobody winning?",o:[["🤝","A draw"],["🏆","A win"],["😢","A loss"],["🎉","A party"]],h:"Both teams finish equal."},
{e:"🎽",q:"Which Indian board game later became Snakes and Ladders?",o:[["🐍","Moksha Patam"],["♟️","Chess"],["🎯","Carrom"],["🎲","Dice"]],h:"An old game about good deeds and bad deeds."},
{e:"🔍",q:"Which toy do children spin with a string in Indian villages?",o:[["🌀","Lattu"],["🪁","Patang"],["⚽","Ball"],["🧸","Teddy"]],h:"It hums as it spins on the ground."},
{e:"🧐",q:"Which Indian cartoon has a boy called Bheem and a girl called Chutki?",o:[["🧡","Chhota Bheem"],["🐱","Doraemon"],["🍔","Motu Patlu"],["🐭","Mickey Mouse"]],h:"Set in the town of Dholakpur."},
{e:"🎓",q:"How many squares are there on a chess board?",o:[["6️⃣4️⃣","64"],["3️⃣2️⃣","32"],["1️⃣0️⃣0️⃣","100"],["1️⃣6️⃣","16"]],h:"Eight rows of eight."},
{e:"📖",q:"Which piece in chess can jump over other pieces?",o:[["🐎","The knight"],["👑","The king"],["🏰","The rook"],["👸","The queen"]],h:"It moves in an L shape, like a horse."}
]
};
