module.exports = {
"World Around Us": [
{e:"🌍",q:"Which country is famous for pandas?",o:[["🐼","China"],["🦘","Australia"],["🥖","France"],["🇮🇳","India"]],h:"Black and white bears that eat bamboo."},
{e:"🔍",q:"Which country is famous for pyramids?",o:[["🔺","Egypt"],["🗾","Japan"],["🦘","Australia"],["🐼","China"]],h:"Huge stone triangles in the desert."},
{e:"🧐",q:"Which country is shaped like a boot on the map?",o:[["🍕","Italy"],["🐼","China"],["🇮🇳","India"],["🦘","Australia"]],h:"Famous for pizza and pasta."},
{e:"🎓",q:"Which is the smallest country in the world?",o:[["⛪","Vatican City"],["🇮🇳","India"],["🐼","China"],["❄️","Russia"]],h:"So small it fits inside one city."},
{e:"📖",q:"Which sea animal is the largest in the world?",o:[["🐋","The blue whale"],["🦈","The shark"],["🐬","The dolphin"],["🐙","The octopus"]],h:"Bigger than any dinosaur ever was."},
{e:"🗺️",q:"Which is the highest waterfall in the world?",o:[["⛲","Angel Falls"],["🏞️","Ganga Falls"],["🌊","Sea Falls"],["❄️","Snow Falls"]],h:"In South America, in Venezuela."},
{e:"🌍",q:"What do we call a very large area of salt water, smaller than an ocean?",o:[["🌊","A sea"],["🏞️","A river"],["🪣","A pond"],["🕳️","A well"]],h:"Like the Arabian one beside Mumbai."},
{e:"🔍",q:"What do we call land with water all around it?",o:[["🏝️","An island"],["🏔️","A mountain"],["🏜️","A desert"],["🌾","A field"]],h:"Sri Lanka is one."},
{e:"🧐",q:"Which country's flag is a red circle on white?",o:[["🗾","Japan"],["🇮🇳","India"],["🐼","China"],["🥖","France"]],h:"The rising sun."},
{e:"🎓",q:"Which country has a maple leaf on its flag?",o:[["🍁","Canada"],["🇮🇳","India"],["🗾","Japan"],["🐼","China"]],h:"A cold country famous for maple syrup."},
{e:"📖",q:"What do we call a doctor who treats animals?",o:[["🐕","A vet"],["🩺","A dentist"],["👨‍🍳","A chef"],["👨‍✈️","A pilot"]],h:"Short for veterinarian."},
{e:"🗺️",q:"What do we call someone who travels to study new places?",o:[["🧭","An explorer"],["👨‍🍳","A cook"],["🚗","A driver"],["👮","A policeman"]],h:"They go where few have gone."},
{e:"🌍",q:"Which machine helped people first fly across the sky?",o:[["✈️","The aeroplane"],["🚂","The train"],["🚗","The car"],["⛵","The boat"]],h:"The Wright brothers built it."},
{e:"🔍",q:"Who invented the light bulb?",o:[["💡","Thomas Edison"],["🚀","Dr Kalam"],["🧓","Gandhi ji"],["✍️","Tagore"]],h:"He tried over a thousand times before it worked."},
{e:"🧐",q:"Who gave us the law of gravity after seeing an apple fall?",o:[["🍎","Isaac Newton"],["💡","Edison"],["🧓","Gandhi ji"],["🚀","Dr Kalam"]],h:"He asked why things fall down and not up."},
{e:"🎓",q:"Which Indian scientist won the Nobel Prize for the Raman Effect?",o:[["🔬","C.V. Raman"],["🚀","Dr Kalam"],["🧓","Gandhi ji"],["✍️","Tagore"]],h:"National Science Day is on his birthday."},
{e:"📖",q:"Which Indian was the first to win a Nobel Prize, for literature?",o:[["✍️","Rabindranath Tagore"],["🔬","C.V. Raman"],["🧓","Gandhi ji"],["🚀","Dr Kalam"]],h:"He wrote our national anthem."},
{e:"🗺️",q:"Who is known worldwide for helping the poor in Kolkata?",o:[["🕊️","Mother Teresa"],["⚔️","Rani Lakshmibai"],["🌹","Indira Gandhi"],["🏏","Sachin"]],h:"She won the Nobel Peace Prize."},
{e:"🌍",q:"What do we call the study of the Earth, its countries and its people?",o:[["🗺️","Geography"],["🔢","Mathematics"],["🎵","Music"],["🎨","Art"]],h:"Maps, mountains and rivers."},
{e:"🔍",q:"What do we call the study of things that happened long ago?",o:[["📜","History"],["🔢","Maths"],["🎵","Music"],["🔬","Science"]],h:"Kings, freedom fighters and old monuments."},
{e:"🧐",q:"Which two countries share the Himalayas with India?",o:[["🏔️","Nepal and Bhutan"],["🦘","Australia and Japan"],["🥖","France and Italy"],["🐧","Antarctica and Egypt"]],h:"Both are our small northern neighbours."},
{e:"🎓",q:"What do we call people who move from one country to live in another?",o:[["✈️","Immigrants"],["🩺","Doctors"],["👮","Police"],["🌾","Farmers"]],h:"Many Indians live abroad this way."},
{e:"📖",q:"Which day celebrates children all over the world on 20 November?",o:[["🧒","World Children's Day"],["🎂","Birthday"],["🪔","Diwali"],["🎄","Christmas"]],h:"Different from India's own on 14 November."}
],

"Stories & Rhymes": [
{e:"📚",q:"In the Panchatantra, which animal is usually the clever trickster?",o:[["🦊","The jackal"],["🐄","The cow"],["🐑","The sheep"],["🐔","The hen"]],h:"Sly and quick-witted."},
{e:"🔍",q:"In the story, how did the clever rabbit escape the lion?",o:[["🕳️","He tricked him into a well"],["🏃","He ran faster"],["🌳","He climbed a tree"],["🏊","He swam away"]],h:"The lion saw his own reflection and jumped in."},
{e:"🧐",q:"What do we call the people in a story?",o:[["👥","Characters"],["🎨","Colours"],["🔢","Numbers"],["📏","Rulers"]],h:"Rama, Sita and Hanuman are all these."},
{e:"🎓",q:"What do we call the place where a story happens?",o:[["🏞️","The setting"],["💡","The moral"],["📛","The title"],["✍️","The author"]],h:"A jungle, a village or a palace."},
{e:"📖",q:"What do we call the name written at the top of a story?",o:[["📛","The title"],["💡","The moral"],["🎨","The picture"],["🔚","The ending"]],h:"It tells you what the story is called."},
{e:"📚",q:"In the rhyme, what did Little Miss Muffet sit on?",o:[["🪑","A tuffet"],["🛏️","A bed"],["🌳","A tree"],["🪨","A rock"]],h:"Until a spider came along."},
{e:"🔍",q:"In the rhyme, what frightened Miss Muffet away?",o:[["🕷️","A spider"],["🐕","A dog"],["🐄","A cow"],["🐍","A snake"]],h:"It sat down beside her."},
{e:"🧐",q:"In the rhyme, what jumped over the moon?",o:[["🐄","The cow"],["🐕","The dog"],["🐈","The cat"],["🥄","The dish"]],h:"Hey diddle diddle!"},
{e:"🎓",q:"In the rhyme, who ran up the clock?",o:[["🐁","A mouse"],["🐈","A cat"],["🐕","A dog"],["🐦","A bird"]],h:"Hickory dickory dock."},
{e:"📖",q:"Which word RHYMES with STAR?",o:[["🚗","Car"],["🏠","House"],["🐕","Dog"],["🌳","Tree"]],h:"Ends with the same -ar sound."},
{e:"📚",q:"Which word RHYMES with SUN?",o:[["🏃","Run"],["🐈","Cat"],["📕","Book"],["🌳","Tree"]],h:"Ends with -un."},
{e:"🔍",q:"Which word RHYMES with BALL?",o:[["📏","Tall"],["🐕","Dog"],["🐈","Cat"],["☀️","Sun"]],h:"Ends with -all."},
{e:"🧐",q:"What do we call a poem sung to help a baby sleep?",o:[["😴","A lullaby"],["📰","A report"],["🧾","A bill"],["📜","A letter"]],h:"Soft and slow, at bedtime."},
{e:"🎓",q:"In Indian villages, who traditionally tells children stories at night?",o:[["👵","Grandparents"],["👮","Policemen"],["🩺","Doctors"],["🚗","Drivers"]],h:"Dadi and Nani."},
{e:"📖",q:"What do we call a very short funny story that makes us laugh?",o:[["😄","A joke"],["📰","News"],["🧾","A bill"],["🗺️","A map"]],h:"It has a punchline."},
{e:"📚",q:"In the Ramayana, how many years was Rama in exile?",o:[["1️⃣4️⃣","Fourteen"],["7️⃣","Seven"],["🔟","Ten"],["2️⃣","Two"]],h:"Diwali celebrates his return after them."},
{e:"🔍",q:"In the Mahabharata, who was the greatest archer among the Pandavas?",o:[["🏹","Arjuna"],["💪","Bhima"],["👑","Yudhishthira"],["🐒","Hanuman"]],h:"Krishna was his charioteer."},
{e:"🧐",q:"Which bird in Indian stories is said to separate milk from water?",o:[["🦢","The swan"],["🐦‍⬛","The crow"],["🦚","The peacock"],["🦜","The parrot"]],h:"A symbol of wisdom, and Saraswati's vehicle."},
{e:"🎓",q:"In the tale, what did the ant do all summer while the grasshopper sang?",o:[["🐜","Stored food for winter"],["😴","Slept"],["🎵","Sang too"],["🏃","Ran races"]],h:"Hard work now, comfort later."},
{e:"📖",q:"What lesson does the ant and grasshopper story teach?",o:[["💪","Work hard and plan ahead"],["😴","Sleep all day"],["🎵","Only sing"],["🍽️","Eat a lot"]],h:"The grasshopper had nothing when winter came."},
{e:"📚",q:"What do we call a book that has many stories in it?",o:[["📚","A collection"],["🧾","A bill"],["🗺️","A map"],["📰","A newspaper"]],h:"Panchatantra is one."},
{e:"🔍",q:"What should we do when someone is telling us a story?",o:[["👂","Listen quietly"],["📣","Talk loudly"],["🏃","Run about"],["😴","Sleep"]],h:"Good listeners enjoy stories most."},
{e:"🧐",q:"What do we call drawing a picture of what a story describes?",o:[["🎨","Illustrating"],["🔢","Counting"],["🎵","Singing"],["🏃","Running"]],h:"Storybook artists do this."},
{e:"🎓",q:"Which Indian cartoon character is known for eating laddoos and helping people?",o:[["🧡","Chhota Bheem"],["🐱","Doraemon"],["🐭","Mickey Mouse"],["🦸","Superman"]],h:"He lives in Dholakpur."},
{e:"📖",q:"What do we call the first page that shows a book's name and picture?",o:[["📕","The cover"],["🔚","The last page"],["💡","The moral"],["🎨","An illustration"]],h:"You see it before you open the book."},
{e:"📚",q:"Why is reading storybooks good for us?",o:[["🧠","It grows our words and imagination"],["😴","It makes us sleepy"],["💰","It makes us rich"],["📏","It makes us taller"]],h:"Every new story teaches new words."},
{e:"🔍",q:"What do we call a person in a story who does bad things?",o:[["😈","The villain"],["🦸","The hero"],["✍️","The author"],["📖","The reader"]],h:"Ravana and Kansa are examples."}
]
};
