/* Famous People, second helping: 15 more in each subsection, taking every
   one of them to 25. */
module.exports = {
"Famous People": [

/* ---------------- SPACE ---------------- */
{g:"Space",e:"🎓",q:"After which scientist is India's Sriharikota launch centre named?",o:[["🛰️","Satish Dhawan"],["🚀","Vikram Sarabhai"],["⚛️","Homi Bhabha"],["🔬","CV Raman"]],h:"He led ISRO after Sarabhai."},
{g:"Space",e:"📝",q:"Who was the FIRST American woman to go into space?",o:[["👩‍🚀","Sally Ride"],["👩","Valentina Tereshkova"],["👩‍🔬","Kalpana Chawla"],["👩‍✈️","Sunita Williams"]],h:"She flew on the shuttle Challenger in 1983."},
{g:"Space",e:"🔎",q:"Who was the FIRST American in space?",o:[["🚀","Alan Shepard"],["🌕","Neil Armstrong"],["👨‍🚀","Buzz Aldrin"],["🛰️","John Glenn"]],h:"He went up in 1961, soon after Gagarin."},
{g:"Space",e:"🎓",q:"Which woman scientist was called the Rocket Woman of India for her work on Mangalyaan?",o:[["👩‍🔬","Ritu Karidhal"],["👩‍🚀","Kalpana Chawla"],["👩","Sunita Williams"],["👩‍✈️","Tessy Thomas"]],h:"She was the deputy operations director of the Mars mission."},
{g:"Space",e:"📝",q:"Who was the Chairman of ISRO when Chandrayaan-3 landed on the Moon?",o:[["🛰️","S Somanath"],["🚀","K Sivan"],["⚛️","Homi Bhabha"],["🔭","Vikram Sarabhai"]],h:"He led ISRO from 2022."},
{g:"Space",e:"🧐",q:"Which Indian scientist is called the father of India's satellite programme?",o:[["🛰️","U R Rao"],["🚀","APJ Abdul Kalam"],["⚛️","Homi Bhabha"],["🔬","CV Raman"]],h:"He led the team that built Aryabhata."},
{g:"Space",e:"🤔",q:"After which ancient Indian mathematician was our first satellite named?",o:[["📐","Aryabhata"],["🔢","Ramanujan"],["🧮","Bhaskara"],["➗","Brahmagupta"]],h:"He wrote about the Earth spinning, long ago."},
{g:"Space",e:"🤔",q:"Which woman is known as the Missile Woman of India?",o:[["🚀","Tessy Thomas"],["👩‍🚀","Kalpana Chawla"],["👩‍🔬","Ritu Karidhal"],["👩","Sunita Williams"]],h:"She led the Agni missile project."},
{g:"Space",e:"💭",q:"Which astronaut did Rakesh Sharma answer when asked how India looked from space?",o:[["🎩","Indira Gandhi"],["🌹","Jawaharlal Nehru"],["🧓","Mahatma Gandhi"],["🛡️","Sardar Patel"]],h:"The Prime Minister at the time, a woman."},
{g:"Space",e:"💭",q:"Who founded the rocket company SpaceX?",o:[["🚀","Elon Musk"],["🛰️","Jeff Bezos"],["💻","Bill Gates"],["📱","Steve Jobs"]],h:"He also makes electric cars."},
{g:"Space",e:"📝",q:"Which Indian-origin astronaut sadly died when her shuttle broke up in 2003?",o:[["👩‍🚀","Kalpana Chawla"],["👩","Sunita Williams"],["👨‍🚀","Rakesh Sharma"],["👩‍🔬","Ritu Karidhal"]],h:"The shuttle was called Columbia."},
{g:"Space",e:"🎓",q:"Which Indian Air Force pilot flew to the Space Station in 2025?",o:[["👨‍🚀","Shubhanshu Shukla"],["🚀","Rakesh Sharma"],["🛰️","S Somanath"],["👩‍🚀","Sunita Williams"]],h:"The second Indian ever to go to space, forty-one years after the first."},
{g:"Space",e:"📝",q:"Which woman was the project director of the Chandrayaan-2 mission?",o:[["👩‍🔬","Muthayya Vanitha"],["👩‍🚀","Ritu Karidhal"],["👩","Tessy Thomas"],["👩‍✈️","Kalpana Chawla"]],h:"The first woman to lead an Indian Moon mission."},
{g:"Space",e:"🔎",q:"Who was the project director of Chandrayaan-3, which landed on the Moon?",o:[["🛬","P Veeramuthuvel"],["🚀","K Sivan"],["🛰️","S Somanath"],["👩‍🔬","Ritu Karidhal"]],h:"He led the mission that finally landed softly."},
{g:"Space",e:"🧐",q:"Which Indian rocket scientist developed the Vikas engine used by ISRO?",o:[["🚀","Nambi Narayanan"],["🛰️","U R Rao"],["⚛️","Homi Bhabha"],["🔬","Satish Dhawan"]],h:"A film was made about his life."},

/* ---------------- CRICKET ---------------- */
{g:"Cricket",e:"🎓",q:"Which Indian woman captained the team to the T20 World Cup final?",o:[["🧤","Harmanpreet Kaur"],["🏏","Mithali Raj"],["🎯","Jhulan Goswami"],["⭐","Smriti Mandhana"]],h:"She hit a famous 171 not out against Australia."},
{g:"Cricket",e:"📝",q:"Which Indian woman opener is famous for her elegant left-handed batting?",o:[["⭐","Smriti Mandhana"],["🏏","Mithali Raj"],["🎯","Jhulan Goswami"],["🧤","Harmanpreet Kaur"]],h:"She bats left-handed and is from Sangli."},
{g:"Cricket",e:"🔎",q:"Which captain led India to the very first T20 World Cup win in 2007?",o:[["🧤","MS Dhoni"],["🏏","Rahul Dravid"],["🧢","Sourav Ganguly"],["👑","Virat Kohli"]],h:"He was the young new captain that year."},
{g:"Cricket",e:"🧐",q:"Which Indian spinner is famous for bowling with a big turning ball?",o:[["🌀","Anil Kumble"],["🏏","Kapil Dev"],["🧤","MS Dhoni"],["🧢","Zaheer Khan"]],h:"He once took all ten wickets in one innings."},
{g:"Cricket",e:"💭",q:"Which Indian captain has won the most Test matches for India?",o:[["👑","Virat Kohli"],["🧤","MS Dhoni"],["🧢","Sourav Ganguly"],["🏏","Sunil Gavaskar"]],h:"He captained India through their best years in Tests."},
{g:"Cricket",e:"🎓",q:"Which Indian cricketer is nicknamed Captain Cool?",o:[["🧤","MS Dhoni"],["👑","Virat Kohli"],["🏏","Rohit Sharma"],["🧢","Sourav Ganguly"]],h:"He never looked worried, however close the match."},
{g:"Cricket",e:"🎓",q:"Which Indian batsman was famous for hitting the very first ball for four?",o:[["💥","Virender Sehwag"],["🧱","Rahul Dravid"],["🏏","Sunil Gavaskar"],["🧤","MS Dhoni"]],h:"They called him the Nawab of Najafgarh."},
{g:"Cricket",e:"📝",q:"Which Indian captain was known as Dada and made the team fearless abroad?",o:[["🧢","Sourav Ganguly"],["🧤","MS Dhoni"],["🏏","Sachin Tendulkar"],["👑","Virat Kohli"]],h:"Dada means elder brother in Bengali."},
{g:"Cricket",e:"📝",q:"Which former Indian batsman coached India to the T20 World Cup win in 2024?",o:[["🧱","Rahul Dravid"],["🧤","MS Dhoni"],["🧢","Sourav Ganguly"],["🏏","Sachin Tendulkar"]],h:"As a player they called him The Wall."},
{g:"Cricket",e:"🔎",q:"Which Indian off-spinner was famous for a delivery called the doosra?",o:[["🎯","Harbhajan Singh"],["🌀","Anil Kumble"],["🏏","Ravichandran Ashwin"],["⚡","Zaheer Khan"]],h:"Doosra means the second one."},
{g:"Cricket",e:"🤔",q:"Which Indian bowler took the most wickets for India in Test cricket?",o:[["🌀","Anil Kumble"],["🏏","Kapil Dev"],["⚡","Zaheer Khan"],["🎯","Harbhajan Singh"]],h:"A leg-spinner who wore glasses."},
{g:"Cricket",e:"🧐",q:"Which Indian fast bowler took a hat-trick at the 2019 World Cup?",o:[["⚡","Mohammed Shami"],["🎯","Jasprit Bumrah"],["🌀","Anil Kumble"],["🏏","Kapil Dev"]],h:"Three wickets in three balls, against Afghanistan."},
{g:"Cricket",e:"🎓",q:"Which Indian all-rounder both batted well and bowled fast in the 1983 win?",o:[["🏆","Kapil Dev"],["🏏","Sunil Gavaskar"],["🧤","Syed Kirmani"],["🧢","Mohinder Amarnath"]],h:"He was also the captain that year."},
{g:"Cricket",e:"🤔",q:"Which Indian holds the highest individual score in a one-day innings?",o:[["🏏","Rohit Sharma"],["👑","Virat Kohli"],["💥","Virender Sehwag"],["🧤","Sachin Tendulkar"]],h:"He made 264, which nobody has beaten."},
{g:"Cricket",e:"💭",q:"Which Indian woman was the first cricketer to play 200 one-day matches?",o:[["🏏","Mithali Raj"],["🎯","Jhulan Goswami"],["🧤","Harmanpreet Kaur"],["⭐","Smriti Mandhana"]],h:"She captained India for many years."},

/* ---------------- SPORTS ---------------- */
{g:"Sports",e:"🧐",q:"Which sport does Neeraj Chopra play?",o:[["🎯","Javelin throw"],["🏸","Badminton"],["🥊","Boxing"],["🏹","Archery"]],h:"He throws a long light spear as far as he can."},
{g:"Sports",e:"🎓",q:"Which Indian woman weightlifter won an Olympic silver medal in 2021?",o:[["🏋️","Mirabai Chanu"],["🥊","Mary Kom"],["🏸","PV Sindhu"],["🤼","Vinesh Phogat"]],h:"She is from Manipur, and lifts more than twice her own weight."},
{g:"Sports",e:"💭",q:"Which Indian badminton player won the All England championship in 1980?",o:[["🏸","Prakash Padukone"],["🎾","Sania Mirza"],["🏑","Dhyan Chand"],["♟️","Viswanathan Anand"]],h:"His daughter is a famous film actor."},
{g:"Sports",e:"🎓",q:"Which Indian wrestler won two Olympic medals?",o:[["🤼","Sushil Kumar"],["🥊","Vijender Singh"],["🎯","Abhinav Bindra"],["🏸","Saina Nehwal"]],h:"He wrestles on a mat, not in a ring."},
{g:"Sports",e:"📝",q:"Which Indian wrestler won a bronze medal at the Tokyo Olympics?",o:[["🤼","Bajrang Punia"],["🥊","Vijender Singh"],["🏋️","Mirabai Chanu"],["🎯","Neeraj Chopra"]],h:"He wrestles in the 65 kilogram class."},
{g:"Sports",e:"🔎",q:"Which Indian sprinter from Assam won a world under-20 gold?",o:[["🏃","Hima Das"],["🏅","PT Usha"],["🥊","Mary Kom"],["🏸","Saina Nehwal"]],h:"People call her the Dhing Express."},
{g:"Sports",e:"🧐",q:"Which Indian badminton player won an Olympic bronze in 2012?",o:[["🏸","Saina Nehwal"],["🎾","Sania Mirza"],["🥊","Mary Kom"],["🏃","PT Usha"]],h:"She was the first Indian woman to win an Olympic badminton medal."},
{g:"Sports",e:"🔎",q:"Which Indian boxer won a bronze medal at the 2008 Olympics?",o:[["🥊","Vijender Singh"],["🤼","Sushil Kumar"],["🎯","Abhinav Bindra"],["🏸","Saina Nehwal"]],h:"India's first Olympic medal in boxing."},
{g:"Sports",e:"💭",q:"Which Indian footballer captained the national team for many years?",o:[["⚽","Sunil Chhetri"],["🏑","Dhyan Chand"],["🏏","Virat Kohli"],["🏸","Lakshya Sen"]],h:"He has scored more international goals than almost anyone alive."},
{g:"Sports",e:"🧐",q:"Which Indian shooter won two bronze medals at the 2024 Paris Olympics?",o:[["🎯","Manu Bhaker"],["🏹","Deepika Kumari"],["🏸","PV Sindhu"],["🏋️","Mirabai Chanu"]],h:"The first Indian to win two medals at a single Olympics."},
{g:"Sports",e:"📝",q:"Which Indian para-athlete won gold in javelin at the Paralympics?",o:[["🥇","Sumit Antil"],["🎯","Neeraj Chopra"],["🏸","Saina Nehwal"],["🥊","Mary Kom"]],h:"He throws javelin from a standing start with a prosthetic leg."},
{g:"Sports",e:"🔎",q:"Which Indian shuttler won gold at the World Championships in 2019?",o:[["🏸","PV Sindhu"],["🎾","Sania Mirza"],["🏃","Hima Das"],["🥊","Mary Kom"]],h:"She already had an Olympic silver by then."},
{g:"Sports",e:"🤔",q:"Which young Indian became World Chess Champion in 2024?",o:[["♟️","D Gukesh"],["🧠","Viswanathan Anand"],["♞","R Praggnanandhaa"],["🎯","Arjun Erigaisi"]],h:"The youngest ever to win the title, at just eighteen."},
{g:"Sports",e:"💭",q:"Which Indian captained the hockey team to an Olympic bronze in 2021?",o:[["🏑","Manpreet Singh"],["🏏","Virat Kohli"],["⚽","Sunil Chhetri"],["🏸","Lakshya Sen"]],h:"India's first hockey medal in forty-one years."},
{g:"Sports",e:"💭",q:"Which Indian city hosted the Commonwealth Games in 2010?",o:[["🕌","New Delhi"],["🏙️","Mumbai"],["🌉","Kolkata"],["🌴","Chennai"]],h:"Our capital city."},

/* ---------------- FREEDOM ---------------- */
{g:"Freedom",e:"🎓",q:"Which leader gave the slogan Jai Jawan Jai Kisan?",o:[["🌾","Lal Bahadur Shastri"],["🌹","Jawaharlal Nehru"],["🧓","Mahatma Gandhi"],["🛡️","Sardar Patel"]],h:"India's second Prime Minister, a very small and very honest man."},
{g:"Freedom",e:"📝",q:"Which Englishwoman became President of the Indian National Congress and fought for Home Rule?",o:[["🕊️","Annie Besant"],["👑","Rani Lakshmibai"],["🎤","Sarojini Naidu"],["📘","Kamala Nehru"]],h:"She started the Home Rule League with Tilak."},
{g:"Freedom",e:"🔎",q:"Whose birthday do we celebrate as Gandhi Jayanti?",o:[["🧓","Mahatma Gandhi"],["🌹","Jawaharlal Nehru"],["🛡️","Sardar Patel"],["📘","Dr Ambedkar"]],h:"The second of October."},
{g:"Freedom",e:"🧐",q:"What was Mahatma Gandhi's full name?",o:[["🧓","Mohandas Karamchand Gandhi"],["👤","Mohan Kumar Gandhi"],["👤","Mahesh Chandra Gandhi"],["👤","Madan Krishna Gandhi"]],h:"His first name was Mohandas."},
{g:"Freedom",e:"🔎",q:"Which woman doctor led the Rani Jhansi Regiment in Subhas Bose's army?",o:[["🩺","Lakshmi Sahgal"],["🎤","Sarojini Naidu"],["👑","Rani Lakshmibai"],["🕊️","Annie Besant"]],h:"A doctor who became a captain in the INA."},
{g:"Freedom",e:"🧐",q:"Which freedom fighter from the north-west was called the Frontier Gandhi?",o:[["🕊️","Khan Abdul Ghaffar Khan"],["⚔️","Bhagat Singh"],["🎖️","Subhas Chandra Bose"],["📢","Bal Gangadhar Tilak"]],h:"A Pathan leader who believed in non-violence."},
{g:"Freedom",e:"❓",q:"Who was the first President of India?",o:[["📘","Dr Rajendra Prasad"],["🌹","Jawaharlal Nehru"],["🎓","S Radhakrishnan"],["🚀","APJ Abdul Kalam"]],h:"He led the meetings that wrote the Constitution."},
{g:"Freedom",e:"📝",q:"Whose birthday do we celebrate as Teachers' Day?",o:[["🎓","Dr S Radhakrishnan"],["🌹","Jawaharlal Nehru"],["🧓","Mahatma Gandhi"],["📘","Dr Ambedkar"]],h:"He was a teacher before he became President."},
{g:"Freedom",e:"🔎",q:"Which slogan did Gandhi give in 1942 asking the British to leave?",o:[["📢","Quit India"],["⚔️","Do or Die only"],["🇮🇳","Jai Hind"],["🕊️","Vande Mataram"]],h:"Two words, telling them to go."},
{g:"Freedom",e:"🧐",q:"Who wrote the song Vande Mataram?",o:[["📜","Bankim Chandra Chatterjee"],["✍️","Rabindranath Tagore"],["🖋️","Sarojini Naidu"],["📖","Munshi Premchand"]],h:"It comes from his novel Anandamath."},
{g:"Freedom",e:"🤔",q:"Which freedom fighter was called Punjab Kesari, the Lion of Punjab?",o:[["🦁","Lala Lajpat Rai"],["📢","Bal Gangadhar Tilak"],["⚔️","Bhagat Singh"],["🛡️","Sardar Patel"]],h:"He was one of the trio Lal, Bal and Pal."},
{g:"Freedom",e:"🤔",q:"Which revolutionary threw a bomb in the Assembly along with Bhagat Singh?",o:[["💣","Batukeshwar Dutt"],["⚔️","Chandrashekhar Azad"],["🎖️","Rajguru"],["🔫","Sukhdev"]],h:"They shouted Inquilab Zindabad and did not run away."},
{g:"Freedom",e:"🎓",q:"Which young woman fought the British alongside Rani Lakshmibai?",o:[["🗡️","Jhalkaribai"],["👑","Razia Sultan"],["🏹","Ahilyabai Holkar"],["⚔️","Chand Bibi"]],h:"She looked so like the queen that she took her place in battle."},
{g:"Freedom",e:"📝",q:"Which garden saw a terrible massacre in Amritsar in 1919?",o:[["🌳","Jallianwala Bagh"],["🏛️","Shalimar Bagh"],["🌺","Mughal Gardens"],["🌿","Lodhi Gardens"]],h:"There is a memorial there with bullet marks on the walls."},
{g:"Freedom",e:"💭",q:"Which old woman was shot in Bengal while holding the tricolour and never let it fall?",o:[["🇮🇳","Matangini Hazra"],["👑","Rani Lakshmibai"],["🎤","Sarojini Naidu"],["🩺","Lakshmi Sahgal"]],h:"People called her Gandhi Buri, the old Gandhi lady."},

/* ---------------- SCIENCE ---------------- */
{g:"Science",e:"🧐",q:"Which Indian-American scientist won a Nobel Prize for work on genes?",o:[["🧬","Har Gobind Khorana"],["🔬","CV Raman"],["⚛️","Homi Bhabha"],["🌱","JC Bose"]],h:"He helped work out the genetic code."},
{g:"Science",e:"🤔",q:"Which Indian astrophysicist won a Nobel Prize for work on stars?",o:[["⭐","Subrahmanyan Chandrasekhar"],["🔬","CV Raman"],["🧬","Har Gobind Khorana"],["⚛️","Homi Bhabha"]],h:"A limit for dying stars carries his name."},
{g:"Science",e:"💭",q:"Which Indian scientist led the Green Revolution that grew more food?",o:[["🌾","MS Swaminathan"],["🥛","Verghese Kurien"],["🔬","CV Raman"],["🌱","JC Bose"]],h:"He bred wheat that gave far bigger harvests."},
{g:"Science",e:"🎓",q:"Who led India's White Revolution and made it rich in milk?",o:[["🥛","Verghese Kurien"],["🌾","MS Swaminathan"],["⚛️","Homi Bhabha"],["🛰️","Vikram Sarabhai"]],h:"He founded Amul in Gujarat."},
{g:"Science",e:"📝",q:"Which Indian doctor is Doctors' Day named after?",o:[["🩺","Dr B C Roy"],["💉","Dr Salim Ali"],["🔬","Dr CV Raman"],["🧬","Dr Khorana"]],h:"He was also Chief Minister of West Bengal."},
{g:"Science",e:"🔎",q:"Which Indian scientist was famous for studying birds?",o:[["🐦","Salim Ali"],["🌱","JC Bose"],["🔬","CV Raman"],["🌾","MS Swaminathan"]],h:"People call him the Birdman of India."},
{g:"Science",e:"🧐",q:"Who discovered that the Earth goes round the Sun, not the other way?",o:[["☀️","Copernicus"],["🍎","Newton"],["⚛️","Einstein"],["💡","Edison"]],h:"He put the Sun at the centre, long ago in Poland."},
{g:"Science",e:"🤔",q:"Which scientist discovered penicillin by accident?",o:[["🧫","Alexander Fleming"],["💉","Louis Pasteur"],["🔬","Robert Koch"],["🧬","Gregor Mendel"]],h:"A mould grew on a dish he had left out."},
{g:"Science",e:"💭",q:"Which woman scientist won two Nobel Prizes for her work on radioactivity?",o:[["⚛️","Marie Curie"],["🧬","Rosalind Franklin"],["🔬","Ada Lovelace"],["🌱","Jane Goodall"]],h:"She discovered radium and polonium."},
{g:"Science",e:"🎓",q:"Which scientist explained how animals change slowly over a very long time?",o:[["🐢","Charles Darwin"],["🍎","Isaac Newton"],["⚛️","Albert Einstein"],["🔭","Galileo"]],h:"He sailed on a ship called the Beagle."},
{g:"Science",e:"📝",q:"Who is often called the father of the computer for designing the first one?",o:[["🖩","Charles Babbage"],["💡","Thomas Edison"],["📞","Graham Bell"],["⚛️","Einstein"]],h:"He designed an Analytical Engine made of gears."},
{g:"Science",e:"🔎",q:"Which Indian mathematician wrote the ancient book Aryabhatiya?",o:[["📐","Aryabhata"],["🔢","Ramanujan"],["🧮","Bhaskara"],["➗","Brahmagupta"]],h:"The book carries his own name."},
{g:"Science",e:"🧐",q:"Which scientist invented the radio?",o:[["📻","Guglielmo Marconi"],["💡","Thomas Edison"],["📞","Graham Bell"],["🍎","Isaac Newton"]],h:"An Italian, and he sent signals without any wires."},
{g:"Science",e:"🤔",q:"Which two brothers built and flew the first aeroplane?",o:[["✈️","The Wright brothers"],["🚂","The Stephenson brothers"],["🚗","The Ford brothers"],["🚲","The Michaux brothers"]],h:"Orville and Wilbur, in America."},
{g:"Science",e:"💭",q:"On whose birthday do we celebrate National Science Day in India?",o:[["🔬","CV Raman's discovery"],["⚛️","Homi Bhabha"],["🌱","JC Bose"],["🚀","APJ Abdul Kalam"]],h:"It marks the day he announced his effect, on 28 February."},

/* ---------------- ARTS ---------------- */
{g:"Arts",e:"🎓",q:"Which Indian sitar player's daughter is also a famous musician?",o:[["🎸","Ravi Shankar"],["🪈","Bismillah Khan"],["🥁","Zakir Hussain"],["🎻","Amjad Ali Khan"]],h:"Anoushka carries on his music."},
{g:"Arts",e:"📝",q:"Which classical dance comes from Tamil Nadu?",o:[["💃","Bharatanatyam"],["🎭","Kathakali"],["🪘","Kathak"],["🕺","Manipuri"]],h:"The oldest of them all, danced in temples."},
{g:"Arts",e:"📝",q:"Which Indian playback singer sang thousands of songs and is loved for Baharon Phool Barsao?",o:[["🎶","Mohammed Rafi"],["🎤","Kishore Kumar"],["🎵","Mukesh"],["🎼","Hemant Kumar"]],h:"He could sing in almost any voice asked of him."},
{g:"Arts",e:"🧐",q:"Which Indian painter is famous for beautiful paintings of gods and queens?",o:[["🖌️","Raja Ravi Varma"],["🎨","MF Husain"],["🖼️","Amrita Sher-Gil"],["✏️","Jamini Roy"]],h:"He was from Kerala, and a prince."},
{g:"Arts",e:"🔎",q:"Which Carnatic singer was the first musician to receive the Bharat Ratna?",o:[["🎵","MS Subbulakshmi"],["🎶","Lata Mangeshkar"],["🎤","Asha Bhosle"],["🎼","Bhimsen Joshi"]],h:"She sang at the United Nations in 1966."},
{g:"Arts",e:"🧐",q:"Which dancer was the great master of Kathak in our time?",o:[["🪘","Birju Maharaj"],["💃","Rukmini Devi Arundale"],["🎭","Kelucharan Mohapatra"],["🕺","Uday Shankar"]],h:"He taught Kathak for films as well as the stage."},
{g:"Arts",e:"🎓",q:"Which Indian flute player is world famous?",o:[["🪈","Hariprasad Chaurasia"],["🎸","Ravi Shankar"],["🥁","Zakir Hussain"],["🎻","Amjad Ali Khan"]],h:"He plays the bansuri, Krishna's instrument."},
{g:"Arts",e:"📝",q:"Which Indian singer sang for films alongside her sister Lata?",o:[["🎤","Asha Bhosle"],["🎶","Shreya Ghoshal"],["🎵","Geeta Dutt"],["🎼","Alka Yagnik"]],h:"Two sisters, both legends of playback singing."},
{g:"Arts",e:"🔎",q:"Which Indian music director won two Oscars for Slumdog Millionaire?",o:[["🎬","AR Rahman"],["🎸","Ravi Shankar"],["🥁","Zakir Hussain"],["🎤","Asha Bhosle"]],h:"From Chennai, and he wrote Jai Ho."},
{g:"Arts",e:"🤔",q:"Which dancer brought Bharatanatyam back to the stage and founded Kalakshetra?",o:[["💃","Rukmini Devi Arundale"],["🪘","Birju Maharaj"],["🎭","Kelucharan Mohapatra"],["🕺","Uday Shankar"]],h:"She started a famous dance school in Chennai."},
{g:"Arts",e:"🤔",q:"Which Indian writer wrote stories about the town of Malgudi?",o:[["📜","RK Narayan"],["📖","Munshi Premchand"],["✍️","Rabindranath Tagore"],["🖋️","Ruskin Bond"]],h:"Malgudi Days was made into a television show."},
{g:"Arts",e:"💭",q:"Which writer living in Mussoorie is loved for children's stories about the hills?",o:[["🖋️","Ruskin Bond"],["📜","RK Narayan"],["📖","Munshi Premchand"],["✍️","Rabindranath Tagore"]],h:"He wrote The Blue Umbrella."},
{g:"Arts",e:"🎓",q:"Which Indian woman painter is famous for paintings of village women?",o:[["🖼️","Amrita Sher-Gil"],["🎨","MF Husain"],["🖌️","Raja Ravi Varma"],["✏️","Jamini Roy"]],h:"She died very young, but her paintings are treasures."},
{g:"Arts",e:"💭",q:"Which artist decorated the original handwritten copy of our Constitution?",o:[["✏️","Nandalal Bose"],["🎨","MF Husain"],["🖌️","Raja Ravi Varma"],["🖼️","Amrita Sher-Gil"]],h:"He painted the borders of every page."},
{g:"Arts",e:"🎓",q:"Which Indian classical singer was famous for Hindustani khayal and the song Mile Sur Mera Tumhara?",o:[["🎼","Bhimsen Joshi"],["🎵","MS Subbulakshmi"],["🎶","Lata Mangeshkar"],["🎤","Kishore Kumar"]],h:"A great voice of the Kirana gharana."}
]
};
