module.exports = {
"Life Skills": [
{e:"💭",q:"Your friend keeps telling lies. What should you do?",o:[["🗣️","Tell them kindly that truth is better"],["🤥","Lie with them"],["📣","Shout at them"],["😆","Laugh"]],h:"A real friend helps you do the right thing."},
{e:"🔍",q:"You see someone being unkind to a smaller child. What should you do?",o:[["🧑","Tell a grown-up at once"],["😆","Laugh"],["🚶","Walk away"],["👊","Hit them back"]],h:"Grown-ups can stop it safely."},
{e:"🧐",q:"You broke your friend's toy by mistake. What should you do?",o:[["😔","Say sorry and offer to fix it"],["🙈","Hide it"],["🤥","Say it was already broken"],["🏃","Run away"]],h:"Honesty first, then help put it right."},
{e:"🤷",q:"You are the last to leave a room. What should you do?",o:[["💡","Switch off the light and fan"],["🔊","Turn the TV up"],["🚪","Leave everything on"],["🪟","Open the fridge"]],h:"Saving power saves money and the planet."},
{e:"💡",q:"You get a seat but an aunty is holding a baby. What should you do?",o:[["🪑","Offer her your seat"],["😴","Pretend to sleep"],["📱","Look at a phone"],["👀","Look away"]],h:"Her hands are full and yours are not."},
{e:"🎓",q:"Someone compliments your drawing. What should you say?",o:[["😊","Thank you"],["🤷","It is nothing"],["😠","No it is not"],["🤐","Nothing at all"]],h:"Accept kind words gracefully."},
{e:"📝",q:"You do not like the food served at a friend's house. What should you do?",o:[["🙏","Eat a little politely, or say no thank you"],["🤢","Say it is horrible"],["🗑️","Throw it away"],["😠","Get angry"]],h:"Someone worked hard to cook it."},
{e:"💭",q:"You are at a wedding and feel bored. What should you do?",o:[["🧑","Tell your parents quietly"],["📣","Shout that it is boring"],["🏃","Run around the hall"],["😭","Cry loudly"]],h:"Use words, not noise."},
{e:"🔍",q:"You find a lost puppy on the street. What should you do?",o:[["🧑","Tell a grown-up, do not pick it up"],["🏠","Take it home secretly"],["🏃","Chase it"],["🪨","Throw stones"]],h:"A frightened animal may bite, even a small one."},
{e:"🧐",q:"Someone asks you to keep a secret that makes you feel uncomfortable. What should you do?",o:[["👨‍👩‍👧","Tell your parents anyway"],["🤐","Keep it forever"],["📣","Tell all your friends"],["🙈","Forget it"]],h:"Some secrets are not safe to keep. Always tell family."},
{e:"🤷",q:"A grown-up you do not know offers you a ride home. What should you do?",o:[["🚫","Say no and go to a teacher or parent"],["🚗","Get in"],["🙏","Say thank you and get in"],["🤝","Shake hands first"]],h:"Only go with people your parents named."},
{e:"💡",q:"You want a toy that your parents cannot afford. What should you do?",o:[["🙂","Understand, and wait for a special day"],["😭","Cry in the shop"],["😠","Get angry"],["🤾","Throw a tantrum"]],h:"Money is limited in every family."},
{e:"🎓",q:"You finish your work early in class. What should you do?",o:[["📚","Read quietly or help a friend"],["📣","Shout that you are done"],["🏃","Run around"],["😴","Sleep on the desk"]],h:"Stay quiet so others can finish too."},
{e:"📝",q:"You see a friend struggling with a sum. What should you do?",o:[["🤝","Help them understand it"],["📋","Give them the answer only"],["😆","Laugh at them"],["🏃","Walk away"]],h:"Teaching them is better than telling them."},
{e:"💭",q:"You lose in a game your friend wins. What is the kind thing to do?",o:[["👏","Congratulate them"],["😠","Say the game was unfair"],["😭","Cry"],["🚫","Never play again"]],h:"There is always another game tomorrow."},
{e:"🔍",q:"A classmate has a different religion from yours. How should you treat them?",o:[["🤝","Exactly the same as everyone else"],["🚫","Avoid them"],["😆","Tease them"],["👉","Point at them"]],h:"India's beauty is that we all live together."},
{e:"🧐",q:"A classmate cannot walk and uses a wheelchair. What should you do?",o:[["🤝","Include them and ask if they want help"],["👀","Stare at them"],["🚫","Leave them out"],["😆","Laugh"]],h:"Ask first; do not just push their chair."},
{e:"🤷",q:"You spilled colours on the classroom floor. What should you do?",o:[["🧽","Clean it up yourself"],["👉","Blame someone else"],["🏃","Run away"],["🙈","Cover it with a bag"]],h:"Own your mess."},
{e:"💡",q:"You want to watch TV but your sister is studying. What should you do?",o:[["🔉","Watch quietly or wait"],["🔊","Turn it up loud"],["📣","Argue"],["🚪","Slam the door"]],h:"Share the space kindly."},
{e:"🎓",q:"You feel very angry. What is a good thing to do first?",o:[["🫁","Take deep breaths and count to ten"],["👊","Hit something"],["📣","Scream"],["🤾","Throw things"]],h:"Calm the body, then use words."},
{e:"📝",q:"What should you do if you see a tap or light left on in school?",o:[["🔌","Switch it off"],["🚶","Walk past"],["📣","Tell nobody"],["💦","Play with the water"]],h:"School resources belong to everyone."},
{e:"💭",q:"What should you do before crossing to help someone?",o:[["👀","Make sure you are safe yourself first"],["🏃","Run into the road"],["🙈","Close your eyes"],["📣","Shout"]],h:"You cannot help anyone if you get hurt too."},
{e:"🔍",q:"Your friend shares their lunch with you. What should you do next time?",o:[["🤝","Share yours with them"],["🙈","Forget about it"],["🍽️","Eat theirs again"],["😆","Laugh"]],h:"Kindness goes both ways."},
{e:"🧐",q:"You are given pocket money. What is a wise thing to do with some of it?",o:[["🐷","Save a little in a piggy bank"],["🍬","Spend it all on sweets"],["🗑️","Throw it"],["🙈","Hide it and forget"]],h:"Saving a little each time adds up fast."},
{e:"🤷",q:"What makes a person truly great?",o:[["❤️","Being kind and honest"],["💰","Having lots of money"],["📏","Being tall"],["🏆","Winning always"]],h:"Gandhi ji owned almost nothing."}
],

"Maths": [
{e:"🔢",q:"What is the EXPANDED form of 16?",o:[["➕","10 + 6"],["➕","10 + 5"],["➕","1 + 6"],["➕","1 + 5"]],h:"One ten and six ones."},
{e:"🧮",q:"What is the expanded form of 25?",o:[["➕","20 + 5"],["➕","2 + 5"],["➕","10 + 5"],["➕","25 + 0"]],h:"Two tens and five ones."},
{e:"🤔",q:"Which number has 3 tens and 4 ones?",o:[["3️⃣4️⃣","34"],["4️⃣3️⃣","43"],["3️⃣","3"],["7️⃣","7"]],h:"Tens go first, ones go second."},
{e:"📝",q:"Which number comes just after 99?",o:[["💯","100"],["9️⃣8️⃣","98"],["9️⃣","9"],["1️⃣0️⃣","10"]],h:"The first three-digit number!"},
{e:"🧐",q:"What is 20 + 15?",o:[["3️⃣5️⃣","35"],["2️⃣5️⃣","25"],["4️⃣5️⃣","45"],["3️⃣0️⃣","30"]],h:"Add the tens, then the ones."},
{e:"💭",q:"What is 30 - 10?",o:[["2️⃣0️⃣","20"],["4️⃣0️⃣","40"],["1️⃣0️⃣","10"],["3️⃣0️⃣","30"]],h:"Take one whole ten away."},
{e:"🎓",q:"Aarohi has 6 balloons. She gives 3 away. How many are left?",o:[["3️⃣","3"],["2️⃣","2"],["4️⃣","4"],["9️⃣","9"]],h:"Half of six."},
{e:"🔢",q:"Ankita buys 2 pens for 5 rupees each. How much does she pay?",o:[["🔟","10 rupees"],["7️⃣","7 rupees"],["5️⃣","5 rupees"],["2️⃣","2 rupees"]],h:"Five and five more."},
{e:"🧮",q:"Rohan has 8 marbles and finds 4 more. How many now?",o:[["1️⃣2️⃣","12"],["4️⃣","4"],["1️⃣0️⃣","10"],["1️⃣4️⃣","14"]],h:"Eight and four more."},
{e:"🤔",q:"There are 9 laddoos shared equally among 3 children. How many each?",o:[["3️⃣","3"],["2️⃣","2"],["9️⃣","9"],["6️⃣","6"]],h:"Three groups of three."},
{e:"📝",q:"Which is the SMALLEST two-digit number?",o:[["1️⃣0️⃣","10"],["1️⃣","1"],["9️⃣9️⃣","99"],["1️⃣1️⃣","11"]],h:"The very first number with two digits."},
{e:"🧐",q:"Which is the LARGEST two-digit number?",o:[["9️⃣9️⃣","99"],["1️⃣0️⃣0️⃣","100"],["9️⃣0️⃣","90"],["1️⃣0️⃣","10"]],h:"Just before one hundred."},
{e:"💭",q:"What comes next: 20, 30, 40, __ ?",o:[["5️⃣0️⃣","50"],["4️⃣5️⃣","45"],["6️⃣0️⃣","60"],["4️⃣1️⃣","41"]],h:"Counting in tens."},
{e:"🎓",q:"What comes next: 2, 4, 8, 10, __ ? Careful!",o:[["1️⃣2️⃣","12"],["1️⃣1️⃣","11"],["1️⃣6️⃣","16"],["2️⃣0️⃣","20"]],h:"They are all even numbers going up by two."},
{e:"🔢",q:"How many ones are there in 1 ten?",o:[["🔟","10"],["1️⃣","1"],["5️⃣","5"],["2️⃣0️⃣","20"]],h:"One bundle of ten sticks."},
{e:"🧮",q:"Which coin do we NOT have in India?",o:[["3️⃣","A 3 rupee coin"],["1️⃣","A 1 rupee coin"],["2️⃣","A 2 rupee coin"],["5️⃣","A 5 rupee coin"]],h:"Think about what is really in your purse."},
{e:"🤔",q:"How many 2 rupee coins make 10 rupees?",o:[["5️⃣","5"],["2️⃣","2"],["🔟","10"],["4️⃣","4"]],h:"Two, four, six, eight, ten."},
{e:"📝",q:"What time is it when the long hand is on 12 and short hand on 3?",o:[["3️⃣","3 o'clock"],["1️⃣2️⃣","12 o'clock"],["6️⃣","6 o'clock"],["9️⃣","9 o'clock"]],h:"The short hand tells the hour."},
{e:"🧐",q:"Which is longer: an hour or a minute?",o:[["⏰","An hour"],["⏱️","A minute"],["🟰","Both same"],["0️⃣","Neither"]],h:"Sixty of one make the other."},
{e:"💭",q:"Which weighs more: a kilo or a gram?",o:[["⚖️","A kilo"],["🪶","A gram"],["🟰","Both same"],["0️⃣","Neither"]],h:"One kilo is a thousand grams."},
{e:"🎓",q:"Which unit do we use to buy milk?",o:[["🥛","Litres"],["📏","Metres"],["⚖️","Kilograms"],["🕐","Hours"]],h:"We measure liquids this way."},
{e:"🔢",q:"Which unit do we use to buy cloth?",o:[["📏","Metres"],["🥛","Litres"],["🕐","Hours"],["🌡️","Degrees"]],h:"The tailor measures length."},
{e:"🧮",q:"Which solid shape has NO flat face at all?",o:[["⚽","A sphere"],["🎲","A cube"],["🥫","A cylinder"],["📦","A cuboid"]],h:"It rolls in every direction, with nowhere to rest flat."},
{e:"🤔",q:"How many faces does a cube have?",o:[["6️⃣","6"],["4️⃣","4"],["8️⃣","8"],["1️⃣2️⃣","12"]],h:"Look at a dice: how many numbers?"},
{e:"📝",q:"A chocolate bar is cut into 4 equal parts. You eat 1. What did you eat?",o:[["🍫","One quarter"],["🍫","One half"],["🍫","All of it"],["🍫","Nothing"]],h:"One out of four equal pieces."}
]
};
