module.exports = {
"Science": [
{e:"🔬",q:"Odd one out by NUMBER OF LEGS: which is different?",o:[["🕷️","Spider"],["🐝","Bee"],["🐜","Ant"],["🦋","Butterfly"]],h:"Three have six legs. One has eight."},
{e:"🧪",q:"Which of these is a NATURAL thing, not man-made?",o:[["🌊","A river"],["🪑","A chair"],["🚗","A car"],["🏠","A house"]],h:"Nobody built it. It was always there."},
{e:"🤔",q:"Which source of water is UNDERGROUND?",o:[["🕳️","A well"],["🌊","The sea"],["🌧️","Rain"],["🏞️","A river"]],h:"You lower a bucket down into the ground."},
{e:"🧐",q:"Which is the GASEOUS form of water?",o:[["♨️","Water vapour"],["🧊","Ice"],["💧","Liquid water"],["❄️","Snow"]],h:"You cannot see it, but it is in the air."},
{e:"💭",q:"Which is a MAN-MADE container for storing water?",o:[["🪣","A tank"],["🌊","The sea"],["🏞️","A river"],["🌧️","A cloud"]],h:"Built by people on a rooftop."},
{e:"🎓",q:"Which of these do plants NOT need to grow?",o:[["📺","A television"],["💧","Water"],["☀️","Sunlight"],["🌬️","Air"]],h:"Three are essential. One is just for us."},
{e:"📝",q:"What happens to a plant kept in a completely dark cupboard?",o:[["🥀","It turns pale and dies"],["📈","It grows faster"],["🌸","It flowers more"],["🎨","It turns red"]],h:"No sunlight means no food."},
{e:"🔬",q:"Which animal group does a frog belong to, living in water and on land?",o:[["🐸","Amphibians"],["🐦","Birds"],["🐟","Fish"],["🐄","Mammals"]],h:"Amphi means both."},
{e:"🧪",q:"Which animals feed their babies with milk?",o:[["🐄","Mammals"],["🐦","Birds"],["🐟","Fish"],["🐍","Snakes"]],h:"Cows, dogs, cats and humans too."},
{e:"🤔",q:"Are human beings mammals?",o:[["✅","Yes"],["❌","No"],["🐦","No, we are birds"],["🐟","No, we are fish"]],h:"Babies drink their mother's milk."},
{e:"🧐",q:"Which sense would help us most in a completely dark room?",o:[["👂","Hearing and touch"],["👁️","Sight"],["🎨","Colour"],["📏","Measuring"]],h:"Your eyes are useless with no light."},
{e:"💭",q:"Why do we see lightning BEFORE we hear thunder?",o:[["⚡","Light travels faster than sound"],["🔊","Sound is quiet"],["☁️","Clouds block it"],["🌧️","Rain slows it"]],h:"They happen together, but light wins the race."},
{e:"🎓",q:"Which surface would a ball roll furthest on?",o:[["🛣️","A smooth floor"],["🏖️","Sand"],["🌿","Thick grass"],["🪨","Rocky ground"]],h:"Less friction means a longer roll."},
{e:"📝",q:"Why do we put rubber grips on a cycle handle?",o:[["✋","So our hands do not slip"],["🎨","To look nice"],["⚖️","To make it heavy"],["🔊","To make noise"]],h:"Rubber grips well, metal is slippery."},
{e:"🔬",q:"Which of these would a magnet NOT pick up?",o:[["🥄","A plastic spoon"],["📎","A paper clip"],["🔩","A nail"],["✂️","Steel scissors"]],h:"Magnets only like certain metals."},
{e:"🧪",q:"What happens if we mix sugar into water?",o:[["🫗","It dissolves and disappears"],["🪨","It sinks as a lump"],["🛟","It floats on top"],["🔥","It burns"]],h:"The water tastes sweet but looks clear."},
{e:"🤔",q:"What happens if we mix sand into water?",o:[["⬇️","It settles at the bottom"],["🫗","It dissolves"],["🛟","It floats"],["💨","It disappears"]],h:"Unlike sugar, it does not dissolve."},
{e:"🧐",q:"Which part of the plant carries water up from the roots?",o:[["🌿","The stem"],["🌸","The flower"],["🍎","The fruit"],["🌰","The seed"]],h:"Like a straw running up the middle."},
{e:"💭",q:"Why do we boil drinking water?",o:[["🦠","Heat kills the germs"],["🎨","To change its colour"],["🍬","To make it sweet"],["🧊","To cool it"]],h:"Then we let it cool and drink it."},
{e:"🎓",q:"Which of these is a source of LIGHT and HEAT together?",o:[["🔥","Fire"],["🧊","Ice"],["🪞","A mirror"],["🌑","A shadow"]],h:"It glows and it warms you."},
{e:"📝",q:"Does a mirror make its own light?",o:[["❌","No, it only reflects light"],["✅","Yes"],["🌙","Only at night"],["☀️","Only in summer"]],h:"In a dark room a mirror shows nothing."},
{e:"🔬",q:"Which of these is a sense organ?",o:[["👅","The tongue"],["🦴","A bone"],["❤️","The heart"],["🫁","The lungs"]],h:"It tells us about taste."},
{e:"🧪",q:"Which animal would you find in a nest, an egg and a beak?",o:[["🐦","A bird"],["🐄","A cow"],["🐟","A fish"],["🐍","A snake"]],h:"All three belong to the same creature."},
{e:"🤔",q:"Odd one out: which does NOT come from a plant?",o:[["🥛","Milk"],["🍚","Rice"],["🍎","Apple"],["🌾","Wheat"]],h:"Three grow in fields or on trees."},
{e:"🧐",q:"What should we do with waste water from washing vegetables?",o:[["🪴","Use it to water plants"],["🗑️","Throw it down the drain"],["🌊","Pour it on the road"],["🔥","Boil it away"]],h:"It is clean enough for the garden."}
],

"Computer": [
{e:"💻",q:"Which key do we press to delete the letter AFTER the cursor?",o:[["🗑️","Delete"],["⬅️","Backspace"],["␣","Spacebar"],["↩️","Enter"]],h:"Backspace goes left. This one goes right."},
{e:"🔌",q:"Which keys do we use to move around a page?",o:[["⬆️","The arrow keys"],["🔢","The number keys"],["🔠","The letter keys"],["␣","The spacebar"]],h:"Up, down, left and right."},
{e:"🤔",q:"What do we call clicking the mouse button twice quickly?",o:[["2️⃣","A double click"],["1️⃣","A single click"],["👉","A right click"],["✋","A drag"]],h:"It usually opens something."},
{e:"🧐",q:"What usually happens when we RIGHT click?",o:[["📋","A little menu appears"],["🚪","The computer shuts down"],["🖨️","It prints"],["🔊","It plays music"]],h:"A list of choices pops up."},
{e:"💭",q:"What do we call holding the mouse button and moving something?",o:[["✋","Dragging"],["👆","Clicking"],["⌨️","Typing"],["🔊","Listening"]],h:"Drag and drop."},
{e:"🎓",q:"Which program do we use to write a letter on a computer?",o:[["📝","A word processor"],["🎨","A paint program"],["🎵","A music player"],["🎮","A game"]],h:"You type, and you can change the font."},
{e:"📝",q:"What do we call a picture we take of the screen?",o:[["📸","A screenshot"],["🎬","A film"],["🖨️","A printout"],["📻","A recording"]],h:"It saves exactly what you can see."},
{e:"💻",q:"Which part of the computer stores all our files even when it is off?",o:[["💾","The hard disk"],["🖥️","The monitor"],["🔊","The speaker"],["🖱️","The mouse"]],h:"That is why your work is still there tomorrow."},
{e:"🔌",q:"What should we do BEFORE closing a file we have been working on?",o:[["💾","Save it"],["🚪","Just close it"],["🔌","Pull the plug"],["🔨","Hit the screen"]],h:"Otherwise all your work disappears."},
{e:"🤔",q:"What do we call a set of instructions that tells a computer what to do?",o:[["📋","A program"],["🎨","A picture"],["🎵","A song"],["🪑","A chair"]],h:"People who write them are called programmers."},
{e:"🧐",q:"What is the very first thing a computer shows when it starts?",o:[["🖥️","The desktop"],["🎮","A game"],["🖨️","A printout"],["🔊","A song"]],h:"With icons and a wallpaper."},
{e:"💭",q:"Which button makes a window fill the whole screen?",o:[["⬜","Maximise"],["➖","Minimise"],["❌","Close"],["🔊","Volume"]],h:"The square button at the top right."},
{e:"🎓",q:"Which button closes a window completely?",o:[["❌","The red cross"],["➖","The minus"],["⬜","The square"],["🔊","The speaker"]],h:"Top right corner, and usually red."},
{e:"📝",q:"What do we call the bar at the bottom of the screen with open programs?",o:[["📊","The taskbar"],["🖼️","The wallpaper"],["📁","A folder"],["🖨️","The printer"]],h:"The Start button lives there too."},
{e:"💻",q:"Which device do we use to draw directly on a screen?",o:[["✏️","A stylus"],["🖨️","A printer"],["🔊","A speaker"],["💾","A pen drive"]],h:"A special pen for tablets."},
{e:"🔌",q:"Which is an INPUT device?",o:[["🎤","A microphone"],["🖨️","A printer"],["🖥️","A monitor"],["🔊","A speaker"]],h:"It sends information INTO the computer."},
{e:"🤔",q:"Which is an OUTPUT device?",o:[["🔊","A speaker"],["⌨️","A keyboard"],["🖱️","A mouse"],["📷","A camera"]],h:"It gives information OUT to us."},
{e:"🧐",q:"Why should we not keep a magnet near a computer?",o:[["🧲","It can damage stored information"],["🎨","It changes the colour"],["🔊","It makes noise"],["🌡️","It heats it"]],h:"Magnets and stored data do not mix."},
{e:"💭",q:"Which is the safest kind of password?",o:[["🔐","A long one only you know"],["1️⃣","1234"],["📛","Your own name"],["🎂","Your birthday"]],h:"Easy to guess means easy to break."},
{e:"🎓",q:"What should we do if a strange window pops up asking for money?",o:[["🧑","Close it and tell a grown-up"],["💳","Give the card number"],["👆","Click on it"],["📞","Call the number"]],h:"These tricks are called scams."},
{e:"📝",q:"How much screen time is healthy for a Class 1 child each day?",o:[["⏳","About an hour or less"],["🌞","All day"],["🌙","All night"],["📆","All weekend"]],h:"Play outside for much longer than you sit inside."},
{e:"💻",q:"What should we do to our eyes during long computer use?",o:[["👀","Blink often and look away sometimes"],["🙈","Never blink"],["👓","Stare harder"],["💡","Turn off all lights"]],h:"Staring at a screen dries the eyes out."},
{e:"🔌",q:"What does a UPS do during a power cut?",o:[["🔋","Keeps the computer on for a short time"],["🖨️","Prints"],["🔊","Plays music"],["🧹","Cleans"]],h:"Just long enough to save and shut down."},
{e:"🤔",q:"Which of these is a computer we use every day without noticing?",o:[["📱","A smartphone"],["🪑","A chair"],["🥄","A spoon"],["📕","A book"]],h:"It has a screen, memory and programs."},
{e:"🧐",q:"Who should decide how long you use the computer?",o:[["👨‍👩‍👧","Your parents, together with you"],["🧒","Only you"],["🤖","The computer"],["🐕","The dog"]],h:"Agree a rule and stick to it."}
],

"Logical Reasoning": [
{e:"🧩",q:"Odd one out by SHAPE OF SIDES: which one is curved?",o:[["⚪","Circle"],["🔺","Triangle"],["🟥","Square"],["▭","Rectangle"]],h:"Three are made of straight lines only."},
{e:"❓",q:"Odd one out: which does NOT belong with the others?",o:[["🪑","Chair"],["🍎","Apple"],["🍌","Banana"],["🥭","Mango"]],h:"Three you can eat."},
{e:"🤔",q:"Odd one out by WHERE THEY LIVE: which is a wild animal?",o:[["🦁","Lion"],["🐄","Cow"],["🐕","Dog"],["🐈","Cat"]],h:"Three live with people at home."},
{e:"🧐",q:"Odd one out: which is NOT a day of the week?",o:[["🌸","March"],["1️⃣","Monday"],["5️⃣","Friday"],["7️⃣","Sunday"]],h:"One of them is a month."},
{e:"💭",q:"Odd one out: which is NOT a season?",o:[["🕐","Tuesday"],["☀️","Summer"],["❄️","Winter"],["🌧️","Rainy"]],h:"One of them is a day."},
{e:"🎓",q:"In the row 5 6 7 8 9, which number is 2nd from the RIGHT?",o:[["8️⃣","8"],["9️⃣","9"],["6️⃣","6"],["7️⃣","7"]],h:"Start at 9 and count back two."},
{e:"📝",q:"In the word MANGO, which letter is 3rd?",o:[["🅽","N"],["🅼","M"],["🅶","G"],["🅾️","O"]],h:"M is first, A is second..."},
{e:"🔎",q:"In a queue of 6 children, Meena is LAST. What is her position?",o:[["6️⃣","6th"],["1️⃣","1st"],["3️⃣","3rd"],["5️⃣","5th"]],h:"Last means nobody is behind her."},
{e:"🧩",q:"Amit is shorter than Ravi. Ravi is shorter than Sohan. Who is SHORTEST?",o:[["🧍","Amit"],["🧍","Ravi"],["🧍","Sohan"],["🟰","All same"]],h:"Amit is below Ravi, who is below Sohan."},
{e:"❓",q:"Rani is heavier than Sita. Sita is heavier than Gita. Who is LIGHTEST?",o:[["🪶","Gita"],["⚖️","Rani"],["🧍","Sita"],["🟰","All same"]],h:"Work down the line from heaviest."},
{e:"🤔",q:"What comes next in this NUMBER pattern: 1, 2, 4, 8, __ ?",o:[["1️⃣6️⃣","16"],["1️⃣0️⃣","10"],["1️⃣2️⃣","12"],["9️⃣","9"]],h:"Each number is double the one before."},
{e:"🧐",q:"What comes next: Z, Y, X, W, __ ?",o:[["🆅","V"],["🆄","U"],["🅰️","A"],["🅱️","B"]],h:"The alphabet, but going backwards."},
{e:"💭",q:"What is MISSING: 5, 10, __, 20, 25 ?",o:[["1️⃣5️⃣","15"],["1️⃣2️⃣","12"],["1️⃣8️⃣","18"],["1️⃣1️⃣","11"]],h:"Counting in fives."},
{e:"🎓",q:"Sun is to Day, as Moon is to ___ ?",o:[["🌙","Night"],["🌈","Rainbow"],["☔","Rain"],["❄️","Snow"]],h:"When do we see each one?"},
{e:"📝",q:"Doctor is to Medicine, as Teacher is to ___ ?",o:[["📚","Books"],["💊","Pills"],["🚗","Cars"],["🍚","Rice"]],h:"What tool does each one work with?"},
{e:"🔎",q:"Cow is to Milk, as Hen is to ___ ?",o:[["🥚","Eggs"],["🧶","Wool"],["🍯","Honey"],["🥛","Milk"]],h:"What do we get from each?"},
{e:"🧩",q:"Bee is to Honey, as Sheep is to ___ ?",o:[["🧶","Wool"],["🥚","Eggs"],["🥛","Milk"],["🍯","Honey"]],h:"What does each animal give us?"},
{e:"❓",q:"Summer is to Hot, as Winter is to ___ ?",o:[["🥶","Cold"],["🥵","Hot"],["💦","Wet"],["🌈","Colourful"]],h:"How does each season feel?"},
{e:"🤔",q:"Big is to Small, as Tall is to ___ ?",o:[["📏","Short"],["📐","Wide"],["⚖️","Heavy"],["🎨","Colourful"]],h:"Each pair is opposites."},
{e:"🧐",q:"Open is to Shut, as Up is to ___ ?",o:[["⬇️","Down"],["➡️","Right"],["⬅️","Left"],["🔄","Around"]],h:"Opposites again."},
{e:"💭",q:"You have 15 sweets. How many groups of 5 can you make?",o:[["3️⃣","3"],["5️⃣","5"],["2️⃣","2"],["4️⃣","4"]],h:"5 and 5 and 5 makes fifteen."},
{e:"🎓",q:"You share 8 biscuits equally between 2 friends. How many each?",o:[["4️⃣","4"],["2️⃣","2"],["8️⃣","8"],["6️⃣","6"]],h:"Half of eight."},
{e:"📝",q:"How many CORNERS does a triangle have?",o:[["3️⃣","3"],["4️⃣","4"],["2️⃣","2"],["0️⃣","None"]],h:"The same as its number of sides."},
{e:"🔎",q:"If today is Monday, what day will it be tomorrow?",o:[["2️⃣","Tuesday"],["7️⃣","Sunday"],["3️⃣","Wednesday"],["6️⃣","Saturday"]],h:"The next day in the week."},
{e:"🧩",q:"If today is Wednesday, what day was it YESTERDAY?",o:[["2️⃣","Tuesday"],["4️⃣","Thursday"],["1️⃣","Monday"],["5️⃣","Friday"]],h:"Go one day backwards."}
]
};
