module.exports = {
"Places & Monuments": [
{e:"🗺️",q:"Which state is the Taj Mahal in?",o:[["🕌","Uttar Pradesh"],["🐪","Rajasthan"],["🥥","Kerala"],["🍵","Assam"]],h:"Agra is in this big northern state."},
{e:"🔍",q:"Which is the largest state of India by NUMBER OF PEOPLE?",o:[["👥","Uttar Pradesh"],["🐪","Rajasthan"],["🏖️","Goa"],["🏔️","Sikkim"]],h:"Rajasthan is biggest by land, but this one has more people."},
{e:"🧐",q:"Which city is the capital of Rajasthan?",o:[["🏰","Jaipur"],["🏛️","Delhi"],["🌊","Mumbai"],["🌉","Kolkata"]],h:"The Pink City."},
{e:"🎓",q:"Which city is the capital of Maharashtra?",o:[["🌊","Mumbai"],["🏰","Jaipur"],["❄️","Shimla"],["🍵","Guwahati"]],h:"Home of the Gateway of India."},
{e:"📖",q:"Which state is famous for its houseboats on the Dal Lake?",o:[["🏔️","Jammu and Kashmir"],["🏖️","Goa"],["🐪","Rajasthan"],["🍵","Assam"]],h:"Called the paradise on Earth."},
{e:"🗺️",q:"Which Indian city has the Hawa Mahal, the Palace of Winds?",o:[["🏰","Jaipur"],["🕌","Agra"],["🌊","Mumbai"],["🌉","Kolkata"]],h:"It has hundreds of tiny windows."},
{e:"🔍",q:"Which monument in Delhi was built in memory of Mahatma Gandhi?",o:[["🕯️","Raj Ghat"],["🏰","Red Fort"],["🗼","Qutub Minar"],["🚪","India Gate"]],h:"A simple black platform with an eternal flame."},
{e:"🧐",q:"Which city is famous for the Ajanta and Ellora caves?",o:[["🕳️","Aurangabad"],["🏖️","Goa"],["❄️","Shimla"],["🌴","Kochi"]],h:"Ancient caves carved into solid rock."},
{e:"🎓",q:"Which sea route city is called the Gateway of South India?",o:[["🏖️","Chennai"],["❄️","Shimla"],["🏔️","Ladakh"],["🐪","Jaisalmer"]],h:"On the east coast, with Marina Beach."},
{e:"📖",q:"Which is the longest beach city on India's east coast?",o:[["🏖️","Chennai"],["🏔️","Shimla"],["🏜️","Jaisalmer"],["🌲","Dehradun"]],h:"Marina Beach is one of the longest in the world."},
{e:"🗺️",q:"In which state will you find the Sun Temple with a stone chariot?",o:[["☀️","Odisha"],["🌾","Punjab"],["🏖️","Goa"],["🍵","Assam"]],h:"At Konark, near the sea."},
{e:"🔍",q:"Which state has the famous Meenakshi Temple at Madurai?",o:[["💃","Tamil Nadu"],["🌾","Punjab"],["🐪","Rajasthan"],["🍵","Assam"]],h:"The same state that celebrates Pongal."},
{e:"🧐",q:"Which river is called the sorrow of Bihar because it floods?",o:[["🌊","Kosi"],["🏞️","Ganga"],["💧","Yamuna"],["🏔️","Narmada"]],h:"It changes its path and floods the fields."},
{e:"🎓",q:"Which is the highest waterfall in India?",o:[["⛲","Kunchikal Falls"],["🌊","Sea Falls"],["🏔️","Snow Falls"],["🏜️","Sand Falls"]],h:"It is in Karnataka."},
{e:"📖",q:"Which state is known as the Spice Garden of India?",o:[["🌶️","Kerala"],["🐪","Rajasthan"],["❄️","Ladakh"],["🌾","Punjab"]],h:"Pepper, cardamom and cloves grow there."},
{e:"🗺️",q:"What is a 'stepwell' that we see in Rajasthan and Gujarat?",o:[["🪜","A well with steps going down to the water"],["🏔️","A mountain"],["🌉","A bridge"],["🏰","A fort"]],h:"Baoli! People walked down to fetch water."},
{e:"🔍",q:"Which desert animal fair happens at Pushkar?",o:[["🐪","Camels"],["🐟","Fish"],["🐧","Penguins"],["🐻","Bears"]],h:"Thousands come to buy and sell them."},
{e:"🧐",q:"Which is the busiest kind of place in a city, full of shops?",o:[["🛒","A market"],["🏞️","A park"],["📚","A library"],["🏥","A hospital"]],h:"Bazaar! Noisy and crowded."},
{e:"🎓",q:"Where would we go to see very old things from long ago?",o:[["🏛️","A museum"],["🏦","A bank"],["🏊","A swimming pool"],["🛒","A market"]],h:"Sangrahalaya! Coins, statues and fossils."},
{e:"📖",q:"Where do we go to watch a film on a big screen?",o:[["🎬","A cinema"],["🏥","A hospital"],["🏦","A bank"],["📮","A post office"]],h:"With popcorn and comfy seats."},
{e:"🗺️",q:"Which building keeps records of who owns land?",o:[["🏛️","A government office"],["🦁","A zoo"],["🏊","A pool"],["🎬","A cinema"]],h:"Sarkari daftar. Very full of files!"},
{e:"🔍",q:"Which is the coldest inhabited village in India?",o:[["🥶","Dras in Ladakh"],["🏖️","Goa"],["🌴","Kochi"],["🐪","Jaisalmer"]],h:"In the far north, near Kargil."},
{e:"🧐",q:"On a map of India, which direction is Kashmir?",o:[["⬆️","North"],["⬇️","South"],["➡️","East"],["⬅️","West"]],h:"Right at the very top."},
{e:"🎓",q:"On a map of India, which direction is Kanyakumari?",o:[["⬇️","South"],["⬆️","North"],["➡️","East"],["⬅️","West"]],h:"Right at the very bottom tip."},
{e:"📖",q:"What do three seas meet at, in Kanyakumari?",o:[["🌊","The very tip of India"],["🏔️","A mountain top"],["🏜️","A desert"],["🌴","A forest"]],h:"Land ends and water begins on three sides."}
],

"Earth & Nature": [
{e:"🌦️",q:"Which month usually brings the monsoon to Kerala first?",o:[["🌧️","June"],["❄️","January"],["🎄","December"],["🌸","March"]],h:"The rains arrive in the south first, early summer's end."},
{e:"🔍",q:"What do we call the long dry spell with no rain at all?",o:[["🏜️","A drought"],["🌊","A flood"],["🌈","A rainbow"],["❄️","Snow"]],h:"Sukha! Wells dry up and crops fail."},
{e:"🧐",q:"What do we call it when rivers overflow and cover the land?",o:[["🌊","A flood"],["🏜️","A drought"],["🌈","A rainbow"],["🌪️","A tornado"]],h:"Baadh! Houses and fields go under water."},
{e:"🎓",q:"Why should we save water even when it rains a lot?",o:[["💧","Clean water is limited and precious"],["💰","It is expensive"],["🎨","It is colourful"],["🤷","No reason"]],h:"Most of the Earth's water is salty and cannot be drunk."},
{e:"📖",q:"What do we call water that soaks into the ground?",o:[["🕳️","Groundwater"],["🌊","Sea water"],["🌧️","Rain water"],["♨️","Steam"]],h:"We pull it back up from wells and borewells."},
{e:"🌦️",q:"Which gas do plants take IN from the air?",o:[["💨","Carbon dioxide"],["🌬️","Oxygen"],["💧","Water vapour"],["🔥","Smoke"]],h:"They take in what we breathe out."},
{e:"🔍",q:"What do we call the air around our Earth?",o:[["🌍","The atmosphere"],["🌊","The ocean"],["🏔️","The mountain"],["🌳","The forest"]],h:"A big blanket of air holding us in."},
{e:"🧐",q:"Which of these makes the air dirty?",o:[["🏭","Smoke from vehicles and factories"],["🌳","Trees"],["🌸","Flowers"],["💧","Rain"]],h:"Pollution! It makes us cough."},
{e:"🎓",q:"What can we do to make less rubbish?",o:[["♻️","Reuse and recycle things"],["🗑️","Throw more away"],["🔥","Burn it all"],["🕳️","Bury plastic"]],h:"Carry a cloth bag instead of taking plastic ones."},
{e:"📖",q:"Which bag is better for the Earth?",o:[["👜","A cloth bag"],["🛍️","A plastic bag"],["🎈","A balloon"],["📄","A thin film wrapper"]],h:"You can wash it and use it hundreds of times."},
{e:"🌦️",q:"How long does plastic take to rot away in the soil?",o:[["⏳","Hundreds of years"],["📆","One day"],["🗓️","One week"],["🌙","One night"]],h:"Almost forever. That is why we must not litter."},
{e:"🔍",q:"Which of these rots away quickly and safely in soil?",o:[["🍌","A banana peel"],["🍾","A plastic bottle"],["🔋","A battery"],["🪟","Glass"]],h:"Kitchen waste turns into compost."},
{e:"🧐",q:"What do we call rotted kitchen waste used to feed plants?",o:[["🟤","Compost"],["🧂","Salt"],["🏖️","Sand"],["🔩","Iron"]],h:"Free food for your garden!"},
{e:"🎓",q:"Which season do most trees shed their leaves?",o:[["🍂","Autumn"],["☀️","Summer"],["🌧️","Rainy"],["❄️","Winter"]],h:"Patjhad! The ground goes crunchy."},
{e:"📖",q:"What do we call the study of weather?",o:[["🌡️","Weather forecasting"],["🔢","Counting"],["🎨","Painting"],["🎵","Music"]],h:"It tells us if we need an umbrella tomorrow."},
{e:"🌦️",q:"What do we use to measure how hot or cold it is?",o:[["🌡️","A thermometer"],["📏","A ruler"],["🕐","A clock"],["⚖️","A weighing scale"]],h:"A thin tube with a red or silver line."},
{e:"🔍",q:"What do we call the very hot wind in North India in summer?",o:[["🥵","The loo"],["❄️","Snow"],["🌈","A rainbow"],["💧","Dew"]],h:"So hot that people stay indoors at noon."},
{e:"🧐",q:"What are the tiny water drops on grass early in the morning?",o:[["💧","Dew"],["❄️","Snow"],["🌊","Sea water"],["🔥","Smoke"]],h:"Os! They dry up as the sun rises."},
{e:"🎓",q:"What do we call thick low cloud that makes it hard to see?",o:[["🌫️","Fog"],["🌈","A rainbow"],["⚡","Lightning"],["🌊","A wave"]],h:"Kohra! Common on winter mornings in Delhi."},
{e:"📖",q:"Where does the water in a river finally go?",o:[["🌊","Into the sea"],["🏔️","Up a mountain"],["🏜️","Into a desert"],["☁️","Straight into a cloud"]],h:"Rivers always flow downhill to the ocean."},
{e:"🌦️",q:"Where does the water in clouds come from?",o:[["☀️","The sun lifts it from seas and rivers"],["🕳️","Holes in the ground"],["🌳","Trees make it"],["🪨","Rocks make it"]],h:"Heat turns water into vapour, which rises."},
{e:"🔍",q:"What do we call the journey of water from sea to cloud to rain to sea?",o:[["🔄","The water cycle"],["🚲","A bicycle"],["🔁","A song"],["🎡","A wheel"]],h:"It goes round and round forever."},
{e:"🧐",q:"Why do we plant trees along roads?",o:[["🌳","For shade and clean air"],["🎨","To look colourful"],["🔊","To make noise"],["🚗","To block cars"]],h:"They cool the road and soak up smoke."},
{e:"🎓",q:"What happens if we cut down too many trees?",o:[["🏜️","Less rain and more dust"],["🌧️","More rain"],["❄️","More snow"],["🌈","More rainbows"]],h:"Trees help bring rain and hold soil together."},
{e:"📖",q:"On which date is World Environment Day?",o:[["🌍","5 June"],["🎄","25 December"],["1️⃣","1 January"],["1️⃣5️⃣","15 August"]],h:"In the month the monsoon arrives."}
]
};
