module.exports = {
"Plants & Food": [
{e:"🌿",q:"Which part of the MANGO plant gives rise to the fruit?",o:[["🌸","The flower"],["🪴","The root"],["🌳","The branch"],["🍃","The leaf"]],h:"First a flower blooms, then it becomes a fruit."},
{e:"🔍",q:"Which food is in the SAME group as an egg?",o:[["🧀","Cheese"],["🍊","Orange"],["🧈","Butter"],["🍬","Sugar"]],h:"Both help us grow. They are body-building foods."},
{e:"🧐",q:"Which foods help us GROW taller and stronger?",o:[["🥛","Milk, dal and eggs"],["🍭","Toffees"],["🥤","Cold drinks"],["🍟","Fried chips"]],h:"Body-building foods, full of protein."},
{e:"🎓",q:"Which foods give us ENERGY to run and play?",o:[["🍚","Rice, roti and potato"],["🧂","Salt"],["💧","Water"],["🌶️","Chilli"]],h:"The ones that fill your tummy at every meal."},
{e:"📖",q:"Which part of the potato plant do we eat?",o:[["🪴","The part under the ground"],["🌸","The flower"],["🍃","The leaf"],["🌿","The stem above ground"]],h:"You dig it out of the soil."},
{e:"🌿",q:"Which part of the spinach plant do we eat?",o:[["🍃","The leaves"],["🪴","The root"],["🌸","The flower"],["🌰","The seed"]],h:"Green and flat, we cook them in palak."},
{e:"🔍",q:"Which part of the cauliflower do we eat?",o:[["🌸","The flower"],["🪴","The root"],["🍃","The leaf"],["🌿","The stem"]],h:"Gobi! The white bunchy part."},
{e:"🧐",q:"Which food do we get from the sea?",o:[["🐟","Fish"],["🌾","Wheat"],["🥔","Potato"],["🥭","Mango"]],h:"Fishermen catch it in big nets."},
{e:"🎓",q:"How do we know a fruit is ripe and ready to eat?",o:[["🎨","It changes colour and smells sweet"],["🪨","It gets very hard"],["⚫","It turns black"],["❄️","It gets cold"]],h:"A green mango turns yellow when ready."},
{e:"📖",q:"What happens to food if we leave it out for many days?",o:[["🦠","It spoils and grows fungus"],["✨","It becomes tastier"],["📈","It grows bigger"],["🍬","It turns sweet"]],h:"Germs get into it. Never eat it then!"},
{e:"🌿",q:"Why do we keep milk in the fridge?",o:[["❄️","Cold stops it going sour"],["🎨","To change its colour"],["📈","To make more of it"],["🍬","To make it sweet"]],h:"Germs grow slowly when it is cold."},
{e:"🔍",q:"Which drink should we have instead of a cold drink?",o:[["🥥","Fresh fruit juice or nimbu paani"],["🥤","Fizzy soda"],["☕","Strong coffee"],["🍦","A milkshake every day"]],h:"Fresh and homemade beats fizzy and sugary."},
{e:"🧐",q:"Which spice do we add to food for a black peppery taste?",o:[["⚫","Kali mirch"],["🍬","Sugar"],["🟡","Haldi"],["🧂","Salt"]],h:"Little black balls we grind."},
{e:"🎓",q:"Which plant part do we eat when we eat ginger?",o:[["🪴","The underground part"],["🌸","The flower"],["🍃","The leaf"],["🌰","The seed"]],h:"Adrak! Knobbly and brown, dug from the soil."},
{e:"📖",q:"Which tree is called the Kalpavriksha because every part is useful?",o:[["🥥","The coconut tree"],["🌹","The rose bush"],["🌵","The cactus"],["🎋","The bamboo"]],h:"Water, fruit, oil, leaves and wood all come from it."},
{e:"🌿",q:"What do farmers spread on fields to help plants grow?",o:[["🟤","Manure"],["🧂","Salt"],["🏖️","Sand"],["🪨","Stones"]],h:"Khaad! It feeds the soil."},
{e:"🔍",q:"What does a plant do if we forget to water it for many days?",o:[["🥀","It wilts and dries up"],["📈","It grows faster"],["🌸","It flowers more"],["🎨","It turns blue"]],h:"The leaves go droopy and brown."},
{e:"🧐",q:"Which season do farmers sow wheat in North India?",o:[["❄️","Winter"],["☀️","Summer"],["🌧️","Rainy"],["🍂","Autumn"]],h:"Rabi crop. Sown in the cold months."},
{e:"🎓",q:"Which food comes wrapped in its own natural cover?",o:[["🍌","A banana"],["🍚","Rice"],["🥛","Milk"],["🧂","Salt"]],h:"You peel it off and throw it in the bin."},
{e:"📖",q:"Which of these is a dry fruit?",o:[["🥜","Almond"],["🍉","Watermelon"],["🍊","Orange"],["🍇","Grapes"]],h:"Badam! We eat a few soaked every morning."},
{e:"🌿",q:"Why should we chew our food slowly?",o:[["😋","It helps our tummy digest it"],["⏱️","To waste time"],["📣","To make noise"],["🤷","No reason"]],h:"Big lumps are hard for the tummy."},
{e:"🔍",q:"Which food helps us see well in the dark?",o:[["🥕","Carrots"],["🍭","Toffees"],["🍟","Chips"],["🥤","Cold drinks"]],h:"Orange and crunchy, full of vitamin A."},
{e:"🧐",q:"Which fruit is given to sick people because it is easy to digest?",o:[["🍎","Apple"],["🌶️","Chilli"],["🧅","Onion"],["🧄","Garlic"]],h:"An apple a day keeps the doctor away!"},
{e:"🎓",q:"Where do we store grain in a village?",o:[["🏚️","In a granary"],["🏦","In a bank"],["🦁","In a zoo"],["📮","In a post office"]],h:"A big dry store, safe from rats and rain."},
{e:"📖",q:"Which meal of the day should never be skipped?",o:[["🌅","Breakfast"],["🍪","Evening snack"],["🍬","Dessert"],["🥤","A cold drink"]],h:"It breaks your night-long fast and starts the day."}
],

"Festivals & Culture": [
{e:"🎊",q:"Which festival is celebrated with a huge fair at Pushkar in Rajasthan?",o:[["🐪","The camel fair"],["🐟","A fish fair"],["🐧","A penguin fair"],["🦁","A lion fair"]],h:"Thousands of desert animals gather there."},
{e:"🔍",q:"On Govardhan Puja, what did Krishna lift?",o:[["⛰️","A whole mountain"],["🌊","A river"],["🌳","A tree"],["🏠","A house"]],h:"He held it on one little finger to shelter everyone."},
{e:"🧐",q:"Which festival celebrates the bond between a brother and sister in the south?",o:[["🎀","Raksha Bandhan"],["🍚","Pongal"],["🌺","Onam"],["🔥","Lohri"]],h:"The same rakhi festival, celebrated everywhere."},
{e:"🎓",q:"What do we offer to Lord Ganesha as his favourite sweet?",o:[["🥟","Modak"],["🍫","Chocolate"],["🍦","Ice cream"],["🍟","Chips"]],h:"A steamed dumpling filled with coconut and gud."},
{e:"📖",q:"On which festival do we worship books and instruments of learning?",o:[["📚","Saraswati Puja"],["🎨","Holi"],["🪔","Diwali"],["🪁","Makar Sankranti"]],h:"Goddess of learning. Also called Basant Panchami."},
{e:"🎊",q:"Which colour do people wear on Basant Panchami?",o:[["🟡","Yellow"],["⚫","Black"],["🟤","Brown"],["⬜","Grey"]],h:"The colour of mustard flowers in the fields."},
{e:"🔍",q:"Which festival marks the end of the month of fasting for Muslims?",o:[["🌙","Eid-ul-Fitr"],["🪔","Diwali"],["🎨","Holi"],["🎄","Christmas"]],h:"It comes right after Ramzan."},
{e:"🧐",q:"What is the month of fasting called in Islam?",o:[["🌙","Ramzan"],["🪔","Diwali"],["🌾","Baisakhi"],["🔥","Lohri"]],h:"People eat before sunrise and after sunset."},
{e:"🎓",q:"Which festival do Jains celebrate by asking forgiveness from everyone?",o:[["🙏","Paryushan"],["🎨","Holi"],["🪁","Makar Sankranti"],["🔥","Lohri"]],h:"They say Michhami Dukkadam: forgive me."},
{e:"📖",q:"On which day do we remember Lord Buddha's birth?",o:[["☸️","Buddha Purnima"],["🪔","Diwali"],["🎨","Holi"],["🌾","Baisakhi"]],h:"On a full moon night in spring."},
{e:"🎊",q:"Where did Lord Buddha get his enlightenment?",o:[["🌳","Under a tree at Bodh Gaya"],["🌊","In the sea"],["🏔️","On Everest"],["🏜️","In the desert"]],h:"A peepal tree in Bihar."},
{e:"🔍",q:"Which musical instrument is played at weddings and temples in the south?",o:[["🎺","Nadaswaram"],["🎸","Guitar"],["🎹","Piano"],["🥁","Drum set"]],h:"A long wind instrument, very loud and joyful."},
{e:"🧐",q:"Which stringed instrument does Goddess Saraswati hold?",o:[["🪕","The veena"],["🥁","A drum"],["🎺","A trumpet"],["🎹","A piano"]],h:"A big stringed instrument resting on her lap."},
{e:"🎓",q:"Which dance from Odisha is performed in temples?",o:[["💃","Odissi"],["🥁","Bhangra"],["🪘","Garba"],["🎺","Bihu"]],h:"Its name sounds like the state it comes from."},
{e:"📖",q:"What is a 'thali' in an Indian meal?",o:[["🍽️","A big plate with many small bowls"],["🥤","A drink"],["👗","A dress"],["🎵","A song"]],h:"Dal, sabzi, roti, rice and sweet, all together."},
{e:"🎊",q:"Why do we not waste food at a festival feast?",o:[["🙏","Food is precious and many go hungry"],["💰","It costs nothing"],["🗑️","The bin is far"],["🤷","No reason"]],h:"Take a small helping first, then more if you want."},
{e:"🔍",q:"What do we call the sweet prasad given at a temple?",o:[["🙏","Prasad"],["🍔","A burger"],["🥤","A cold drink"],["🍟","Chips"]],h:"We take it with both hands and eat it respectfully."},
{e:"🧐",q:"Which hand do we traditionally use to give and receive things?",o:[["🤝","The right hand"],["🤲","The left hand"],["🦶","The foot"],["👘","The elbow"]],h:"It shows respect in Indian custom."},
{e:"🎓",q:"Which festival is celebrated with a lamp floating on a river?",o:[["🪔","Dev Deepawali"],["🎨","Holi"],["🪁","Makar Sankranti"],["🔥","Lohri"]],h:"Thousands of diyas float on the Ganga at Varanasi."},
{e:"📖",q:"On Makar Sankranti, which sweet do we share made of til and gud?",o:[["🟤","Til laddoo"],["🍦","Ice cream"],["🍟","Chips"],["🥤","Cola"]],h:"Til means sesame seeds. Sticky and sweet!"},
{e:"🎊",q:"What do we say when giving til laddoo on Sankranti?",o:[["🤝","Til gud ghya, goad goad bola"],["😠","Go away"],["🌙","Good night"],["😔","Sorry"]],h:"It means: take this sweet and speak sweetly."},
{e:"🔍",q:"Which festival of Kerala has men dancing dressed as tigers?",o:[["🐅","Pulikali at Onam"],["🎨","Holi"],["🔥","Lohri"],["🌾","Baisakhi"]],h:"Puli means tiger. They paint their bodies."},
{e:"🧐",q:"Which festival do we celebrate for Lord Shiva at night?",o:[["🔱","Mahashivratri"],["🪈","Janmashtami"],["🏹","Ram Navami"],["🌺","Onam"]],h:"Ratri means night. People stay awake and pray."},
{e:"🎓",q:"Why do we touch a book with our head if it falls down?",o:[["📚","Books are treated as holy"],["🧹","To clean it"],["🎨","To colour it"],["🤷","No reason"]],h:"Knowledge is respected like a goddess."},
{e:"📖",q:"What should we do with old flowers and leaves after a puja?",o:[["🌱","Put them in soil to make compost"],["🌊","Throw them in a river"],["🛣️","Throw them on the road"],["🔥","Burn plastic with them"]],h:"They rot down and feed the plants again."}
]
};
