window.MBQ_BANK = (window.MBQ_BANK || []).concat([{
name:"Maths", deva:"गणित", emoji:"🔢", color:"chalk", qs:[
{e:"🧮",q:"What comes just AFTER 5?",o:[["6️⃣","6"],["4️⃣","4"],["7️⃣","7"],["3️⃣","3"]],h:"Count up: four, five, then..."},
{e:"🧮",q:"What comes just BEFORE 9?",o:[["8️⃣","8"],["🔟","10"],["7️⃣","7"],["6️⃣","6"]],h:"One step back from nine."},
{e:"🧮",q:"Which number comes BETWEEN 6 and 8?",o:[["7️⃣","7"],["5️⃣","5"],["9️⃣","9"],["🔟","10"]],h:"Six, then... then eight!"},
{e:"🔢",q:"Which number is missing: 1, 2, __, 4?",o:[["3️⃣","3"],["5️⃣","5"],["6️⃣","6"],["0️⃣","0"]],h:"Say it out loud: one, two, ..., four."},
{e:"⬆️",q:"Which is BIGGER, 7 or 4?",o:[["7️⃣","7"],["4️⃣","4"],["🟰","Both same"],["0️⃣","Neither"]],h:"Which one would you rather have in toffees?"},
{e:"⬇️",q:"Which is SMALLER, 3 or 8?",o:[["3️⃣","3"],["8️⃣","8"],["🟰","Both same"],["0️⃣","Neither"]],h:"The one you reach first when counting."},
{e:"🔢",q:"Which is the BIGGEST number here?",o:[["2️⃣1️⃣","21"],["1️⃣2️⃣","12"],["9️⃣","9"],["1️⃣5️⃣","15"]],h:"Look at the tens first. Which has two tens?"},
{e:"🔢",q:"Which is the SMALLEST number here?",o:[["9️⃣","9"],["1️⃣2️⃣","12"],["2️⃣1️⃣","21"],["1️⃣5️⃣","15"]],h:"Only one of them is less than ten."},
{e:"0️⃣",q:"Which is the smallest number of all?",o:[["0️⃣","0"],["1️⃣","1"],["5️⃣","5"],["9️⃣","9"]],h:"It means nothing at all. Zero!"},
{e:"➕",q:"What is 2 + 3?",o:[["5️⃣","5"],["4️⃣","4"],["6️⃣","6"],["7️⃣","7"]],h:"Hold up 2 fingers, then 3 more. Count them!"},
{e:"➕",q:"What is 4 + 4?",o:[["8️⃣","8"],["6️⃣","6"],["7️⃣","7"],["9️⃣","9"]],h:"Four on one hand, four on the other."},
{e:"➕",q:"What is 5 + 5?",o:[["🔟","10"],["8️⃣","8"],["9️⃣","9"],["1️⃣1️⃣","11"]],h:"All the fingers on both your hands!"},
{e:"➕",q:"What is 10 + 10?",o:[["2️⃣0️⃣","20"],["1️⃣2️⃣","12"],["1️⃣5️⃣","15"],["3️⃣0️⃣","30"]],h:"Two tens together."},
{e:"➖",q:"What is 9 - 3?",o:[["6️⃣","6"],["5️⃣","5"],["7️⃣","7"],["3️⃣","3"]],h:"Start at nine and count back three."},
{e:"➖",q:"What is 7 - 2?",o:[["5️⃣","5"],["4️⃣","4"],["6️⃣","6"],["9️⃣","9"]],h:"Seven toffees, you eat two."},
{e:"➖",q:"What is 10 - 10?",o:[["0️⃣","0"],["1️⃣","1"],["🔟","10"],["5️⃣","5"]],h:"You gave away every single one!"},
{e:"🍬",q:"You have 3 toffees and eat 1. How many are left?",o:[["2️⃣","2"],["3️⃣","3"],["4️⃣","4"],["1️⃣","1"]],h:"Three take away one."},
{e:"✏️",q:"You have 2 pencils and Mummy gives 3 more. How many now?",o:[["5️⃣","5"],["4️⃣","4"],["6️⃣","6"],["3️⃣","3"]],h:"Two and three more."},
{e:"🐦",q:"5 birds are sitting. 2 fly away. How many are left?",o:[["3️⃣","3"],["2️⃣","2"],["5️⃣","5"],["7️⃣","7"]],h:"Five take away two."},
{e:"➕",q:"What is 1 MORE than 10?",o:[["1️⃣1️⃣","11"],["9️⃣","9"],["1️⃣2️⃣","12"],["🔟","10"]],h:"Just one step up from ten."},
{e:"➖",q:"What is 1 LESS than 10?",o:[["9️⃣","9"],["1️⃣1️⃣","11"],["8️⃣","8"],["🔟","10"]],h:"Just one step down from ten."},
{e:"✌️",q:"What is DOUBLE of 4?",o:[["8️⃣","8"],["6️⃣","6"],["4️⃣","4"],["2️⃣","2"]],h:"Double means the same amount twice."},
{e:"🍰",q:"What is HALF of 10?",o:[["5️⃣","5"],["2️⃣","2"],["🔟","10"],["2️⃣0️⃣","20"]],h:"Share ten toffees equally with one friend."},
{e:"🚲",q:"How many wheels do 2 bicycles have?",o:[["4️⃣","4"],["2️⃣","2"],["3️⃣","3"],["6️⃣","6"]],h:"Two wheels each. Two and two."},
{e:"🐄",q:"How many legs do 2 cows have?",o:[["8️⃣","8"],["4️⃣","4"],["6️⃣","6"],["🔟","10"]],h:"Four legs each. Four and four."},
{e:"🔟",q:"How many TENS are there in 20?",o:[["2️⃣","2"],["1️⃣","1"],["🔟","10"],["2️⃣0️⃣","20"]],h:"Ten and ten makes twenty."},
{e:"✍️",q:"How do we write FIFTEEN in numbers?",o:[["1️⃣5️⃣","15"],["5️⃣1️⃣","51"],["5️⃣","5"],["5️⃣0️⃣","50"]],h:"One ten and five more."},
{e:"✍️",q:"How do we write 30 in words?",o:[["3️⃣0️⃣","Thirty"],["3️⃣","Three"],["1️⃣3️⃣","Thirteen"],["3️⃣3️⃣","Thirty three"]],h:"Three tens."},
{e:"🔢",q:"How many zeros are there in 100?",o:[["2️⃣","Two"],["1️⃣","One"],["3️⃣","Three"],["0️⃣","None"]],h:"One, zero, zero. Count the round ones!"},
{e:"🔢",q:"Which of these is an EVEN number?",o:[["4️⃣","4"],["3️⃣","3"],["5️⃣","5"],["7️⃣","7"]],h:"Even numbers can be shared equally by two."},
{e:"🔢",q:"Which of these is an ODD number?",o:[["7️⃣","7"],["2️⃣","2"],["4️⃣","4"],["6️⃣","6"]],h:"Odd numbers always leave one extra."},
{e:"🔁",q:"What comes next: 2, 4, 6, __?",o:[["8️⃣","8"],["7️⃣","7"],["9️⃣","9"],["🔟","10"]],h:"We are skipping by two each time."},
{e:"🔁",q:"What comes next: 5, 10, 15, __?",o:[["2️⃣0️⃣","20"],["1️⃣6️⃣","16"],["2️⃣5️⃣","25"],["1️⃣8️⃣","18"]],h:"We are jumping five each time."},
{e:"🎨",q:"What comes next: red, blue, red, blue, __?",o:[["🔴","Red"],["🟢","Green"],["🟡","Yellow"],["⚫","Black"]],h:"The pattern keeps repeating!"},
{e:"📐",q:"Which shape has 3 sides?",o:[["🔺","Triangle"],["🟥","Square"],["⚪","Circle"],["▭","Rectangle"]],h:"Like a samosa!"},
{e:"📐",q:"Which shape has 4 equal sides?",o:[["🟥","Square"],["🔺","Triangle"],["⚪","Circle"],["▭","Rectangle"]],h:"Like a chess board box."},
{e:"📐",q:"Which shape is round with no corners?",o:[["⚪","Circle"],["🔺","Triangle"],["🟥","Square"],["▭","Rectangle"]],h:"Like a chapati or a bangle."},
{e:"📐",q:"Which shape is long and flat, like a door?",o:[["▭","Rectangle"],["⚪","Circle"],["🔺","Triangle"],["🔷","Diamond"]],h:"Two long sides and two short sides."},
{e:"📏",q:"How many corners does a SQUARE have?",o:[["4️⃣","4"],["3️⃣","3"],["5️⃣","5"],["0️⃣","None"]],h:"One in each corner of the box."},
{e:"📏",q:"How many sides does a TRIANGLE have?",o:[["3️⃣","3"],["4️⃣","4"],["2️⃣","2"],["5️⃣","5"]],h:"Tri means three!"},
{e:"📏",q:"How many corners does a CIRCLE have?",o:[["0️⃣","None"],["1️⃣","One"],["3️⃣","Three"],["4️⃣","Four"]],h:"Run your finger around it. Do you bump anywhere?"},
{e:"📏",q:"How many sides does a RECTANGLE have?",o:[["4️⃣","4"],["3️⃣","3"],["5️⃣","5"],["6️⃣","6"]],h:"Same as a square, but two are longer."},
{e:"⚖️",q:"Which is HEAVIER, a stone or a feather?",o:[["🪨","A stone"],["🪶","A feather"],["🟰","Both same"],["0️⃣","Neither"]],h:"One floats down slowly, one drops with a thud."},
{e:"📏",q:"Which is LONGER, a pencil or a bus?",o:[["🚌","A bus"],["✏️","A pencil"],["🟰","Both same"],["0️⃣","Neither"]],h:"One fits in your bag, one carries fifty people!"},
{e:"📏",q:"Which is TALLER, a tree or a flower?",o:[["🌳","A tree"],["🌸","A flower"],["🟰","Both same"],["0️⃣","Neither"]],h:"You have to look up at one of them."},
{e:"💰",q:"Which is worth the MOST money?",o:[["🔟","Ten rupees"],["1️⃣","One rupee"],["2️⃣","Two rupees"],["5️⃣","Five rupees"]],h:"The biggest number of rupees."},
{e:"🪙",q:"How many one-rupee coins make five rupees?",o:[["5️⃣","5"],["2️⃣","2"],["🔟","10"],["1️⃣","1"]],h:"One, two, three, four, five!"},
{e:"🕐",q:"Which hand of the clock is LONGER?",o:[["⏱️","The minute hand"],["⏰","The hour hand"],["🟰","Both same"],["0️⃣","Neither"]],h:"The one that moves faster is the long one."},
{e:"🕛",q:"What time is it when both clock hands point to 12?",o:[["1️⃣2️⃣","12 o'clock"],["6️⃣","6 o'clock"],["3️⃣","3 o'clock"],["9️⃣","9 o'clock"]],h:"Both hands together at the top."},
{e:"🏁",q:"If you are 3rd in a line, how many children are in FRONT of you?",o:[["2️⃣","2"],["3️⃣","3"],["1️⃣","1"],["4️⃣","4"]],h:"First and second are ahead of you."},
{e:"➕",q:"Which sign means ADD?",o:[["➕","+"],["➖","-"],["🟰","="],["✖️","x"]],h:"It looks like a little plus cross."},
{e:"➖",q:"Which sign means TAKE AWAY?",o:[["➖","-"],["➕","+"],["🟰","="],["✖️","x"]],h:"Just one straight line lying down."},
{e:"🟰",q:"Which sign means IS EQUAL TO?",o:[["🟰","="],["➕","+"],["➖","-"],["✖️","x"]],h:"Two little lines, exactly the same."}
]}]);
