window.MBQ_BANK = (window.MBQ_BANK || []).concat([{
name:"Science", deva:"विज्ञान", emoji:"🔬", color:"cyan", qs:[
{e:"🔬",q:"Which one of these is LIVING?",o:[["🐕","A dog"],["🪑","A chair"],["🪨","A stone"],["📕","A book"]],h:"Living things eat, grow and move."},
{e:"🔬",q:"Which one of these is NON-LIVING?",o:[["🪑","A table"],["🐈","A cat"],["🌳","A tree"],["🐦","A bird"]],h:"It cannot eat or grow by itself."},
{e:"🧐",q:"Can a stone grow bigger by itself?",o:[["❌","No"],["✅","Yes"],["🌧️","Only in rain"],["☀️","Only in sun"]],h:"Only living things grow."},
{e:"🏃",q:"Which of these can move on its own?",o:[["🐈","A cat"],["🪨","A rock"],["☕","A cup"],["🪑","A chair"]],h:"Moving by itself is a sign of life."},
{e:"🌱",q:"Do plants need water to stay alive?",o:[["✅","Yes"],["❌","No"],["🌙","Only at night"],["❄️","Only in winter"]],h:"That is why we water them every day."},
{e:"🐣",q:"Which animal lays EGGS?",o:[["🐔","A hen"],["🐄","A cow"],["🐕","A dog"],["🐈","A cat"]],h:"She sits on them until the chicks come out."},
{e:"🍼",q:"Which animal gives birth to live babies?",o:[["🐄","A cow"],["🐔","A hen"],["🐦‍⬛","A crow"],["🦆","A duck"]],h:"Her baby drinks milk, it does not hatch."},
{e:"🪶",q:"Which animal has FEATHERS?",o:[["🦜","A parrot"],["🐄","A cow"],["🐕","A dog"],["🐟","A fish"]],h:"Feathers help with flying."},
{e:"🐟",q:"Which animal has SCALES on its body?",o:[["🐟","A fish"],["🐄","A cow"],["🐕","A dog"],["🐈","A cat"]],h:"Shiny little plates that keep it smooth in water."},
{e:"🏊",q:"Which body part helps a fish swim?",o:[["🐠","Its fins"],["🦵","Its legs"],["🪽","Its wings"],["👂","Its ears"]],h:"Little flaps on its sides and tail."},
{e:"💧",q:"Do fish need water to live?",o:[["✅","Yes, always"],["❌","No"],["☀️","Only in summer"],["🌙","Only at night"]],h:"Take them out and they cannot breathe."},
{e:"🛟",q:"Which of these FLOATS on water?",o:[["🍃","A leaf"],["🪙","A coin"],["🔩","An iron nail"],["🪨","A big stone"]],h:"The lightest one stays on top."},
{e:"⬇️",q:"Which of these SINKS in water?",o:[["🪙","A coin"],["🍃","A leaf"],["⛵","A paper boat"],["🎈","A plastic ball"]],h:"Heavy metal goes straight to the bottom."},
{e:"🧲",q:"What does a magnet pull towards itself?",o:[["🔩","Iron things"],["📄","Paper"],["🪵","Wood"],["🥤","Plastic"]],h:"Try it on a pin and then on a pencil!"},
{e:"🧊",q:"What happens to ice when it gets warm?",o:[["💧","It melts into water"],["🪨","It becomes stone"],["💨","It disappears"],["🏖️","It becomes sand"]],h:"Leave an ice cube out and watch."},
{e:"❄️",q:"What do we get if we make water very, very cold?",o:[["🧊","Ice"],["♨️","Steam"],["🏖️","Sand"],["🪨","Stone"]],h:"Put it in the freezer overnight."},
{e:"🥛",q:"Which of these is a LIQUID?",o:[["🥛","Milk"],["🪨","Stone"],["🪵","Wood"],["🔩","Iron"]],h:"A liquid flows and takes the shape of its glass."},
{e:"🧱",q:"Which of these is a SOLID?",o:[["🧱","A brick"],["🥛","Milk"],["💧","Water"],["🧃","Juice"]],h:"A solid keeps its own shape."},
{e:"💨",q:"Which of these is a GAS?",o:[["🌬️","Air"],["💧","Water"],["🪨","Stone"],["🥛","Milk"]],h:"You cannot see it, but you can feel it."},
{e:"🫁",q:"Do we need air to live?",o:[["✅","Yes"],["❌","No"],["🌙","Only at night"],["😴","Only when sleeping"]],h:"Hold your breath and count. Not for long!"},
{e:"👀",q:"Can we SEE air?",o:[["🌬️","No, but we can feel it"],["✅","Yes, it is blue"],["✅","Yes, it is white"],["❌","No, and we cannot feel it"]],h:"A fan proves it is there!"},
{e:"🍃",q:"What do we call moving air?",o:[["🌬️","Wind"],["🌧️","Rain"],["⚡","Lightning"],["🌈","A rainbow"]],h:"It makes the leaves and your hair move."},
{e:"🌑",q:"What makes a shadow?",o:[["🚧","Something blocking the light"],["💧","Water"],["🌬️","Wind"],["🔊","Sound"]],h:"Stand in the sun and look at the ground."},
{e:"🌚",q:"Can we see a shadow in a completely dark room?",o:[["❌","No"],["✅","Yes"],["🌙","Only at night"],["☀️","Only in summer"]],h:"No light means no shadow at all."},
{e:"💡",q:"Which of these gives us light at home at night?",o:[["💡","A bulb"],["🌑","A shadow"],["🚪","A cupboard"],["🪑","A table"]],h:"Flick the switch and it glows."},
{e:"🚰",q:"Which of these is a source of water?",o:[["🏞️","A river"],["🪑","A chair"],["📕","A book"],["👟","A shoe"]],h:"It flows and flows and never stops."},
{e:"☀️",q:"What do green plants use to make their own food?",o:[["☀️","Sunlight"],["🌙","Moonlight"],["🌑","Darkness"],["🌬️","Wind"]],h:"That is why plants lean towards the window."},
{e:"🌱",q:"What do we call a baby plant?",o:[["🌱","A sapling"],["🪵","A log"],["🪨","A stone"],["🍂","A dry leaf"]],h:"Small, green and just come out of the seed."},
{e:"🦴",q:"What is inside our body that helps us stand straight?",o:[["🦴","Bones"],["💇","Hair"],["💅","Nails"],["👕","Clothes"]],h:"Hard and strong, under the skin."},
{e:"🖐️",q:"Which is the biggest part of our body, covering all of it?",o:[["🖐️","The skin"],["👁️","The eye"],["👂","The ear"],["👃","The nose"]],h:"It wraps around you from head to toe."},
{e:"🧶",q:"Which of these materials is SOFT?",o:[["🧶","Cotton"],["🔩","Iron"],["🪨","Stone"],["🪟","Glass"]],h:"Your pillow is full of it."},
{e:"🪨",q:"Which of these materials is HARD?",o:[["🪨","Stone"],["🧶","Cotton"],["🐑","Wool"],["🧽","Sponge"]],h:"You cannot squeeze it at all."},
{e:"⚠️",q:"Which material breaks very easily?",o:[["🪟","Glass"],["🎈","Rubber"],["👕","Cloth"],["🥤","Plastic"]],h:"Drop it and it shatters. Be careful!"},
{e:"🌳",q:"Which of these comes from a TREE?",o:[["📄","Paper"],["🔩","Iron"],["🪟","Glass"],["🥤","Plastic"]],h:"That is why wasting it wastes trees."},
{e:"✂️",q:"What do we use to cut paper?",o:[["✂️","Scissors"],["🥄","A spoon"],["💇","A comb"],["☕","A cup"]],h:"Two sharp blades joined together."},
{e:"🔎",q:"What do we use to see very tiny things bigger?",o:[["🔍","A magnifying glass"],["🔭","A telescope"],["🪞","A mirror"],["🥄","A spoon"]],h:"Hold it over an ant and look!"},
{e:"🚪",q:"Do we PUSH or PULL to open a drawer?",o:[["🫸","Pull"],["🫷","Push"],["🔄","Twist"],["🤸","Jump"]],h:"You bring it towards you."},
{e:"🚪",q:"Do we PUSH or PULL to close an open door?",o:[["🫷","Push"],["🫸","Pull"],["🔄","Twist"],["🤸","Jump"]],h:"You send it away from you."},
{e:"⬇️",q:"If you drop a ball, where does it go?",o:[["⬇️","Down to the ground"],["⬆️","Up to the sky"],["➡️","Sideways"],["🛑","It stays still"]],h:"Everything falls down. Always!"},
{e:"🔊",q:"Which of these is a SOUND?",o:[["🔔","A bell ringing"],["🌑","A shadow"],["🎨","A colour"],["👃","A smell"]],h:"You hear it with your ears."},
{e:"👕",q:"What happens to a wet cloth left in the sun?",o:[["☀️","It dries"],["💧","It gets wetter"],["🧊","It freezes"],["🔥","It burns"]],h:"The sun takes the water away."},
{e:"🥶",q:"Which machine keeps our food cold?",o:[["🧊","A fridge"],["🔥","A stove"],["🪭","A fan"],["📺","A TV"]],h:"It hums in the kitchen and has a freezer on top."},
{e:"🔥",q:"Which of these is HOT?",o:[["☀️","The sun"],["🧊","Ice"],["❄️","Snow"],["🥶","A freezer"]],h:"Too hot to ever touch or look at."},
{e:"🍚",q:"Which food comes from a PLANT?",o:[["🍚","Rice"],["🥛","Milk"],["🥚","Egg"],["🐟","Fish"]],h:"It grows in a field full of water."},
{e:"🐄",q:"Which food comes from an ANIMAL?",o:[["🥛","Milk"],["🍚","Rice"],["🌾","Wheat"],["🫘","Dal"]],h:"The cow gives it to us."},
{e:"🤕",q:"What should we do if we get a small cut?",o:[["🧼","Wash it and tell a grown-up"],["🙈","Hide it"],["🟤","Put mud on it"],["🤷","Do nothing"]],h:"Clean water first, then a grown-up."},
{e:"👃",q:"Which part of our body do we use to smell a flower?",o:[["👃","The nose"],["👂","The ear"],["🦶","The foot"],["💇","The hair"]],h:"Take a deep sniff!"},
{e:"🌞",q:"Which season comes with the most sunshine and heat?",o:[["☀️","Summer"],["❄️","Winter"],["🍂","Autumn"],["🌸","Spring"]],h:"The season of ice cream and holidays."},
{e:"🪵",q:"Which of these can burn?",o:[["🪵","Wood"],["💧","Water"],["🪨","Stone"],["🔩","Iron"]],h:"We use it to make a fire."},
{e:"🐜",q:"How do ants carry food back to their home?",o:[["🐜","In a long line together"],["🪽","By flying"],["🏊","By swimming"],["🤸","By jumping"]],h:"They follow each other one behind the other."},
{e:"🌻",q:"Which part of a plant grows towards the sunlight?",o:[["🌿","The shoot above the ground"],["🪴","The root"],["🌰","The seed"],["🟤","The soil"]],h:"Roots go down, this one goes up!"},
{e:"♻️",q:"Which of these should we recycle instead of throwing away?",o:[["🍾","Plastic bottles"],["🍌","Banana peel"],["🍂","Dry leaves"],["🥚","Egg shells"]],h:"The one that never rots away in the soil."}
]}]);
