window.MBQ_BANK = (window.MBQ_BANK || []).concat([{
name:"Gadgets & Tech", deva:"गैजेट और तकनीक", emoji:"📱", color:"steel", qs:[
{e:"📱",q:"Give a GROUP NAME: Laptop, Tablet, Webcam, Smartphone",o:[["📱","Gadgets"],["🪑","Furniture"],["🍽️","Utensils"],["💍","Jewellery"]],h:"All of them are electronic machines."},
{e:"🔍",q:"Give a GROUP NAME: Printer, Speaker, Monitor",o:[["📤","Output devices"],["📥","Input devices"],["🪑","Furniture"],["🍽️","Utensils"]],h:"They all give things OUT to us."},
{e:"🧐",q:"Give a GROUP NAME: Keyboard, Mouse, Microphone",o:[["📥","Input devices"],["📤","Output devices"],["🪑","Furniture"],["👕","Clothes"]],h:"They all put things IN to the computer."},
{e:"🤖",q:"What do we call a machine that can do work like a person?",o:[["🤖","A robot"],["🪑","A chair"],["📕","A book"],["🥄","A spoon"]],h:"It can walk, talk and follow instructions."},
{e:"⌚",q:"Which gadget do we wear on our wrist and it also counts our steps?",o:[["⌚","A smartwatch"],["🖥️","A desktop"],["🖨️","A printer"],["📻","A radio"]],h:"It looks like a watch but does much more."},
{e:"📺",q:"Which gadget lets us watch programmes at home?",o:[["📺","A television"],["🖨️","A printer"],["🥄","A spoon"],["🪑","A chair"]],h:"It sits in the living room."},
{e:"📻",q:"Which gadget lets us only LISTEN to news and songs?",o:[["📻","A radio"],["📺","A television"],["🖨️","A printer"],["📷","A camera"]],h:"No picture, only sound."},
{e:"📷",q:"Which gadget do we use to take photographs?",o:[["📷","A camera"],["🖨️","A printer"],["🔊","A speaker"],["⌨️","A keyboard"]],h:"Say cheese!"},
{e:"🎮",q:"Which gadget do we hold to play video games?",o:[["🎮","A game controller"],["🖨️","A printer"],["📷","A camera"],["🔌","A wire"]],h:"It has buttons and joysticks."},
{e:"❄️",q:"Which machine at home keeps our food cold?",o:[["🧊","A refrigerator"],["📺","A television"],["📻","A radio"],["🖨️","A printer"]],h:"It hums in the kitchen."},
{e:"🍲",q:"Which machine heats our food quickly?",o:[["♨️","A microwave oven"],["🧊","A fridge"],["📻","A radio"],["📷","A camera"]],h:"Ping! Your food is hot."},
{e:"👕",q:"Which machine washes our clothes?",o:[["🫧","A washing machine"],["🧊","A fridge"],["📺","A TV"],["📷","A camera"]],h:"It spins the clothes round and round."},
{e:"💨",q:"Which machine cleans dust from the floor by sucking it up?",o:[["🌪️","A vacuum cleaner"],["🧊","A fridge"],["📷","A camera"],["📻","A radio"]],h:"It makes a loud whooshing noise."},
{e:"🗣️",q:"Which app do we use to send instant messages to friends?",o:[["💬","A messenger app"],["🧮","A calculator"],["🕐","A clock"],["🗺️","A map"]],h:"You type and it arrives at once."},
{e:"🗺️",q:"Which app helps us find our way to a new place?",o:[["🗺️","A maps app"],["🎵","A music app"],["🧮","A calculator"],["📷","A camera"]],h:"It shows roads and directions."},
{e:"🎵",q:"Which app do we use to listen to songs?",o:[["🎵","A music app"],["🗺️","A maps app"],["🧮","A calculator"],["🕐","A clock"]],h:"Press play."},
{e:"🧮",q:"Which app helps us do sums quickly?",o:[["🧮","A calculator"],["🎵","A music app"],["📷","A camera"],["🗺️","A map"]],h:"Type the numbers and press equals."},
{e:"⏰",q:"Which app wakes us up in the morning?",o:[["⏰","An alarm clock app"],["🎵","A music app"],["🗺️","A map"],["📷","A camera"]],h:"It rings at the time you set."},
{e:"📹",q:"Which app lets us see and talk to someone far away?",o:[["📹","A video call app"],["🧮","A calculator"],["🕐","A clock"],["🗺️","A map"]],h:"You can see their face on the screen."},
{e:"❌",q:"Which of these is NOT something a computer can do?",o:[["👕","Wash your clothes"],["🎬","Play a film"],["🎮","Play a game"],["🎵","Play music"]],h:"One of these needs a different machine."},
{e:"❌",q:"Which of these is NOT a gadget?",o:[["🪑","A wooden chair"],["📱","A smartphone"],["💻","A laptop"],["⌚","A smartwatch"]],h:"Three need electricity."},
{e:"❌",q:"Select the INCORRECT match.",o:[["❌","Printer and listening to music"],["✅","Speaker and sound"],["✅","Monitor and pictures"],["✅","Keyboard and typing"]],h:"One pair does not belong together at all."},
{e:"🪟",q:"Which company makes Windows 11?",o:[["🪟","Microsoft"],["🍎","Apple"],["🚗","Tata"],["📮","India Post"]],h:"Its name has Micro and Soft in it."},
{e:"▶️",q:"In Windows 11, which button opens the Start menu?",o:[["🪟","The Windows button"],["🔊","The volume button"],["🔌","The plug"],["🖨️","The printer"]],h:"It has four little squares on it."},
{e:"🔎",q:"In Windows 11, what does the magnifying glass icon do?",o:[["🔍","It searches"],["🖨️","It prints"],["🔊","It plays sound"],["🗑️","It deletes"]],h:"You type what you are looking for."},
{e:"💾",q:"What do we call information stored on a computer?",o:[["💾","Data"],["🍚","Food"],["👕","Clothes"],["🪑","Furniture"]],h:"Photos, songs and files are all this."},
{e:"☁️",q:"Where can we store our photos so they are safe even if the phone is lost?",o:[["☁️","In the cloud"],["🗑️","In the bin"],["🪑","Under a chair"],["🎒","In a bag"]],h:"Not a real cloud, but a store on the internet."},
{e:"🔋",q:"What do we do when a phone battery is low?",o:[["🔌","Charge it"],["💧","Wash it"],["🔨","Hit it"],["🗑️","Throw it"]],h:"Plug it in."},
{e:"🌐",q:"What do we need for a video call to work?",o:[["📶","An internet connection"],["🥄","A spoon"],["🪑","A chair"],["📕","A book"]],h:"Without it, nothing loads."},
{e:"📶",q:"What do we call the wireless internet at home?",o:[["📶","Wi-Fi"],["🔌","A plug"],["🔋","A battery"],["🖨️","A printer"]],h:"You connect to it with a password."},
{e:"🔐",q:"Why should a Wi-Fi have a password?",o:[["🔐","So strangers cannot use it"],["🎨","To look nice"],["🔊","To be loud"],["💰","To cost more"]],h:"It keeps your home network private."},
{e:"🚫",q:"What should we do if an app asks for our parent's card number?",o:[["🧑","Say no and tell a parent"],["💳","Type the number"],["📷","Send a photo of it"],["🤐","Keep it secret"]],h:"Never enter money details yourself."},
{e:"👀",q:"What should we do if something on a screen makes us uncomfortable?",o:[["🧑","Close it and tell a grown-up"],["🤐","Keep watching"],["📣","Share it with friends"],["🙈","Hide it"]],h:"Always tell someone you trust."},
{e:"🤝",q:"Is it safe to accept a friend request from someone you do not know?",o:[["❌","No, never"],["✅","Yes, always"],["🎂","Only on birthdays"],["🌙","Only at night"]],h:"Online strangers are still strangers."},
{e:"🏧",q:"Which machine outside a bank gives us money?",o:[["🏧","An ATM"],["🖨️","A printer"],["📷","A camera"],["📻","A radio"]],h:"Three letters. You put a card in."},
{e:"🎫",q:"How can we book a train ticket without going to the station?",o:[["📱","Online on a phone or computer"],["📮","By post only"],["🚶","By walking there"],["🤷","We cannot"]],h:"IRCTC has an app and a website."},
{e:"💳",q:"What do we call paying with a phone by scanning a code?",o:[["📱","A digital payment"],["🪙","Giving coins"],["📜","Writing a letter"],["🤝","Shaking hands"]],h:"UPI! Very common in India now."},
{e:"🏫",q:"How did children attend class when schools were shut?",o:[["💻","Online classes"],["📮","By post"],["📻","By radio only"],["🤷","They did not"]],h:"On a screen, from home."},
{e:"🩺",q:"How can a doctor see a patient who lives far away?",o:[["📹","By video call"],["📮","By post"],["🚶","By walking"],["🤷","They cannot"]],h:"Telemedicine."},
{e:"🚜",q:"How do computers help farmers today?",o:[["🌦️","They tell them the weather forecast"],["🍚","They cook food"],["👕","They wash clothes"],["😴","They sleep"]],h:"Knowing if rain is coming helps them plan."},
{e:"🚦",q:"How do computers help control city traffic?",o:[["🚦","They run the traffic lights"],["🍚","They cook"],["👕","They wash"],["😴","They sleep"]],h:"Timed red, yellow and green."},
{e:"🚀",q:"How do computers help ISRO?",o:[["🚀","They guide rockets and satellites"],["🍚","They cook food"],["👕","They wash clothes"],["🎵","They sing"]],h:"Chandrayaan needed thousands of calculations."},
{e:"🏥",q:"Which machine in a hospital takes a picture of our bones?",o:[["🦴","An X-ray machine"],["🖨️","A printer"],["📻","A radio"],["🧊","A fridge"]],h:"It shows what is under the skin."},
{e:"🛒",q:"What does the machine at a shop counter do with a barcode?",o:[["🔍","It scans it to find the price"],["🍽️","It eats it"],["🎨","It colours it"],["🎵","It sings"]],h:"Beep! The price appears."},
{e:"🎧",q:"Why should we not listen to headphones at full volume?",o:[["👂","It can damage our ears"],["🔋","It uses battery"],["💰","It costs money"],["🎨","It looks bad"]],h:"Loud sound hurts your hearing forever."},
{e:"🌙",q:"Why should screens be switched off before bedtime?",o:[["😴","The bright light makes sleep harder"],["💰","It saves money"],["🎨","It is prettier"],["🔊","It is quieter"]],h:"Your brain thinks it is still daytime."},
{e:"♻️",q:"What should we do with a broken phone or battery?",o:[["♻️","Give it for e-waste recycling"],["🗑️","Throw it in the normal bin"],["🌊","Throw it in water"],["🔥","Burn it"]],h:"They have chemicals that harm the soil."},
{e:"💡",q:"What do we call machines that do work by themselves without a person?",o:[["🤖","Automatic machines"],["✋","Hand tools"],["🪑","Furniture"],["👕","Clothes"]],h:"Automation! Like a washing machine's cycle."},
{e:"🗣️",q:"Some phones answer when you talk to them. What is that called?",o:[["🗣️","A voice assistant"],["📖","A dictionary"],["🖨️","A printer"],["🧊","A fridge"]],h:"You say a wake word and ask a question."},
{e:"🔦",q:"Which everyday gadget in a phone replaced the torch?",o:[["🔦","The flashlight"],["🧮","The calculator"],["🗺️","The map"],["🎵","The music"]],h:"The bright light next to the camera."},
{e:"🧩",q:"Unscramble the letters to find a device: TROBO",o:[["🤖","ROBOT"],["🖨️","PRINTER"],["🔊","SPEAKER"],["🖱️","MOUSE"]],h:"Five letters. A machine that works like a person."},
{e:"🧩",q:"Unscramble the letters to find a device: TELBAT",o:[["📱","TABLET"],["🖨️","PRINTER"],["🔊","SPEAKER"],["⌨️","KEYBOARD"]],h:"A flat screen you can carry, bigger than a phone."}
]}]);
