window.MBQ_BANK = (window.MBQ_BANK || []).concat([{
name:"World Around Us", deva:"दुनिया", emoji:"🌍", color:"globe", qs:[
{e:"🌍",q:"In which city is the Statue of Liberty?",o:[["🗽","New York"],["🗼","Paris"],["🎡","London"],["🍺","Berlin"]],h:"In America, holding a torch high."},
{e:"🔍",q:"In which country is the Eiffel Tower?",o:[["🥖","France"],["🍕","Italy"],["🗾","Japan"],["🦘","Australia"]],h:"In the city of Paris."},
{e:"🧐",q:"In which country is the Great Wall?",o:[["🐼","China"],["🇮🇳","India"],["🗾","Japan"],["🦘","Australia"]],h:"A wall so long it crosses mountains."},
{e:"🎓",q:"Which country is famous for kangaroos?",o:[["🦘","Australia"],["🐼","China"],["🥖","France"],["🇮🇳","India"]],h:"They hop, and they carry babies in a pouch."},
{e:"📖",q:"Which country is known as the Land of the Rising Sun?",o:[["🗾","Japan"],["🐼","China"],["🦘","Australia"],["🥖","France"]],h:"Its flag has a red circle in the middle."},
{e:"🌍",q:"Which is the biggest ocean in the world?",o:[["🌊","The Pacific Ocean"],["🌏","The Indian Ocean"],["🚢","The Atlantic Ocean"],["🧊","The Arctic Ocean"]],h:"Its name means peaceful."},
{e:"🔍",q:"Which is the longest river in the world?",o:[["🐊","The Nile"],["🏞️","The Ganga"],["🌴","The Amazon"],["🌉","The Thames"]],h:"It flows through Egypt."},
{e:"🧐",q:"Which is the largest desert in the world?",o:[["🏜️","The Sahara"],["🐪","The Thar"],["🧊","The Arctic"],["🌴","The Amazon"]],h:"In Africa, and very very hot."},
{e:"🎓",q:"Which is the coldest place on Earth?",o:[["🐧","Antarctica"],["🏜️","The Sahara"],["🥥","Kerala"],["🏖️","Goa"]],h:"At the very bottom of the globe, where penguins live."},
{e:"📖",q:"Which animal lives in the icy Antarctic and cannot fly?",o:[["🐧","Penguin"],["🦜","Parrot"],["🦚","Peacock"],["🦅","Eagle"]],h:"Black and white, and it waddles."},
{e:"🌍",q:"Which animal lives in the icy Arctic and is white?",o:[["🐻‍❄️","Polar bear"],["🐅","Tiger"],["🦁","Lion"],["🐘","Elephant"]],h:"White fur hides it in the snow."},
{e:"🔍",q:"On which continent is India?",o:[["🌏","Asia"],["🌍","Africa"],["🌎","Europe"],["🦘","Australia"]],h:"The biggest continent of all."},
{e:"🧐",q:"How many continents are there in the world?",o:[["7️⃣","Seven"],["5️⃣","Five"],["3️⃣","Three"],["🔟","Ten"]],h:"Same as the days in a week."},
{e:"🎓",q:"What do we use to see the whole world as a ball?",o:[["🌐","A globe"],["🕐","A clock"],["📏","A ruler"],["🔭","A telescope"]],h:"It spins on a stand."},
{e:"📖",q:"What do we call a flat drawing of a country or the world?",o:[["🗺️","A map"],["🖼️","A painting"],["📷","A photo"],["📕","A book"]],h:"It shows roads, rivers and borders."},
{e:"🌍",q:"Which colour usually shows water on a map?",o:[["🔵","Blue"],["🟢","Green"],["🟤","Brown"],["🔴","Red"]],h:"The same colour as the sea looks."},
{e:"🔍",q:"Which colour usually shows mountains on a map?",o:[["🟤","Brown"],["🔵","Blue"],["⬜","White"],["🩷","Pink"]],h:"The colour of rock and earth."},
{e:"🧐",q:"What do we call people from Japan?",o:[["🗾","Japanese"],["🐼","Chinese"],["🇮🇳","Indian"],["🥖","French"]],h:"Japan plus -ese."},
{e:"🎓",q:"Which sport is played at the FIFA World Cup?",o:[["⚽","Football"],["🏏","Cricket"],["♟️","Chess"],["🏊","Swimming"]],h:"The whole world watches it every four years."},
{e:"📖",q:"In which country did the Olympic Games begin long ago?",o:[["🏛️","Greece"],["🇮🇳","India"],["🐼","China"],["🗾","Japan"]],h:"Ancient athletes competed there."},
{e:"🌍",q:"What do we call the imaginary line around the middle of the Earth?",o:[["➖","The Equator"],["⬆️","The North Pole"],["⬇️","The South Pole"],["🧭","The compass"]],h:"It is hottest there."},
{e:"🔍",q:"Which is the largest country in the world by area?",o:[["❄️","Russia"],["🇮🇳","India"],["🐼","China"],["🦘","Australia"]],h:"So big it covers many time zones."},
{e:"🧐",q:"What do we call money used in America?",o:[["💵","Dollar"],["🪙","Rupee"],["💷","Pound"],["💴","Yen"]],h:"Its sign is $."},
{e:"🎓",q:"What do we call money used in Japan?",o:[["💴","Yen"],["🪙","Rupee"],["💵","Dollar"],["💷","Pound"]],h:"Three letters, starts with Y."},
{e:"📖",q:"Which festival is celebrated all over the world on 1 January?",o:[["🎉","New Year"],["🪔","Diwali"],["🎨","Holi"],["🌙","Eid"]],h:"The first day of the calendar."},
{e:"🌍",q:"On which day is Earth Day celebrated?",o:[["🌍","22 April"],["1️⃣","1 January"],["🎄","25 December"],["1️⃣5️⃣","15 August"]],h:"In the spring month of April."},
{e:"🔍",q:"What do we call the United Nations flag colour?",o:[["🔵","Light blue"],["🔴","Red"],["⬛","Black"],["🟣","Purple"]],h:"A pale blue with a white world map."},
{e:"🧐",q:"Which language is spoken by the most people in the world?",o:[["🐼","Chinese"],["🇮🇳","Hindi"],["🥖","French"],["🇩🇪","German"]],h:"Spoken in the country with the Great Wall."},
{e:"🎓",q:"Which bird is the national bird of America?",o:[["🦅","Bald eagle"],["🦚","Peacock"],["🦜","Parrot"],["🐧","Penguin"]],h:"A powerful bird with a white head."},
{e:"📖",q:"Which is the tallest building in the world?",o:[["🏙️","Burj Khalifa"],["🗼","Qutub Minar"],["🗽","Statue of Liberty"],["🕌","Taj Mahal"]],h:"In Dubai, and it seems to touch the clouds."}
]}]);

window.MBQ_BANK = (window.MBQ_BANK || []).concat([{
name:"Stories & Rhymes", deva:"कहानी और कविता", emoji:"📚", color:"story", qs:[
{e:"📚",q:"In the story, what did the thirsty crow drop into the pot?",o:[["🪨","Pebbles"],["🍞","Bread"],["🌸","Flowers"],["🍃","Leaves"]],h:"They made the water rise up."},
{e:"🔍",q:"In the story of the greedy dog, what did he lose?",o:[["🍖","His piece of meat"],["🦴","His bone"],["🏠","His house"],["🐕","His friend"]],h:"He barked at his own reflection."},
{e:"🧐",q:"In the race, who beat the fast hare?",o:[["🐢","The tortoise"],["🐇","The rabbit"],["🐕","The dog"],["🐈","The cat"]],h:"Slow and steady wins the race."},
{e:"🎓",q:"What lesson does the tortoise and hare story teach?",o:[["🐢","Slow and steady wins the race"],["💨","Always run fast"],["😴","Sleeping is good"],["😠","Be proud"]],h:"The hare was too confident and rested."},
{e:"📖",q:"In the story, who cried wolf when there was no wolf?",o:[["👦","The shepherd boy"],["👧","A girl"],["👵","An old lady"],["🐕","A dog"]],h:"Nobody believed him when a real wolf came."},
{e:"📚",q:"What lesson does the boy who cried wolf teach?",o:[["🤥","Do not tell lies"],["🏃","Run fast"],["😴","Sleep early"],["🍽️","Eat well"]],h:"If you lie, people stop believing you."},
{e:"🔍",q:"Which Indian book of animal stories teaches wisdom?",o:[["📕","Panchatantra"],["📗","A dictionary"],["📘","A maths book"],["📙","A phone book"]],h:"Very old Indian stories with clever animals."},
{e:"🧐",q:"In the Ramayana, who is Lord Rama's wife?",o:[["👸","Sita"],["👩","Radha"],["🧕","Draupadi"],["👧","Parvati"]],h:"Ravana took her away to Lanka."},
{e:"🎓",q:"In the Ramayana, who helped Rama find Sita?",o:[["🐒","Hanuman"],["🐘","Ganesha"],["🪈","Krishna"],["🔱","Shiva"]],h:"He leapt across the sea."},
{e:"📖",q:"Which Indian epic tells the story of the Pandavas?",o:[["📜","Mahabharata"],["🏹","Ramayana"],["📕","Panchatantra"],["📗","Jataka Tales"]],h:"Five brothers and a great battle."},
{e:"📚",q:"Which clever character appears in many Indian tales as a wise minister?",o:[["🧔","Birbal"],["🐒","Hanuman"],["🐘","Ganesha"],["👸","Sita"]],h:"He solved Akbar's puzzles."},
{e:"🔍",q:"Who wrote the poem that became our national anthem?",o:[["✍️","Rabindranath Tagore"],["🧓","Gandhi ji"],["🌹","Nehru ji"],["🚀","Dr Kalam"]],h:"A great Bengali poet."},
{e:"🧐",q:"What do we call a story that is not true, with magic and fairies?",o:[["🧚","A fairy tale"],["📰","A news report"],["🧾","A bill"],["📜","A letter"]],h:"Once upon a time..."},
{e:"🎓",q:"What do we call the person who tells a story?",o:[["🗣️","A storyteller"],["🩺","A doctor"],["👨‍🍳","A cook"],["🚗","A driver"]],h:"Grandmothers are often the best ones."},
{e:"📖",q:"How do most fairy tales BEGIN?",o:[["📜","Once upon a time"],["🔚","The end"],["🌙","Good night"],["🎂","Happy birthday"]],h:"The four magic opening words."},
{e:"📚",q:"How do most fairy tales END?",o:[["😊","They lived happily ever after"],["📜","Once upon a time"],["🌅","Good morning"],["🎂","Happy birthday"]],h:"The happy closing line."},
{e:"🔍",q:"What do we call a short poem for children?",o:[["🎵","A rhyme"],["📰","A newspaper"],["🧾","A bill"],["🗺️","A map"]],h:"Like Twinkle Twinkle or Jack and Jill."},
{e:"🧐",q:"In the rhyme, who went up the hill to fetch a pail of water?",o:[["👦","Jack and Jill"],["👧","Mary"],["🐑","Little Bo Peep"],["👶","Humpty Dumpty"]],h:"And Jack fell down."},
{e:"🎓",q:"In the rhyme, who sat on a wall and had a great fall?",o:[["🥚","Humpty Dumpty"],["👦","Jack"],["👧","Mary"],["🐑","Bo Peep"]],h:"All the king's horses could not fix him."},
{e:"📖",q:"In the rhyme, what did Mary have that followed her to school?",o:[["🐑","A little lamb"],["🐕","A dog"],["🐈","A cat"],["🐦","A bird"]],h:"Its fleece was white as snow."},
{e:"📚",q:"What do we call the pictures inside a storybook?",o:[["🎨","Illustrations"],["🔢","Numbers"],["📏","Rulers"],["🎵","Songs"]],h:"They help you imagine the story."},
{e:"🔍",q:"Where in a library would you find storybooks for children?",o:[["🧒","The children's section"],["🔬","The science section"],["🗞️","The newspaper rack"],["🖥️","The computer desk"]],h:"Books are grouped by who reads them."},
{e:"🧐",q:"What should we do with a library book after reading it?",o:[["🔄","Return it on time"],["🎒","Keep it forever"],["📄","Tear it"],["🙈","Hide it"]],h:"So the next child can read it."},
{e:"🎓",q:"Which Indian tales are about the Buddha's earlier lives?",o:[["☸️","Jataka Tales"],["🏹","Ramayana"],["📜","Mahabharata"],["🧚","Fairy tales"]],h:"Animal stories with a moral."},
{e:"📖",q:"What do we call the lesson at the end of a story?",o:[["💡","The moral"],["🎨","The picture"],["📛","The title"],["✍️","The author"]],h:"It tells you what the story teaches."}
]}]);
