window.MBQ_BANK = (window.MBQ_BANK || []).concat([{
name:"People & Helpers", deva:"लोग और मददगार", emoji:"👨‍🚒", color:"helper", qs:[
/* community helpers */
{e:"👩‍🚒",q:"Who puts out fires?",o:[["🚒","A firefighter"],["👮","A policeman"],["📮","A postman"],["👞","A cobbler"]],h:"They rush in wearing a helmet and carrying a hose."},
{e:"🔍",q:"Who mends our shoes?",o:[["👞","A cobbler"],["✂️","A tailor"],["🌾","A farmer"],["📮","A postman"]],h:"Mochi! He sits with needle, thread and polish."},
{e:"🧐",q:"Who stitches our clothes?",o:[["✂️","A tailor"],["👞","A cobbler"],["🌾","A farmer"],["📮","A postman"]],h:"Darzi! He measures you first."},
{e:"🤔",q:"Who protects us and keeps law and order?",o:[["👮","A policeman"],["📮","A postman"],["✂️","A tailor"],["👨‍🍳","A cook"]],h:"You can always go to them if you are lost."},
{e:"💭",q:"Who delivers our letters and postcards?",o:[["📮","A postman"],["👮","A policeman"],["🌾","A farmer"],["👞","A cobbler"]],h:"Dakiya! He carries a big bag."},
{e:"🎓",q:"Who protects our country at the border?",o:[["🎖️","A soldier"],["👞","A cobbler"],["✂️","A tailor"],["📰","A newspaper boy"]],h:"They stand guard in heat, cold and snow."},
{e:"📝",q:"Who grows the crops we eat?",o:[["🌾","A farmer"],["👮","A policeman"],["📮","A postman"],["✂️","A tailor"]],h:"Kisan! He works in the fields."},
{e:"👨‍🚒",q:"Who controls the traffic on a busy road?",o:[["🚦","A traffic policeman"],["🌾","A farmer"],["📮","A postman"],["👞","A cobbler"]],h:"White uniform, whistle and waving hands."},
{e:"🔍",q:"Who fits and repairs the electrical wiring in our house?",o:[["⚡","An electrician"],["✂️","A tailor"],["🌾","A farmer"],["🩺","A doctor"]],h:"He comes when a fan or light stops working."},
{e:"🧐",q:"Who brings the newspaper to our door every morning?",o:[["📰","A newspaper boy"],["🩺","A doctor"],["👮","A policeman"],["✂️","A tailor"]],h:"Very early, often on a bicycle."},
{e:"🤔",q:"Who helps keep our house neat and clean?",o:[["🧹","A maid"],["👨‍✈️","A pilot"],["🌾","A farmer"],["🎖️","A soldier"]],h:"They sweep, mop and tidy up."},
{e:"💭",q:"Who teaches us in school?",o:[["👩‍🏫","A teacher"],["🩺","A doctor"],["👮","A policeman"],["🌾","A farmer"]],h:"They explain things and mark your work."},
{e:"🎓",q:"Who treats us when we are ill?",o:[["🩺","A doctor"],["✂️","A tailor"],["🌾","A farmer"],["📮","A postman"]],h:"Stethoscope around the neck."},
{e:"📝",q:"Who helps the doctor look after patients?",o:[["👩‍⚕️","A nurse"],["👮","A policeman"],["📮","A postman"],["🌾","A farmer"]],h:"They give medicines and dress wounds."},
{e:"👨‍🚒",q:"Who cuts our hair?",o:[["💈","A barber"],["👞","A cobbler"],["✂️","A tailor"],["🌾","A farmer"]],h:"Nai! Scissors and a comb."},
{e:"🔍",q:"Who bakes our bread and cakes?",o:[["🍞","A baker"],["👞","A cobbler"],["📮","A postman"],["👮","A policeman"]],h:"Up before dawn, working at a hot oven."},
{e:"🧐",q:"Who builds our houses?",o:[["🧱","A mason"],["🩺","A doctor"],["📰","A newspaper boy"],["✂️","A tailor"]],h:"Rajmistri! Bricks, cement and a trowel."},
{e:"🤔",q:"Who repairs a leaking tap or pipe?",o:[["🔧","A plumber"],["⚡","An electrician"],["✂️","A tailor"],["🌾","A farmer"]],h:"He carries a wrench and spare washers."},
{e:"💭",q:"Who brings milk to our home each morning?",o:[["🥛","A milkman"],["📰","A newspaper boy"],["📮","A postman"],["🧹","A maid"]],h:"Doodhwala! Often before you wake up."},
{e:"🎓",q:"Who sells us vegetables in the market?",o:[["🥕","A vegetable seller"],["🩺","A doctor"],["✂️","A tailor"],["👮","A policeman"]],h:"Sabziwala, with a cart or a stall."},
{e:"📝",q:"How should we behave with community helpers?",o:[["🙏","With respect and thanks"],["😠","Rudely"],["👀","Ignore them"],["😆","Laugh at them"]],h:"Every kind of work deserves respect."},
/* family */
{e:"👨‍👩‍👧",q:"What is a NUCLEAR family?",o:[["👨‍👩‍👧","Children living only with parents and brothers or sisters"],["👵","Children living with grandparents too"],["🏘️","A whole village"],["🏫","A class at school"]],h:"A small family. Just parents and children."},
{e:"🔍",q:"What is a JOINT family?",o:[["👵","Parents, children, grandparents, uncles, aunts and cousins together"],["👨‍👩‍👧","Only parents and children"],["🧍","One person alone"],["🏫","A school class"]],h:"A big family, all under one roof."},
{e:"🧐",q:"Who is your father's mother to you?",o:[["👵","Your grandmother"],["👩","Your aunt"],["👧","Your sister"],["👩‍🏫","Your teacher"]],h:"Dadi!"},
{e:"🤔",q:"Who is your mother's brother to you?",o:[["👨","Your uncle"],["👴","Your grandfather"],["👦","Your brother"],["👨‍🏫","Your teacher"]],h:"Mama!"},
{e:"💭",q:"What do we call your uncle's children?",o:[["🧒","Your cousins"],["👦","Your brothers"],["👧","Your sisters"],["👶","Your babies"]],h:"You play with them at family gatherings."},
{e:"🎓",q:"How should we treat our grandparents?",o:[["❤️","With love and respect, and help them"],["😠","Rudely"],["👀","Ignore them"],["📣","Shout at them"]],h:"They have the most stories to tell."},
/* house and rooms */
{e:"🏠",q:"What does a house protect us from?",o:[["🌧️","Heat, cold, rain and strong wind"],["🎵","Music"],["🌈","Rainbows"],["📚","Books"]],h:"Shelter is one of our basic needs."},
{e:"🔍",q:"In which room of the house do we cook?",o:[["🍳","The kitchen"],["🛏️","The bedroom"],["🛁","The bathroom"],["🛋️","The living room"]],h:"Where the stove and the spices are."},
{e:"🧐",q:"In which room do we sleep and rest?",o:[["🛏️","The bedroom"],["🍳","The kitchen"],["🛁","The bathroom"],["🚪","The verandah"]],h:"The bed lives there."},
{e:"🤔",q:"In which room do we bathe and wash?",o:[["🛁","The bathroom"],["🍳","The kitchen"],["🛏️","The bedroom"],["🛋️","The drawing room"]],h:"Soap, bucket and tap."},
{e:"💭",q:"Which kind of house do people build in very rainy places?",o:[["🏠","One with a sloping roof"],["🏢","One with a flat roof"],["⛺","A tent only"],["🕳️","A hole"]],h:"So the rain runs straight off."},
{e:"🎓",q:"What is a house made of mud and straw called?",o:[["🛖","A hut"],["🏰","A palace"],["🏢","A flat"],["⛺","A tent"]],h:"Common in villages, and cool inside."},
{e:"📝",q:"What do we call a house on wheels that travellers use?",o:[["🚐","A caravan"],["🏰","A palace"],["🛖","A hut"],["🏢","A flat"]],h:"It moves from place to place."},
/* neighbourhood */
{e:"🏘️",q:"What do we call the houses and places near our own home?",o:[["🏘️","Our neighbourhood"],["🌍","The whole world"],["🏫","A school"],["🌊","A sea"]],h:"Mohalla! The area right around you."},
{e:"🔍",q:"Which place in our neighbourhood do we go to post a letter?",o:[["📮","The post office"],["🏥","The hospital"],["🏞️","The park"],["🏫","The school"]],h:"It has a red letterbox outside."},
{e:"🧐",q:"Which place in our neighbourhood do we go to play?",o:[["🏞️","The park"],["🏥","The hospital"],["📮","The post office"],["🏦","The bank"]],h:"Swings, slides and open grass."},
{e:"🤔",q:"How should we behave with our neighbours?",o:[["🤝","Be friendly and helpful"],["😠","Fight with them"],["🔊","Play loud music at night"],["🗑️","Throw rubbish at their door"]],h:"Good neighbours help each other."},
/* needs, food and clothes */
{e:"🍚",q:"Which are our three most basic NEEDS?",o:[["🏠","Food, clothes and a house"],["🎮","Toys, games and sweets"],["📺","TV, phone and computer"],["🎂","Cake, cream and candles"]],h:"Roti, kapda aur makaan."},
{e:"🔍",q:"Why do we need food?",o:[["💪","To grow and stay healthy"],["🎨","To look colourful"],["🔊","To make noise"],["😴","To stay awake"]],h:"It gives energy and helps the body build."},
{e:"🧐",q:"Which foods give us ENERGY to work and play?",o:[["🍚","Rice and chapati"],["🍫","Chocolate and grapes"],["🥛","Milk and cheese"],["🍎","Apple and banana"]],h:"The ones that fill your plate at every meal."},
{e:"🤔",q:"What do we call a meal with the right amount of every kind of food?",o:[["🍽️","A balanced diet"],["🍭","A sweet diet"],["🍟","A fried diet"],["💧","A water diet"]],h:"It fights disease and helps you grow."},
{e:"💭",q:"Which clothes do we wear in SUMMER?",o:[["👕","Light cotton clothes"],["🧶","Thick woollen clothes"],["🧥","A raincoat"],["🧣","A muffler"]],h:"Cotton lets the air through and keeps you cool."},
{e:"🎓",q:"Which clothes do we wear in WINTER?",o:[["🧶","Warm woollen clothes"],["👕","Thin cotton clothes"],["🩱","A swimsuit"],["🩳","Shorts"]],h:"Wool traps the warm air next to you."},
{e:"📝",q:"What do we wear on a rainy day?",o:[["🧥","A raincoat"],["🧶","A sweater"],["🩱","A swimsuit"],["🧢","Only a cap"]],h:"And carry an umbrella."},
{e:"👨‍🚒",q:"Why do we wear clothes?",o:[["🛡️","To cover and protect our body"],["🔊","To make noise"],["🍽️","To eat"],["😴","To sleep only"]],h:"They protect us from heat, cold and dust."},
/* festivals, national vs religious */
{e:"🇮🇳",q:"Which of these is a NATIONAL festival of India?",o:[["🇮🇳","Republic Day"],["🪔","Diwali"],["🌙","Eid"],["🎄","Christmas"]],h:"The whole country celebrates it, whatever your religion."},
{e:"🔍",q:"Which of these is a RELIGIOUS festival?",o:[["🪔","Diwali"],["🇮🇳","Independence Day"],["🎖️","Republic Day"],["🕯️","Gandhi Jayanti"]],h:"Three of these are national days."},
{e:"🧐",q:"How many national festivals does India have?",o:[["3️⃣","Three"],["5️⃣","Five"],["🔟","Ten"],["1️⃣","One"]],h:"Republic Day, Independence Day and Gandhi Jayanti."},
/* sense organs, the ISO way */
{e:"👁️",q:"Which sense organ do we SEE with?",o:[["👁️","Our eyes"],["👂","Our ears"],["👃","Our nose"],["👅","Our tongue"]],h:"Two of them, on your face."},
{e:"🔍",q:"Select the INCORRECT statement about our sense organs.",o:[["❌","We smell with our ears"],["✅","We taste with our tongue"],["✅","We feel with our skin"],["✅","We see with our eyes"]],h:"Three are right. One swaps two organs over."},
{e:"🧐",q:"Unscramble the letters to find the body part you hold a bat with: ADHSN",o:[["✋","HANDS"],["🦵","LEGS"],["🦴","NECK"],["🤲","STOMACH"]],h:"Five letters. You grip with them."},
{e:"🤔",q:"Which body parts help us walk and run?",o:[["🦵","Our legs"],["👂","Our ears"],["👃","Our nose"],["👁️","Our eyes"]],h:"Two of them, below your waist."},
{e:"💭",q:"Which body parts help us hold, write and clap?",o:[["✋","Our hands"],["🦵","Our legs"],["👂","Our ears"],["👃","Our nose"]],h:"Ten fingers between them."}
]}]);
